### ISSUE TITLE
FATAL:  remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by jonlives** [chef/chef-server#112]
When running this command:
```
chef-server-ctl chef12-upgrade-download --download-only --chef11-data-dir /var/chef_11_data
```

to dump the data from our Chef 11 server (version 11.1.4) in preparation for upgrade, I'm getting the following exception after knife download runs.

```
Pulling open source Chef 11 database credentials
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:217:in `initialize': PG::ConnectionBad: FATAL:  remaining connection slots are reserved for non-replication superuser connections (Sequel::DatabaseConnectionError)
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:217:in `new'  
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:217:in `connect'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool.rb:96:in `make_new'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:158:in `make_new'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:137:in `available'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:127:in `block in acquire'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:194:in `block in sync'
        from <internal:prelude>:10:in `synchronize'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:194:in `sync'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:126:in `acquire'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:94:in `hold'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/database/connecting.rb:250:in `synchronize'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/shared/postgres.rb:446:in `server_version'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/shared/postgres.rb:1563:in `server_version'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/sql.rb:228:in `select_sql' 
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:139:in `each'   
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:45:in `block in all'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:856:in `_all'   
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:45:in `all'
        from (eval):386:in `create_chef11_key_file'
        from (eval):84:in `download_chef11_data_download'
        from (eval):60:in `download_chef11_data'
        from (eval):84:in `block (2 levels) in load_files'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/lib/omnibus-ctl.rb:177:in `call'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/lib/omnibus-ctl.rb:177:in `block in add_command_under_category'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/lib/omnibus-ctl.rb:555:in `run'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/bin/omnibus-ctl:31:in `<top (required)>'  
        from /opt/opscode/embedded/bin/omnibus-ctl:23:in `load'
        from /opt/opscode/embedded/bin/omnibus-ctl:23:in `<main>'
```

I'm still looking into what's causing this as our Chef 11 Server config is relatively stock - wanted to log this here so it's recorded.

**Comment by jonlives** [comment]
Closing this one off - the cause was that when `postgresql['max_connections']` is the same as `erchef['db_pool_size']` there ain't no connections left for the data download tool - we'd previously not noticed this as, of course, erchef was the only thing talking to postgres :p

**Comment by mmzyk** [comment]
@jonlives Fascinating. I'm always amazed at the myriad ways we can break software.

**Comment by mmzyk** [comment]
@jonlives We're going to update the docs to ensure this is mentioned, thanks for finding and tracking this down.

**Comment by jamescott** [comment]
https://github.com/chef/chef-docs/commit/b0b3f1e1ba48be64678681d777dbe9f79b446d18

Is building now.
