### ISSUE TITLE
Fresh server install on Jessie fails during client run - exception handlers

### ISSUE THREAD

**Issue by bklnnet** [chef/chef-server#1178]
chef-stacktrace.out
```
//--- snip---
Generated at 2017-03-24 23:01:23 -0400
Chef::Exceptions::MultipleFailures: Chef::Exceptions::MultipleFailures
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:97:in `create_superuser_in_erchef'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:50:in `block in bootstrap'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:55:in `block in with_service_connection'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:44:in `with_connection'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:52:in `with_service_connection'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:49:in `bootstrap'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb:35:in `block (2 levels) in from_file'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/provider/ruby_block.rb:35:in `call'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/provider/ruby_block.rb:35:in `block in action_run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/provider.rb:176:in `converge_by'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/provider/ruby_block.rb:34:in `action_run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/provider.rb:145:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource.rb:622:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/runner.rb:69:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:114:in `call'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/runner.rb:96:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/client.rb:670:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `catch'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/client.rb:704:in `converge_and_save'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/client.rb:284:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/application.rb:252:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/application.rb:235:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/application/client.rb:427:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/application.rb:59:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/bin/chef-client:26:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:22:in `load'
/opt/opscode/embedded/bin/chef-client:22:in `<main>'

>>>> Caused by NoMethodError: ruby_block[bootstrap-chef-server-data] (private-chef::bootstrap line 33) had an error: NoMethodError: undefined method `[]' for nil:NilClass
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:97:in `create_superuser_in_erchef'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:50:in `block in bootstrap'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:55:in `block in with_service_connection'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:44:in `with_connection'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:52:in `with_service_connection'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:49:in `bootstrap'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb:35:in `block (2 levels) in from_file'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/provider/ruby_block.rb:35:in `call'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/provider/ruby_block.rb:35:in `block in action_run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/provider.rb:176:in `converge_by'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/provider/ruby_block.rb:34:in `action_run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/provider.rb:145:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource.rb:622:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/runner.rb:69:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:114:in `call'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/runner.rb:96:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/client.rb:670:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `catch'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/client.rb:704:in `converge_and_save'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/client.rb:284:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/application.rb:252:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/application.rb:235:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/application/client.rb:427:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/application.rb:59:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/bin/chef-client:26:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:22:in `load'
/opt/opscode/embedded/bin/chef-client:22:in `<main>'

>>>> Caused by NoMethodError: undefined method `[]' for nil:NilClass
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:97:in `create_superuser_in_erchef'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:50:in `block in bootstrap'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:55:in `block in with_service_connection'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:44:in `with_connection'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:52:in `with_service_connection'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:49:in `bootstrap'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb:35:in `block (2 levels) in from_file'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/provider/ruby_block.rb:35:in `call'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/provider/ruby_block.rb:35:in `block in action_run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/provider.rb:176:in `converge_by'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/provider/ruby_block.rb:34:in `action_run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/provider.rb:145:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource.rb:622:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/runner.rb:69:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:114:in `call'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/runner.rb:96:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/client.rb:670:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `catch'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/client.rb:704:in `converge_and_save'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/client.rb:284:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/application.rb:252:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/application.rb:235:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/application/client.rb:427:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/lib/chef/application.rb:59:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.17.44/bin/chef-client:26:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:22:in `load'
/opt/opscode/embedded/bin/chef-client:22:in `<main>'

//--- snip ---
```

**Comment by trickyearlobe** [comment]
Hi @bklnnet , though Debian isn't listed in Chef server supported platforms at https://docs.chef.io/platforms.html I just tried installing `chef-server-core_12.15.6-1_amd64.deb` on Jessie and it seems to work fine.

Is it a vanilla install of Debian?
Do you have a bit more info about versions, contents of `/etc/opscode/chef-server.rb` etc.

**Comment by bklnnet** [comment]
Hey Richard, it's Mark Naumowicz. No worries despite these errors it seemed to install fine. Yes it was a vanila
I was running:
[root@gcp-naumowicz-net-vm: ~]# chef -v
Chef Development Kit Version: 0.16.28
chef-client version: 12.12.15
delivery version: master (921828facad8a8bbbd767368bfc72f19bd30e7bd)
berks version: 4.3.5
kitchen version: 1.10.2

"chef verify" came out with no issues, I guess we can close this for now. The install script spotted these errors and suggested that I report it, so I did. I guess the call to these undefined methods started it. I figure you guys might wanted to know...

Cheers...

**Comment by trickyearlobe** [comment]
Yeah, I saw the profile pic... good to hear from you !!

The version stuff you pasted is all for the client side tools. If you need us to investigate further we'd need to get the server version and a bit more info about the VM.

If a simple version upgrade doesn't make this go away, then the easiest way to get the version on the Debian command line is probably `dpkg --list | grep -i chef`
