### ISSUE TITLE
Failure upgrading RabbitMQ from Migration 1.30 to 1.31

### ISSUE THREAD

**Issue by StuporHero** [chef/chef-server#1220]
I'm running chef-server-ctl upgrade, and it's failing when partybus tries to change the password of the chef user on the RabbitMQ instance during the migration from 1.30 to 1.31. Below is the log.

```
ok: down: bookshelf: 1606s, normally up
ok: down: nginx: 1605s, normally up
ok: down: oc_bifrost: 1605s, normally up
ok: down: oc_id: 1603s, normally up
ok: down: opscode-chef-mover: 1750s, normally up
ok: down: opscode-erchef: 1602s, normally up
ok: down: opscode-expander: 1599s, normally up
ok: down: opscode-reporting: 3164s, normally up
ok: down: opscode-solr4: 1599s, normally up
ok: down: postgresql: 0s, normally up
timeout: run: rabbitmq: (pid 22670) 765s, want down
ok: down: redis_lb: 1s, normally up
ok: run: postgresql: (pid 28855) 0s
[private-chef-upgrade] - Latest Migration Available: 1.32
[private-chef-upgrade] - Migrations to Run: [#<Partybus::MigrationFile:0x0000000156e018 @path="/opt/opscode/embedded/upgrades/001/031_migrate_rabbitmq_password.rb", @major=1, @minor=31>, #<Partybus::MigrationFile:0x0000000156cc40 @path="/opt/opscode/embedded/upgrades/001/032_oc_id_logdir_perms.rb", @major=1, @minor=32>]
[private-chef-upgrade] - Current Migration Version: 1.30
[private-chef-upgrade] - Starting Migration 1.31
[private-chef-upgrade] -        Starting Services ["rabbitmq"]
down: rabbitmq: 113s, normally up; run: log: (pid 570) 17401s
ok: run: rabbitmq: (pid 29386) 0s
run: rabbitmq: (pid 29386) 66s; run: log: (pid 570) 17525s
[private-chef-upgrade] - Sleeping for 15 seconds while services comes online...
[private-chef-upgrade] -        Running Command: /opt/opscode/embedded/bin/rabbitmqctl change_password chef aafc8632588d5dede202bd04e1d07845051182c927e324e41ff41a234d7b8961a0ed62a5c84c992430f3ef10f9e439540c94 with options {}
Changing password for user "chef" ...
Error: {noproc,{gen_server2,call,
                            [worker_pool,{next_free,<10245.172.0>},infinity]}}
bundler: failed to load command: ./bin/partybus (./bin/partybus)
RuntimeError: Partybus failed to execute command '/opt/opscode/embedded/bin/rabbitmqctl change_password chef aafc8632588d5dede202bd04e1d07845051182c927e324e41ff41a234d7b8961a0ed62a5c84c992430f3ef10f9e439540c94' exitstatus: 70
  /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in 'instance_eval'
  /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v1.rb:97:in 'run_command'
  (eval):14:in 'block (2 levels) in run'
  (eval):12:in 'each'
  (eval):12:in 'block in run'
  /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v1.rb:14:in 'instance_eval'
  /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v1.rb:14:in 'initialize'
  /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:25:in 'new'
  /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:25:in 'define_upgrade'
  (eval):1:in 'run'
  /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in 'instance_eval'
  /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in 'run'
  /opt/opscode/embedded/service/partybus/lib/partybus/migrations.rb:41:in 'run_migration'
  /opt/opscode/embedded/service/partybus/bin/partybus:62:in 'block in do_upgrade'
  /opt/opscode/embedded/service/partybus/bin/partybus:58:in 'each'
  /opt/opscode/embedded/service/partybus/bin/partybus:58:in 'do_upgrade'
  /opt/opscode/embedded/service/partybus/bin/partybus:79:in 'block in <top (required)>'
  /opt/opscode/embedded/service/partybus/bin/partybus:70:in 'open'
  /opt/opscode/embedded/service/partybus/bin/partybus:70:in '<top (required)>'
```
Any ideas for a workaround?

**Comment by stevendanna** [comment]
It may be that `rabbitmq` is not coming up quickly enough.  This is a small migration to upgrade the hashing strategy used to store that password in rabbitmq.

One concerning aspect of the output you've provided is that this sequence of log messages:

```
down: rabbitmq: 113s, normally up; run: log: (pid 570) 17401s
ok: run: rabbitmq: (pid 29386) 0s
run: rabbitmq: (pid 29386) 66s; run: log: (pid 570) 17525s
[private-chef-upgrade] - Sleeping for 15 seconds while services comes online...
```

Implies (1) that rabbitmq has been up for 66 seconds before we sleep for another 15 seconds.  Under normal circumstances rabbitmq should have been fully started in that time.

Is this machine under a particularly high load at the moment?

Additionally, you may check to ensure there aren't somehow multiple rabbitmq processes running:

```
ps auxww | grep '[r]abbitmq' | grep -v runsv | grep -v svlogd
```

And that there aren't any obvious errors in `/var/log/opscode/rabbitmq/current`

If there aren't any obvious errors and the machine otherwise looks healthy, the best path forward is the following:

1) Modify `/var/opt/opscode/upgrades/migration-level` to have the following content:

```
{"major":1,"minor":31}
```

2) Run: `chef-server-ctl upgrade`
3) Run: `chef-server-ctl start`
4) Rotate your rabbitmq password.  This will have the same effect as the migration would have:

    ```
    chef-server-ctl rotate-credentials rabbitmq
    ```

If this is a multi-node installation (HA or Tier topologies), you'll need to run the rotate-credentials command on all nodes.

**Comment by StuporHero** [comment]
I didn't find any errors in the log during the upgrade, and there appeared to only be one instance running, so I used your work around. Thanks!!
