### ISSUE TITLE
'chef-server-ctl upgrade' fails when sudo is not installed

### ISSUE THREAD

**Issue by alexpop** [chef/chef-server#136]
Upgrading Enterprise Chef 11 to Chef server 12.0.6 as root fails if 'sudo' is not installed on the server. Some companies use pbrun instead of sudo for privilege delegation.

'chef-server-ctl upgrade' error output:

``` bash
Migrations completed successfully.

[private-chef-upgrade] -  Stopping Service opscode-chef-mover
ok: down: opscode-chef-mover: 1s, normally up
down: opscode-chef-mover: 3s, normally up; run: log: (pid 764) 1108904s
[private-chef-upgrade] - Sleeping for 10 seconds while service opscode-chef-mover stops...
down: opscode-chef-mover: 14s, normally up; run: log: (pid 764) 1108915s
[private-chef-upgrade] - Finished Migration 1.19 in 62.83 seconds
[private-chef-upgrade] - Current Migration Version: 1.13
[private-chef-upgrade] - Starting Migration 1.20
[private-chef-upgrade] -  Running Command: su -l opscode-pgsql -c "cd /opt/opscode/embedded/service/opscode-erchef/schema && cd baseline && sqitch deploy --to-target @1.0.4 --verify && cd .. && sqitch deploy --to-target @2.5.3 --verify;" with options {:cwd=>"/opt/opscode/embedded/service/opscode-erchef/schema", :env=>{"DB_USER"=>"opscode-pgsql"}}
Nothing to deploy (already at "@1.0.4"
Deploying changes through multiple_keys_migration @2.5.0 @2.5.1 @2.5.2 @2.5.3 to opscode_chef
  + multiple_keys ........................................ psql:deploy/multiple_keys.sql:21: NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "keys_pkey" for table "keys"
ok
  + keys_drop_trigger .................................... psql:deploy/keys_drop_trigger.sql:15: NOTICE:  trigger "delete_keys" for table "clients" does not exist, skipping
psql:deploy/keys_drop_trigger.sql:16: NOTICE:  trigger "delete_keys" for table "users" does not exist, skipping
ok
  + keys_update_trigger .................................. psql:deploy/keys_update_trigger.sql:33: NOTICE:  trigger "add_key" for table "clients" does not exist, skipping
psql:deploy/keys_update_trigger.sql:34: NOTICE:  trigger "update_key" for table "clients" does not exist, skipping
psql:deploy/keys_update_trigger.sql:36: NOTICE:  trigger "add_key" for table "users" does not exist, skipping
psql:deploy/keys_update_trigger.sql:37: NOTICE:  trigger "update_key" for table "users" does not exist, skipping
ok
  + multiple_keys_migration @2.5.0 @2.5.1 @2.5.2 @2.5.3 .. ok
[private-chef-upgrade] -  Running Command: sudo -u opscode-pgsql /opt/opscode/embedded/bin/psql opscode_chef -c 'select migrate_keys();' with options {}
sh: sudo: command not found
/opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in `instance_eval': Partybus failed to execute command 'sudo -u opscode-pgsql /opt/opscode/embedded/bin/psql opscode_chef -c 'select migrate_keys();'' exitstatus: 127 (RuntimeError)
  from /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v1.rb:97:in `run_command'
  from (eval):5:in `block in run'
  from /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v1.rb:14:in `instance_eval'
  from /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v1.rb:14:in `initialize'
  from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:25:in `new'
  from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:25:in `define_upgrade'
  from (eval):1:in `run'
  from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in `instance_eval'
  from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in `run'
  from /opt/opscode/embedded/service/partybus/lib/partybus/migrations.rb:41:in `run_migration'
  from ./bin/partybus:62:in `block in do_upgrade'
  from ./bin/partybus:58:in `each'
  from ./bin/partybus:58:in `do_upgrade'
  from ./bin/partybus:79:in `block in <main>'
  from ./bin/partybus:70:in `open'
  from ./bin/partybus:70:in `<main>'


```

**Comment by stevendanna** [comment]
We appear to use sudo in the following places:

```
files/private-chef-cookbooks/private-chef/templates/default/opscode-chef-mover.erb
20:    exec sudo -u $RUNNER_USER -i $0 $@

files/private-chef-cookbooks/private-chef/templates/default/org_app.erb
13:    exec sudo -u $RUNNER_USER -i $0 $@

files/private-chef-upgrades/001/012_erchef_to_sqitch.rb
7:    sqitch = "sudo -u #{Partybus.config.database_unix_user} PATH=/opt/opscode/embedded/bin:/sbin:/usr/sbin:/bin:/usr/bin /opt/opscode/embedded/bin/sqitch"

files/private-chef-upgrades/001/013_bcrypt_users.rb
7:    sqitch = "sudo -u #{Partybus.config.database_unix_user} PATH=/opt/opscode/embedded/bin:/sbin:/usr/sbin:/bin:/usr/bin /opt/opscode/embedded/bin/sqitch"

files/private-chef-upgrades/001/020_multi_key_schema_migration.rb
5:    run_command("sudo -u #{Partybus.config.database_unix_user} /opt/opscode/embedded/bin/psql opscode_chef -c 'select migrate_keys();'")
```

**Comment by erowid5031** [comment]
Hi - is there an ETA on this feature (pmrun/pbrun alternative to sudo) as we're facing the same (or very similar) situation, both from a infrastructure server as well as chef-client standpoints.  While we could temporarily enable sudo for bootstrapping & build in pre-PROD, from a PRODUCTION CI/CD workflow standpoint, sudo is not a viable option for us (pmrun is the only privilege escalation mechanism available).  Please advise.  Thanks, Steve

**Comment by stevendanna** [comment]
It looks like our only requirement on the sudo executable are down to:

```

**Comment by erowid5031** [comment]
Thanks for the update, Steve.   Forgive my ignorance, but does this apply only to chef-server (the context of Alex’s original query), or will it include chef-client sudo dependencies.

Cheers,
-Steve

[cid:image002.jpg@01D0F05D.7A7D9660]

[cid:image006.jpg@01D0F05D.7A7D9660]

**Comment by stevendanna** [comment]
@erowid5031 I only looked at chef-server's dependency on the sudo executable.

**Comment by stevendanna** [comment]
It appears that to remove those last two uses of sudo requires some additions to the partybus run_sqitch helper, still looks doable, just wanted to give an update of why I didn't get that PR out last week.

**Comment by erowid5031** [comment]
No problem – thanks much for the update, Steve.

Regards,
-Steve

**Comment by PrajaktaPurohit** [comment]
Closing this for inactivity. Please reopen if relevant.
