### ISSUE TITLE
Unsatisfiable run list item with new major cookbook version

### ISSUE THREAD

**Issue by martinmosegaard** [chef/chef-server#1449]
I have bumped an application cookbook from 0.34.5 to 1.0.0. Both versions (plus older) are uploaded to our Chef server.

The cookbook view shows both versions and 1.0.0 as current, which is good.

But if I set the cookbook on the run list of a node, it gets version 0.34.5. Also, if I consume it in a role cookbook that is set on the run list of a node, I get the error "Unsatisfiable run list item".

In the output below, some node and cookbook names have been changed.

## Expected Behavior

When the new cookbook version exists on the Chef server (and our Supermarket FWIW), I should be able to run `chef-client` with the specific, new version.

## Current Behavior

Instead, I get an error:
```
> knife cookbook show mycookbook
mycookbook   1.0.0  0.34.5  0.34.4  0.34.3  0.34.2  0.34.0  0.33.0  0.32.0  0.31.0  0.30.0  0.29.6  0.29.5  0.29.4  0.29.1  0.29.0  0.28.0  0.27.0  0.26.0  0.25.0  0.24.0  0.23.0  0.22.0  0.21.0  0.20.0  0.19.0  0.18.0  0.17.0  0.16.0  0.15.0  0.14.0  0.13.0  0.12.0

> knife winrm name:mynode <connection options> "chef-client -o 'recipe[mycookbook::default@1.0.0]'"
10.20.158.104 [2018-01-24T08:30:10+01:00] INFO: *** Chef 12.21.10 ***
10.20.158.104 [2018-01-24T08:30:10+01:00] INFO: Platform: x64-mingw32
10.20.158.104 [2018-01-24T08:30:10+01:00] INFO: Chef-client pid: 2796
10.20.158.104 [2018-01-24T08:30:10+01:00] INFO: The plugin path C:\chef\ohai\plugins does not exist. Skipping...
10.20.158.104 [2018-01-24T08:30:13+01:00] WARN: Run List override has been provided.
10.20.158.104 [2018-01-24T08:30:13+01:00] WARN: Original Run List: [<not shown here>]
10.20.158.104 [2018-01-24T08:30:13+01:00] WARN: Overridden Run List: [recipe[mycookbook::default@1.0.0]]
10.20.158.104 [2018-01-24T08:30:13+01:00] INFO: Run List is [recipe[mycookbook::default@1.0.0]]
10.20.158.104 [2018-01-24T08:30:13+01:00] INFO: Run List expands to [mycookbook::default@1.0.0]
10.20.158.104 [2018-01-24T08:30:13+01:00] INFO: Starting Chef Run for mynode
10.20.158.104 [2018-01-24T08:30:13+01:00] INFO: Running start handlers
10.20.158.104 [2018-01-24T08:30:13+01:00] INFO: Start handlers complete.
10.20.158.104 [2018-01-24T08:30:13+01:00] INFO: HTTP Request Returned 404 Not Found:
10.20.158.104 [2018-01-24T08:30:14+01:00] INFO: HTTP Request Returned 412 Precondition Failed: {"message"=>"Run list contains invalid items: no versions match the constraints on cookbook (mycookbook = 1.0.0).", "non_existent_cookbooks"=>[], "cookbooks_with_no_versions"=>["(mycookbook = 1.0.0)"]}
10.20.158.104
10.20.158.104
10.20.158.104 ================================================================================
10.20.158.104 Error Resolving Cookbooks for Run List:
10.20.158.104 ================================================================================
10.20.158.104
10.20.158.104 Missing Cookbooks:
10.20.158.104 ------------------
10.20.158.104 The following cookbooks exist on the server, but there is no version that meets
10.20.158.104 the version constraints in this environment:
10.20.158.104 * (mycookbook = 1.0.0)
10.20.158.104
10.20.158.104
10.20.158.104 Expanded Run List:
10.20.158.104 ------------------
10.20.158.104 * mycookbook::default@1.0.0
10.20.158.104
10.20.158.104 System Info:
10.20.158.104 ------------
10.20.158.104 chef_version=12.21.10
10.20.158.104 platform=windows
10.20.158.104 platform_version=6.3.9600
10.20.158.104 ruby=ruby 2.3.4p301 (2017-03-30 revision 58214) [x64-mingw32]
10.20.158.104 program_name=C:/opscode/chef/bin/chef-client
10.20.158.104 executable=C:/opscode/chef/bin/chef-client
10.20.158.104
10.20.158.104 [2018-01-24T08:30:14+01:00] ERROR: Running exception handlers
10.20.158.104 [2018-01-24T08:30:14+01:00] ERROR: Exception handlers complete
10.20.158.104 [2018-01-24T08:30:14+01:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
10.20.158.104 [2018-01-24T08:30:14+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
10.20.158.104 [2018-01-24T08:30:14+01:00] FATAL: Net::HTTPServerException: 412 "Precondition Failed"
```

Here is the stacktrace:

```
λ type chef-stacktrace.out
Generated at 2018-01-24 08:37:46 +0100
Net::HTTPServerException: 412 "Precondition Failed"
C:/opscode/chef/embedded/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/http.rb:150:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/http.rb:131:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:204:in `sync_cookbooks'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:83:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/2.3.0/forwardable.rb:204:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/client.rb:513:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/application.rb:277:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/application.rb:253:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/application.rb:236:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.10-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:68:in `load'
C:/opscode/chef/bin/chef-client:68:in `<main>'
```

## Steps to Reproduce (for bugs)

1. Created many versions of the cookbook, as long as the versions were below 1.0 upgrades worked fine
1. Uploaded version 1.0.0 of the cookbook 
1. Tried to use version 1.0.0 in a chef-client run

## Your Environment

* Chef Server Version: 
```
$ head -n1 /opt/opscode/version-manifest.txt
chef-server 12.16.14
```
* Total/free RAM and disk space:
* Operating System and Version: Windows Server 2012 R2
* If upgrading, previous Chef Server version:
* Running in a container? No

Not sure if related, but this reminds me of this bug:
https://github.com/chef/chef-server/issues/1435

**Comment by martinmosegaard** [comment]
I have found the cause. I had a version constraint in the environment used by the node. This environment file contained lines like this:

```
...
cookbook_versions({
  ...
  'mycookbook' => '= 0.34.5',
  ...
})
...
```

Once I removed that, the `chef-client` run was able to use `mycookbook@1.0.0`. Afterwards, I discovered this line in the output:

```
The following cookbooks exist on the server, but there is no version that meets the version constraints in this environment
```

Perhaps the error message could be more elaborate and mention the environment name and cookbook versions? I am closing this issue, but let me know if you want an issue to track improvement of the error message.
