### ISSUE TITLE
chef-sync crashes after 'yum update' on RHEL 6.6

### ISSUE THREAD

**Issue by vinyar** [chef/chef-server#158]
Upgraded from 2.6.32-431.29.2.el6.x86_64
Resulting kernel - Linux DE1CTIXCHEF01 2.6.32-504.3.3.el6.x86_64 
#1 SMP Fri Dec 12 16:05:43 EST 2014 x86_64 x86_64 x86_64 GNU/Linux

Around 14:00 is when the update took place. As can be seen below, the sync was going strong until the reboot took place. After the reboot it didn't come back and had to be restarted manually.

``` ruby
2015-04-28_21:00:50.66072 I, [2015-04-28T14:00:50.660667 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:01:00 -0700
2015-04-28_21:01:01.21379 I, [2015-04-28T14:01:01.213740 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:01:11 -0700
2015-04-28_21:01:11.78500 I, [2015-04-28T14:01:11.784951 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:01:21 -0700
2015-04-28_21:01:22.34760 I, [2015-04-28T14:01:22.347549 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:01:32 -0700
2015-04-28_21:01:32.99482 I, [2015-04-28T14:01:32.994766 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:01:42 -0700
2015-04-28_21:01:43.57607 I, [2015-04-28T14:01:43.576022 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:01:53 -0700
2015-04-28_21:01:54.14721 I, [2015-04-28T14:01:54.147160 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:02:04 -0700
2015-04-28_21:02:04.72642 I, [2015-04-28T14:02:04.726363 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:02:14 -0700
2015-04-28_21:02:15.27621 I, [2015-04-28T14:02:15.276145 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:02:25 -0700
2015-04-28_21:02:25.82331 I, [2015-04-28T14:02:25.823264 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:02:35 -0700
2015-04-28_21:02:36.40604 I, [2015-04-28T14:02:36.405985 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:02:46 -0700
2015-04-28_21:02:46.97263 I, [2015-04-28T14:02:46.972577 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:02:56 -0700
2015-04-28_21:02:57.53482 I, [2015-04-28T14:02:57.534770 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:03:07 -0700
2015-04-28_21:03:08.10152 I, [2015-04-28T14:03:08.101460 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:03:18 -0700
2015-04-28_21:03:18.66963 I, [2015-04-28T14:03:18.669583 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:03:28 -0700
2015-04-28_21:03:29.24082 I, [2015-04-28T14:03:29.240759 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:03:39 -0700
2015-04-28_21:03:39.82112 I, [2015-04-28T14:03:39.821054 #7032]  INFO -- : ctl: sleeping until 2015-04-28 14:03:49 -0700
2015-04-28_21:03:42.95593 I, [2015-04-28T14:03:42.955774 #7032]  INFO -- : Sending fast shutdown to workers
2015-04-28_21:03:42.95594 I, [2015-04-28T14:03:42.955861 #7032]  INFO -- : Sending TERM to 8133
2015-04-28_21:03:42.95594 I, [2015-04-28T14:03:42.955890 #7032]  INFO -- : Waiting for workers to stop
2015-04-28_21:03:43.08930 I, [2015-04-28T14:03:43.088138 #7032]  INFO -- : Shutdown complete.
2015-04-28_21:03:43.79648 I, [2015-04-28T14:03:43.796407 #11156]  INFO -- : ec_sync_client: manager starting
2015-04-28_21:03:43.79666 I, [2015-04-28T14:03:43.796632 #11156]  INFO -- : ec_sync_client: listening on /var/opt/chef-sync/ec_sync_client/ec_sync.sock
2015-04-28_21:03:43.79671 I, [2015-04-28T14:03:43.796690 #11156]  INFO -- : ec_sync_client: starting worker for ctl
2015-04-28_21:03:45.66987 I, [2015-04-28T14:03:45.669819 #11156]  INFO -- : ctl: sleeping until 2015-04-28 14:03:47 -0700
2015-04-28_21:03:48.24556 I, [2015-04-28T14:03:48.245502 #11156]  INFO -- : ctl: sleeping until 2015-04-28 14:03:52 -0700
2015-04-28_21:03:52.24953 FATAL:  terminating connection due to administrator command
2015-04-28_21:03:52.24954 /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:161:in `async_exec': PG::ConnectionBad: PQconsumeInput()  (Sequel::DatabaseDisconnectError)
2015-04-28_21:03:52.24955   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:161:in `block in execute_query'
2015-04-28_21:03:52.24955   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/database/logging.rb:33:in `log_yield'
2015-04-28_21:03:52.24955   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:161:in `execute_query'
2015-04-28_21:03:52.24955   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:148:in `block in execute'
2015-04-28_21:03:52.24956   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:124:in `check_disconnect_errors'
2015-04-28_21:03:52.24957   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:148:in `execute'
2015-04-28_21:03:52.24957   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:492:in `_execute'
2015-04-28_21:03:52.24957   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:316:in `block (2 levels) in execute'
2015-04-28_21:03:52.24958   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:513:in `check_database_errors'
2015-04-28_21:03:52.24958   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:316:in `block in execute'
2015-04-28_21:03:52.24958   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'
2015-04-28_21:03:52.24958   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
2015-04-28_21:03:52.24958   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/database/connecting.rb:250:in `synchronize'
2015-04-28_21:03:52.24959   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:316:in `execute'
2015-04-28_21:03:52.24959   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:906:in `execute'
2015-04-28_21:03:52.24959   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:636:in `fetch_rows'
2015-04-28_21:03:52.24959   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:139:in `each'
2015-04-28_21:03:52.24960   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:639:in `single_record'
2015-04-28_21:03:52.24960   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:191:in `first'
2015-04-28_21:03:52.24960   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/org.rb:28:in `last_seq'
2015-04-28_21:03:52.24960   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/orgsyncer.rb:63:in `block in start'
2015-04-28_21:03:52.24960   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/orgsyncer.rb:62:in `loop'
2015-04-28_21:03:52.24961   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/orgsyncer.rb:62:in `start'
2015-04-28_21:03:52.24961   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:114:in `block in start_worker'
2015-04-28_21:03:52.24961   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:110:in `fork'
2015-04-28_21:03:52.24962   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:110:in `start_worker'
2015-04-28_21:03:52.24962   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:69:in `block in start'
2015-04-28_21:03:52.24962   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:66:in `each'
2015-04-28_21:03:52.24962   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:66:in `start'
2015-04-28_21:03:52.24962   from /opt/chef-sync/embedded/service/ec_sync_client/bin/ec_sync_client:56:in `run'
2015-04-28_21:03:52.24962   from /opt/chef-sync/embedded/service/ec_sync_client/bin/ec_sync_client:62:in `<main>'
2015-04-28_21:03:52.25496 I, [2015-04-28T14:03:52.254867 #11156]  INFO -- : Worker for ctl died unexpectedly!
2015-04-28_21:08:07.91056 I, [2015-04-28T14:08:07.910450 #11156]  INFO -- : Sending fast shutdown to workers
2015-04-28_21:08:07.91157 I, [2015-04-28T14:08:07.910572 #11156]  INFO -- : Sending TERM to 11169
2015-04-28_21:08:07.91157 I, [2015-04-28T14:08:07.910619 #11156]  INFO -- : Waiting for workers to stop
2015-04-28_21:08:07.91158 I, [2015-04-28T14:08:07.910693 #11156]  INFO -- : Shutdown complete.
2015-04-28_21:08:08.59914 I, [2015-04-28T14:08:08.599069 #13664]  INFO -- : ec_sync_client: manager starting
2015-04-28_21:08:08.59929 I, [2015-04-28T14:08:08.599267 #13664]  INFO -- : ec_sync_client: listening on /var/opt/chef-sync/ec_sync_client/ec_sync.sock
2015-04-28_21:08:08.59935 I, [2015-04-28T14:08:08.599324 #13664]  INFO -- : ec_sync_client: starting worker for ctl
2015-04-28_21:08:10.55364 I, [2015-04-28T14:08:10.553537 #13664]  INFO -- : ctl: sleeping until 2015-04-28 14:08:12 -0700
2015-04-28_21:08:13.10836 I, [2015-04-28T14:08:13.108310 #13664]  INFO -- : ctl: sleeping until 2015-04-28 14:08:17 -0700
2015-04-28_21:08:17.10927 FATAL:  terminating connection due to administrator command
2015-04-28_21:08:17.10929 /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:161:in `async_exec': PG::ConnectionBad: PQconsumeInput()  (Sequel::DatabaseDisconnectError)
2015-04-28_21:08:17.10929   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:161:in `block in execute_query'
2015-04-28_21:08:17.10929   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/database/logging.rb:33:in `log_yield'
2015-04-28_21:08:17.10929   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:161:in `execute_query'
2015-04-28_21:08:17.10930   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:148:in `block in execute'
2015-04-28_21:08:17.10930   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:124:in `check_disconnect_errors'
2015-04-28_21:08:17.10930   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:148:in `execute'
2015-04-28_21:08:17.10930   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:492:in `_execute'
2015-04-28_21:08:17.10931   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:316:in `block (2 levels) in execute'
2015-04-28_21:08:17.10931   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:513:in `check_database_errors'
2015-04-28_21:08:17.10931   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:316:in `block in execute'
2015-04-28_21:08:17.10931   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'
2015-04-28_21:08:17.10932   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
2015-04-28_21:08:17.10932   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/database/connecting.rb:250:in `synchronize'
2015-04-28_21:08:17.10932   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:316:in `execute'
2015-04-28_21:08:17.10932   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:906:in `execute'
2015-04-28_21:08:17.10933   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:636:in `fetch_rows'
2015-04-28_21:08:17.10933   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:139:in `each'
2015-04-28_21:08:17.10933   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:639:in `single_record'
2015-04-28_21:08:17.10933   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:191:in `first'
2015-04-28_21:08:17.10933   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/org.rb:28:in `last_seq'
2015-04-28_21:08:17.10934   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/orgsyncer.rb:63:in `block in start'
2015-04-28_21:08:17.10934   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/orgsyncer.rb:62:in `loop'
2015-04-28_21:08:17.10935   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/orgsyncer.rb:62:in `start'
2015-04-28_21:08:17.10935   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:114:in `block in start_worker'
2015-04-28_21:08:17.10935   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:110:in `fork'
2015-04-28_21:08:17.10935   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:110:in `start_worker'
2015-04-28_21:08:17.10936   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:69:in `block in start'
2015-04-28_21:08:17.10936   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:66:in `each'
2015-04-28_21:08:17.10936   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:66:in `start'
2015-04-28_21:08:17.10936   from /opt/chef-sync/embedded/service/ec_sync_client/bin/ec_sync_client:56:in `run'
2015-04-28_21:08:17.10936   from /opt/chef-sync/embedded/service/ec_sync_client/bin/ec_sync_client:62:in `<main>'
2015-04-28_21:08:17.11488 I, [2015-04-28T14:08:17.114800 #13664]  INFO -- : Worker for ctl died unexpectedly!
2015-04-29_19:06:48.96337 I, [2015-04-29T12:06:48.963276 #13664]  INFO -- : ec_sync_client: starting new command connection handler
2015-04-29_19:06:48.97697 I, [2015-04-29T12:06:48.976894 #13664]  INFO -- : ec_sync_client: closing command connection handler
```

**Comment by stevendanna** [comment]
Thank you for trying chef-sync and taking the time to file this
ticket. I am sorry you haven't received more feedback on this
issue before now.

Chef sync is no longer an actively developed product as it saw
very little adoption in our user base.  No further development is
planned for Chef sync.

I am closing this ticket. However, if you already have a Chef
sync deployment and still require further assistance, please
contact support at support@chef.io.
