### ISSUE TITLE
Initial chef-server-ctl reconfigure fails, 12.18.14-1, Ubuntu 16

### ISSUE THREAD

**Issue by jrobison-sb** [chef/chef-server#1596]
### Chef Server Version
12.18.14-1

### Platform Details
- Ubuntu 16.04
- AWS, t2.large
- 8G RAM total, 4G free
- External postgres (on RDS) and external bookshelf (on S3)

### Configuration
Standalone, but with external postgres and bookshelf as mentioned above.

```
cat /etc/opscode/chef-server.rb
postgresql['db_superuser'] = 'chef'
postgresql['db_superuser_password'] = 'obfuscated'
postgresql['external'] = true
postgresql['vip'] = 'chef-server-rds-hostname.us-east-1.rds.amazonaws.com'

bookshelf['vip'] = 'bookshelf-bucket-name.s3.amazonaws.com'
bookshelf['external_url'] = 'https://bookshelf-bucket-name.s3.amazonaws.com'
bookshelf['access_key_id'] = 'obfuscated'
bookshelf['secret_access_key'] = 'obfuscated'
opscode_erchef['s3_bucket'] = 'bookshelf-bucket-name'
```

### Scenario:
Install chef-server.

### Steps to Reproduce:
Here is my user_data script (it's a Terraform template, hence the `${foo}` variables:

```
#!/bin/bash -x

# apt-get upgrade
export DEBIAN_FRONTEND=noninteractive
export DEBIAN_PRIORITY=critical
sudo -E apt-get -qy update
sudo -E apt-get -qy -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" upgrade
sudo -E apt-get -qy autoclean

# awscli
apt-get install -y python-pip
pip install awscli

# Install and set up the Chef server
wget -q -O /tmp/chef-server.deb https://packages.chef.io/files/stable/chef-server/12.18.14/ubuntu/16.04/chef-server-core_12.18.14-1_amd64.deb
dpkg -i /tmp/chef-server.deb

# Set up external postgres
echo postgresql\[\'db_superuser\'\] = \'${db_superuser}\' > /etc/opscode/chef-server.rb
echo postgresql\[\'db_superuser_password\'\] = \'${db_superuser_password}\' >> /etc/opscode/chef-server.rb
echo postgresql\[\'external\'\]	= true >> /etc/opscode/chef-server.rb
echo postgresql\[\'vip\'\] = \'${rds_endpoint}\' >> /etc/opscode/chef-server.rb
echo >> /etc/opscode/chef-server.rb

# Set up external cookbook storage on S3
echo bookshelf\[\'vip\'\] = \'${bookshelf_bucket_domain_name}\' >> /etc/opscode/chef-server.rb
echo bookshelf\[\'external_url\'\] = \'https://${bookshelf_bucket_domain_name}\' >> /etc/opscode/chef-server.rb
echo bookshelf\[\'access_key_id\'\] = \'${iam_user}\' >> /etc/opscode/chef-server.rb
echo bookshelf\[\'secret_access_key\'\] = \'${iam_secret}\' >> /etc/opscode/chef-server.rb
echo opscode_erchef\[\'s3_bucket\'\] = \'${bookshelf_bucket_name}\' >> /etc/opscode/chef-server.rb
echo >> /etc/opscode/chef-server.rb

chef-server-ctl reconfigure
```

### Expected Result:
exit 0, with chef-server being successfully reconfigured.

### Actual Result:

Giant pastebomb of the error:

```
[0m  * openssl_x509_certificate[/var/opt/opscode/nginx/ca/.crt] action create
    [0m
    ================================================================================[0m
    [31mError executing action `create` on resource 'openssl_x509_certificate[/var/opt/opscode/nginx/ca/.crt]'[0m
    ================================================================================[0m
    
[0m    TypeError[0m
    ---------[0m
    no implicit conversion of nil into String[0m
    
[0m    Cookbook Trace:[0m
    ---------------[0m
    /var/opt/opscode/local-mode-cache/cookbooks/openssl/resources/x509_certificate.rb:111:in `add_entry'
[0m    /var/opt/opscode/local-mode-cache/cookbooks/openssl/resources/x509_certificate.rb:111:in `subject'
[0m    /var/opt/opscode/local-mode-cache/cookbooks/openssl/resources/x509_certificate.rb:97:in `request'
[0m    /var/opt/opscode/local-mode-cache/cookbooks/openssl/resources/x509_certificate.rb:148:in `cert'
[0m    /var/opt/opscode/local-mode-cache/cookbooks/openssl/resources/x509_certificate.rb:57:in `block (3 levels) in class_from_file'
[0m    /var/opt/opscode/local-mode-cache/cookbooks/openssl/resources/x509_certificate.rb:51:in `block (2 levels) in class_from_file'
[0m    /var/opt/opscode/local-mode-cache/cookbooks/openssl/resources/x509_certificate.rb:50:in `block in class_from_file'[0m
    
[0m    Resource Declaration:[0m
    ---------------------[0m
    # In /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/nginx.rb
[0m    
[0m     77:    openssl_x509 ssl_crtfile do
[0m     78:      common_name server_name
[0m     79:      org node['private_chef']['nginx']['ssl_company_name']
[0m     80:      org_unit node['private_chef']['nginx']['ssl_organizational_unit_name']
[0m     81:      country node['private_chef']['nginx']['ssl_country_name']
[0m     82:      key_length node['private_chef']['nginx']['ssl_key_length']
[0m     83:      expire node['private_chef']['nginx']['ssl_duration']
[0m     84:      subject_alt_name [ "#{server_name_type}:#{server_name}" ]
[0m     85:      owner OmnibusHelper.new(node).ownership['owner']
[0m     86:      group OmnibusHelper.new(node).ownership['group']
[0m     87:      mode '0600'
[0m     88:    end
[0m     89: 
[0m    
[0m    Compiled Resource:[0m
    ------------------[0m
    # Declared in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/nginx.rb:77:in `from_file'
[0m    
[0m    openssl_x509_certificate("/var/opt/opscode/nginx/ca/.crt") do
[0m      action [:create]
[0m      default_guard_interpreter :default
[0m      declared_type :openssl_x509
[0m      cookbook_name "private-chef"
[0m      recipe_name "nginx"
[0m      common_name nil
[0m      org "YouCorp"
[0m      org_unit "Operations"
[0m      country "US"
[0m      key_length 2048
[0m      expire 3650
[0m      subject_alt_name ["DNS:"]
[0m      owner "opscode"
[0m      group "opscode"
[0m      mode "0600"
[0m      path "/var/opt/opscode/nginx/ca/.crt"
[0m    end
[0m    
[0m    System Info:[0m
    ------------[0m
    chef_version=14.3.37
[0m    platform=ubuntu
[0m    platform_version=16.04
[0m    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
[0m    program_name=/opt/opscode/embedded/bin/chef-client
[0m    executable=/opt/opscode/embedded/bin/chef-client[0m
    
[0mRecipe: private-chef::oc_bifrost[0m
  * runit_service[oc_bifrost] action restart (up to date)
  * execute[restart_oc_bifrost_log_service] action run
    [32m- execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/oc_bifrost/log[0m
[0mRecipe: private-chef::oc_id[0m
  * runit_service[oc_id] action restart (up to date)
  * execute[restart_oc_id_log_service] action run
    [32m- execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/oc_id/log[0m
[0mRecipe: private-chef::nginx[0m
  * runit_service[nginx] action restart
    [0m
    ================================================================================[0m
    [31mError executing action `restart` on resource 'runit_service[nginx]'[0m
    ================================================================================[0m
    
[0m    Mixlib::ShellOut::ShellCommandFailed[0m
    ------------------------------------[0m
    Expected process to exit with [0], but received '1'
[0m    ---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
[0m    STDOUT: fail: /opt/opscode/service/nginx: unable to change to service directory: file does not exist
[0m    STDERR: 
[0m    ---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
[0m    Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx returned 1[0m
    
[0m    Cookbook Trace:[0m
    ---------------[0m
    /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:174:in `tap'
[0m    /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:174:in `safe_sv_shellout!'
[0m    /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:202:in `restart_service'
[0m    /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/provider_runit_service.rb:330:in `block in <class:RunitService>'[0m
    
[0m    Resource Declaration:[0m
    ---------------------[0m
    # In /var/opt/opscode/local-mode-cache/cookbooks/enterprise/definitions/component_runit_service.rb
[0m    
[0m     37:   runit_service component do
[0m     38:     action :enable
[0m     39:     retries 20
[0m     40:     control params[:control] if params[:control]
[0m     41:     options(
[0m     42:       log_directory: log_directory
[0m     43:     )
[0m     44:     params[:runit_attributes].each do |attr_name, attr_value|
[0m     45:       send(attr_name.to_sym, attr_value)
[0m     46:     end
[0m     47:   end
[0m     48: 
[0m    
[0m    Compiled Resource:[0m
    ------------------[0m
    # Declared in /var/opt/opscode/local-mode-cache/cookbooks/enterprise/definitions/component_runit_service.rb:37:in `block in from_file'
[0m    
[0m    runit_service("nginx") do
[0m      params {:package=>"private_chef", :log_directory=>nil, :svlogd_size=>nil, :svlogd_num=>nil, :ha=>nil, :control=>nil, :runit_attributes=>{}, :action=>:enable, :name=>"nginx"}
[0m      provider Chef::Provider::RunitService
[0m      action [:enable]
[0m      default_guard_interpreter :default
[0m      service_name "nginx"
[0m      enabled false
[0m      running false
[0m      masked nil
[0m      options {:log_directory=>"/var/log/opscode/nginx"}
[0m      pattern "nginx"
[0m      status_command "/opt/opscode/embedded/bin/sv status /opt/opscode/service"
[0m      supports {:restart=>true, :reload=>true, :status=>true}
[0m      sv_bin "/opt/opscode/embedded/bin/sv"
[0m      sv_dir "/opt/opscode/sv"
[0m      service_dir "/opt/opscode/service"
[0m      lsb_init_dir "/opt/opscode/init"
[0m      log true
[0m      restart_on_update true
[0m      run_template_name "nginx"
[0m      log_template_name "nginx"
[0m      check_script_template_name "nginx"
[0m      finish_script_template_name "nginx"
[0m      sv_templates true
[0m      log_dir "/var/log/nginx"
[0m      service_mirror # Declared in 
[0m    
[0m    service("nginx") do
[0m      provider Chef::Provider::Service::Simple
[0m      action [:nothing]
[0m      default_guard_interpreter :default
[0m      service_name "nginx"
[0m      enabled nil
[0m      running nil
[0m      masked nil
[0m      pattern "nginx"
[0m      start_command "/opt/opscode/embedded/bin/sv start /opt/opscode/service/nginx"
[0m      stop_command "/opt/opscode/embedded/bin/sv stop /opt/opscode/service/nginx"
[0m      status_command "/opt/opscode/embedded/bin/sv status /opt/opscode/service/nginx"
[0m      restart_command "/opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx"
[0m      supports {:restart=>true, :reload=>true, :status=>true}
[0m    end
[0m    
[0m      declared_type :runit_service
[0m      cookbook_name "private-chef"
[0m      recipe_name "nginx"
[0m      retries 20
[0m    end
[0m    
[0m    System Info:[0m
    ------------[0m
    chef_version=14.3.37
[0m    platform=ubuntu
[0m    platform_version=16.04
[0m    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
[0m    program_name=/opt/opscode/embedded/bin/chef-client
[0m    executable=/opt/opscode/embedded/bin/chef-client[0m
    
[0mRecipe: private-chef::opscode-solr4[0m
  * runit_service[opscode-solr4] action restart (up to date)
  * execute[restart_opscode-solr4_log_service] action run
    [32m- execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/opscode-solr4/log[0m
[0mRecipe: private-chef::opscode-expander[0m
  * runit_service[opscode-expander] action restart (up to date)
  * execute[restart_opscode-expander_log_service] action run
    [32m- execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/opscode-expander/log[0m
[0mRecipe: private-chef::bookshelf[0m
  * runit_service[bookshelf] action restart (up to date)
  * execute[restart_bookshelf_log_service] action run
    [32m- execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/bookshelf/log[0m
[0mRecipe: private-chef::opscode-erchef[0m
  * runit_service[opscode-erchef] action restart (up to date)
  * execute[restart_opscode-erchef_log_service] action run
    [32m- execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/opscode-erchef/log[0m
[0mRecipe: <Dynamically Defined Resource>[0m
  * service[opscode-erchef] action restart
    [32m- restart service service[opscode-erchef][0m
[0mRecipe: private-chef::partybus[0m
  * execute[set initial migration level] action run
    [0m
    ================================================================================[0m
    [31mError executing action `run` on resource 'execute[set initial migration level]'[0m
    ================================================================================[0m
    
[0m    Mixlib::ShellOut::ShellCommandFailed[0m
    ------------------------------------[0m
    Expected process to exit with [0], but received '1'
[0m    ---- Begin output of cd /opt/opscode/embedded/service/partybus && ./bin/partybus init ----
[0m    STDOUT: 
[0m    STDERR: /opt/opscode/embedded/service/gem/ruby/2.5.0/gems/sequel-3.34.1/lib/sequel/database/schema_generator.rb:19: warning: constant ::Fixnum is deprecated
[0m    /opt/opscode/embedded/service/gem/ruby/2.5.0/gems/sequel-3.34.1/lib/sequel/database/schema_generator.rb:19: warning: constant ::Bignum is deprecated
[0m    ./bin/partybus:11:in `require': cannot load such file -- /opt/opscode/embedded/service/partybus/config.rb (LoadError)
[0m    	from ./bin/partybus:11:in `<main>'
[0m    ---- End output of cd /opt/opscode/embedded/service/partybus && ./bin/partybus init ----
[0m    Ran cd /opt/opscode/embedded/service/partybus && ./bin/partybus init returned 1[0m
    
[0m    Resource Declaration:[0m
    ---------------------[0m
    # In /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/partybus.rb
[0m    
[0m     59: execute "set initial migration level" do
[0m     60:   action :nothing
[0m     61:   command "cd /opt/opscode/embedded/service/partybus && ./bin/partybus init"
[0m     62:   subscribes :run, "file[#{OmnibusHelper.bootstrap_sentinel_file}]", :delayed
[0m     63: end
[0m     64: 
[0m    
[0m    Compiled Resource:[0m
    ------------------[0m
    # Declared in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/partybus.rb:59:in `from_file'
[0m    
[0m    execute("set initial migration level") do
[0m      action [:nothing]
[0m      default_guard_interpreter :execute
[0m      command "cd /opt/opscode/embedded/service/partybus && ./bin/partybus init"
[0m      backup 5
[0m      declared_type :execute
[0m      cookbook_name "private-chef"
[0m      recipe_name "partybus"
[0m      domain nil
[0m      user nil
[0m    end
[0m    
[0m    System Info:[0m
    ------------[0m
    chef_version=14.3.37
[0m    platform=ubuntu
[0m    platform_version=16.04
[0m    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
[0m    program_name=/opt/opscode/embedded/bin/chef-client
[0m    executable=/opt/opscode/embedded/bin/chef-client[0m
    
[0mRecipe: private-chef::opscode-chef-mover[0m
  * execute[restart_opscode-chef-mover_log_service] action run
    [32m- execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/opscode-chef-mover/log[0m
[0mRecipe: private-chef::redis_lb[0m
  * execute[restart_redis_lb_log_service] action run
    [32m- execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/redis_lb/log[0m
[0m[0m
Running handlers:[0m
Running handlers complete
[0mChef Client failed. 306 resources updated in 01 minutes 59 seconds[0m
[2018-11-16T15:16:20+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2018-11-16T15:16:20+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-11-16T15:16:20+00:00] FATAL: Chef::Exceptions::MultipleFailures: Multiple failures occurred:
* TypeError occurred in chef run: openssl_x509_certificate[/var/opt/opscode/nginx/ca/.crt] (private-chef::nginx line 77) had an error: TypeError: no implicit conversion of nil into String
* Mixlib::ShellOut::ShellCommandFailed occurred in delayed notification: runit_service[nginx] (private-chef::nginx line 37) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
STDOUT: fail: /opt/opscode/service/nginx: unable to change to service directory: file does not exist
STDERR: 
---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx returned 1
* Mixlib::ShellOut::ShellCommandFailed occurred in delayed notification: execute[set initial migration level] (private-chef::partybus line 59) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of cd /opt/opscode/embedded/service/partybus && ./bin/partybus init ----
STDOUT: 
STDERR: /opt/opscode/embedded/service/gem/ruby/2.5.0/gems/sequel-3.34.1/lib/sequel/database/schema_generator.rb:19: warning: constant ::Fixnum is deprecated
/opt/opscode/embedded/service/gem/ruby/2.5.0/gems/sequel-3.34.1/lib/sequel/database/schema_generator.rb:19: warning: constant ::Bignum is deprecated
./bin/partybus:11:in `require': cannot load such file -- /opt/opscode/embedded/service/partybus/config.rb (LoadError)
	from ./bin/partybus:11:in `<main>'
---- End output of cd /opt/opscode/embedded/service/partybus && ./bin/partybus init ----
Ran cd /opt/opscode/embedded/service/partybus && ./bin/partybus init returned 1
```

**Comment by jrobison-sb** [comment]
FWIW, running the same exact thing (but with the 18.04 deb) works fine on Ubuntu 18.04. So I'm unblocked and no longer care about following up on this issue. As far as I'm concerned this can be closed, but I'll leave it open and let the maintainers decide.
