### ISSUE TITLE
sudo chef-server-ctl reconfigure on Ubuntu 18.04 failed

### ISSUE THREAD

**Issue by stephanvierkant** [chef/chef-server#1641]
I'm trying to install chef-server on a Ubuntu 18.04 instance, but it failes:

```
wget https://packages.chef.io/files/stable/chef-server/12.19.31/ubuntu/18.04/chef-server-core_12.19.31-1_amd64.deb

sudo dpkg -i chef-server-core_12.19.31-1_amd64.deb
sudo chef-server-ctl reconfigure
```

Full output: https://gist.github.com/stephanvierkant/04791b5d28185ebd603920f131723556

```
Chef Client failed. 341 resources updated in 02 minutes 05 seconds
[2019-03-13T10:07:27+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2019-03-13T10:07:27+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-03-13T10:07:27+00:00] FATAL: Chef::Exceptions::MultipleFailures: Multiple failures occurred:
* TypeError occurred in chef run: openssl_x509_certificate[/var/opt/opscode/nginx/ca/.crt] (private-chef::nginx line 77) had an error: TypeError: no implicit conversion of nil into String
* Mixlib::ShellOut::ShellCommandFailed occurred in delayed notification: runit_service[nginx] (private-chef::nginx line 37) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
STDOUT: fail: /opt/opscode/service/nginx: unable to change to service directory: file does not exist
STDERR: 
---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx returned 1
* Mixlib::ShellOut::ShellCommandFailed occurred in delayed notification: execute[set initial migration level] (private-chef::partybus line 59) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of cd /opt/opscode/embedded/service/partybus && ./bin/partybus init ----
STDOUT: 
STDERR: /opt/opscode/embedded/service/gem/ruby/2.5.0/gems/sequel-3.34.1/lib/sequel/database/schema_generator.rb:19: warning: constant ::Fixnum is deprecated
/opt/opscode/embedded/service/gem/ruby/2.5.0/gems/sequel-3.34.1/lib/sequel/database/schema_generator.rb:19: warning: constant ::Bignum is deprecated
./bin/partybus:11:in `require': cannot load such file -- /opt/opscode/embedded/service/partybus/config.rb (LoadError)
        from ./bin/partybus:11:in `<main>'
---- End output of cd /opt/opscode/embedded/service/partybus && ./bin/partybus init ----
Ran cd /opt/opscode/embedded/service/partybus && ./bin/partybus init returned 1

```

 ```
================================================================================
    Error executing action `create` on resource 'openssl_x509_certificate[/var/opt/opscode/nginx/ca/.crt]'
    ================================================================================
    
    TypeError
    ---------
    no implicit conversion of nil into String
    
    Resource Declaration:
    ---------------------
    # In /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/nginx.rb
    
     77:    openssl_x509_certificate ssl_crtfile do
     78:      common_name server_name
     79:      org node['private_chef']['nginx']['ssl_company_name']
     80:      org_unit node['private_chef']['nginx']['ssl_organizational_unit_name']
     81:      country node['private_chef']['nginx']['ssl_country_name']
     82:      key_length node['private_chef']['nginx']['ssl_key_length']
     83:      expire node['private_chef']['nginx']['ssl_duration']
     84:      subject_alt_name [ "#{server_name_type}:#{server_name}" ]
     85:      owner OmnibusHelper.new(node).ownership['owner']
     86:      group OmnibusHelper.new(node).ownership['group']
     87:      mode '0600'
     88:    end
     89: 

```

```
================================================================================
    Error executing action `restart` on resource 'runit_service[nginx]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
    STDOUT: fail: /opt/opscode/service/nginx: unable to change to service directory: file does not exist
    STDERR: 
    ---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
    Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx returned 1
    
    Cookbook Trace:
    ---------------
    /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:174:in `tap'
    /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:174:in `safe_sv_shellout!'
    /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:202:in `restart_service'
    /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/provider_runit_service.rb:330:in `block in <class:RunitService>'
    
    Resource Declaration:
    ---------------------
    # In /var/opt/opscode/local-mode-cache/cookbooks/enterprise/definitions/component_runit_service.rb
    
     37:   runit_service component do
     38:     action :enable
     39:     retries 20
     40:     control params[:control] if params[:control]
     41:     options(
     42:       log_directory: log_directory
     43:     )
     44:     params[:runit_attributes].each do |attr_name, attr_value|
     45:       send(attr_name.to_sym, attr_value)
     46:     end
     47:   end
     48: 
 
```

```
    ================================================================================
    Error executing action `run` on resource 'execute[set initial migration level]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of cd /opt/opscode/embedded/service/partybus && ./bin/partybus init ----
    STDOUT: 
    STDERR: /opt/opscode/embedded/service/gem/ruby/2.5.0/gems/sequel-3.34.1/lib/sequel/database/schema_generator.rb:19: warning: constant ::Fixnum is deprecated
    /opt/opscode/embedded/service/gem/ruby/2.5.0/gems/sequel-3.34.1/lib/sequel/database/schema_generator.rb:19: warning: constant ::Bignum is deprecated
    ./bin/partybus:11:in `require': cannot load such file -- /opt/opscode/embedded/service/partybus/config.rb (LoadError)
        from ./bin/partybus:11:in `<main>'
    ---- End output of cd /opt/opscode/embedded/service/partybus && ./bin/partybus init ----
    Ran cd /opt/opscode/embedded/service/partybus && ./bin/partybus init returned 1
    
    Resource Declaration:
    ---------------------
    # In /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/partybus.rb
    
     59: execute "set initial migration level" do
     60:   action :nothing
     61:   command "cd /opt/opscode/embedded/service/partybus && ./bin/partybus init"
     62:   subscribes :run, "file[#{OmnibusHelper.bootstrap_sentinel_file}]", :delayed
     63: end
     64: 
 ```

**Comment by stephanvierkant** [comment]
I followed [these instructions](https://docs.chef.io/install_server.html) and that didn't include changing any configuration. But to be honest, I forgot to fix the "resolvable hostname" part that caused the problem. After I set the hostname, it worked. 

Must be said that this is not a bug, I didn't read the installation instruction properly. So please consider my issue as a feature request to include a nice and clear error message instead of a fatal error.

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-server/issues/21

**Comment by PrajaktaPurohit** [comment]
Looks like we have a check for tier configuration : https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/libraries/private_chef.rb#L656

It would be helpful to include "hostname_resolvable by ohai" check in the system preflight checks.
This would need to be tested for standalone and tiered setups.
