### ISSUE TITLE
Can't install addons on new Chef server

### ISSUE THREAD

**Issue by scalp42** [chef/chef-server#1650]
### Chef Server Version

`chef-server-core_12.19.31-1_amd64`

### Platform Details

Ubuntu 18.04

### Configuration
```ruby
addons['install'] = true
```

### Scenario:

Automate the installation of plugins.

### Steps to Reproduce:

```
$> wget https://packages.chef.io/files/stable/chef-server/12.19.31/ubuntu/18.04/chef-server-core_12.19.31-1_amd64.deb

$> dpkg -i chef-server-core_12.19.31-1_amd64.deb

$> chef-server-ctl reconfigure
```

### Actual Result:

```
Starting Chef Client, version 14.11.21
resolving cookbooks for run list: ["private-chef::default"]
Synchronizing Cookbooks:
  - private-chef (0.1.1)
  - enterprise (0.14.1)
  - runit (4.1.1)
  - packagecloud (1.0.1)
  - yum-epel (3.3.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Recipe: private-chef::default
  * directory[/etc/opscode] action create (up to date)
  * directory[/etc/opscode/logrotate.d] action create (up to date)

  ================================================================================
  Recipe Compile Error in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb
  ================================================================================

  Net::HTTPServerException
  ------------------------
  404 "Not Found"

  Cookbook Trace:
  ---------------
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb:68:in `block in from_file'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb:62:in `each'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb:62:in `from_file'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb:24:in `from_file'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:164:in `block in from_file'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:147:in `each'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:147:in `from_file'

  Relevant File Content:
  ----------------------
  /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb:

   61:
   62:    node['private_chef']['addons']['packages'].each do |pkg|
   63:      artifact_info = Mixlib::Install.new(
   64:        channel: :stable,
   65:        product_name: pkg.split(/(chef-|opscode-)(.*)/).last,
   66:        product_version: :latest,
   67:        platform_version_compatibility_mode: true
   68>>     ).detect_platform.artifact_info
   69:
   70:      pkg_file = File.join(addon_path, File.basename(artifact_info.url))
   71:
   72:      remote_file pkg_file do
   73:        source artifact_info.url
   74:        checksum artifact_info.sha256
   75:      end
   76:    end
   77:  else

  System Info:
  ------------
  chef_version=14.11.21
  platform=ubuntu
  platform_version=18.04
  ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
  program_name=/opt/opscode/embedded/bin/chef-client
  executable=/opt/opscode/embedded/bin/chef-client


  Running handlers:
    - #<Class:0x00000000043572e0>::AddonInstallHandler
  Running handlers complete
  Chef Client failed. 0 resources updated in 03 seconds
[2019-03-26T21:05:41+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2019-03-26T21:05:41+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-03-26T21:05:41+00:00] FATAL: Net::HTTPServerException: 404 "Not Found"
```

**Comment by scalp42** [comment]
@PrajaktaPurohit any updates? 😅

**Comment by PrajaktaPurohit** [comment]
Sorry for the delay! Closing since Chef-Manage and Push Jobs are deprecated and End of Life.
