### ISSUE TITLE
13 upgrade failure

### ISSUE THREAD

**Issue by btm** [chef/chef-server#1684]
chef-server-core 12.17.33 upgrade to 13.0.10 on ubuntu 16.04:

```
+---------------------------------------------+
Starting Chef Infra Client, version 15.0.300
resolving cookbooks for run list: ["private-chef::default"]
Synchronizing Cookbooks:
  - private-chef (0.1.1)
  - enterprise (0.15.1)
  - runit (5.1.1)
  - yum-epel (3.3.0)
  - packagecloud (1.0.1)
Installing Cookbook Gems:
Compiling Cookbooks...
Recipe: private-chef::default
  * directory[/etc/opscode] action create (up to date)
  * directory[/etc/opscode/logrotate.d] action create (up to date)
  
  ================================================================================
  Recipe Compile Error in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb
  ================================================================================
  
  Errno::ENOENT
  -------------
  No such file or directory @ rb_sysopen - /var/opt/opscode/plugins/chef-ha-drbd.rb
  
  Cookbook Trace:
  ---------------
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/enterprise_plugin_collection.rb:24:in `read'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/enterprise_plugin_collection.rb:24:in `load_from_file'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/enterprise_plugin_collection.rb:54:in `block in from_glob'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/enterprise_plugin_collection.rb:53:in `glob'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/enterprise_plugin_collection.rb:53:in `from_glob'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/plugin_discovery.rb:21:in `from_file'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:49:in `from_file'
  
  Relevant File Content:
  ----------------------
  /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/enterprise_plugin_collection.rb:
  
   17:  
   18:    def by_name(name)
   19:      @plugins.find {|p| p.name == name }
   20:    end
   21:  
   22:    def load_from_file(filename)
   23:      nc = EnterprisePluginCollection.new
   24>>     nc.instance_eval(::File.read(filename))
   25:      nc.plugins.each do |p|
   26:        p.cookbook_path "#{::File.dirname(filename)}/embedded/cookbooks" unless p.cookbook_path
   27:        p.definition_location filename
   28:      end
   29:  
   30:      # Don't add already loaded plugins to the path.
   31:      nc.plugins.reject! do |p|
   32:        if plugin_names.include?(p.name)
   33:          Chef::Log.warn("Plugin #{p.name} already loaded, not loading #{p.name} from #{filename}")
  
  System Info:
  ------------
  chef_version=15.0.300
  platform=ubuntu
  platform_version=16.04
  ruby=ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
  program_name=/opt/opscode/embedded/bin/chef-client
  executable=/opt/opscode/embedded/bin/chef-client
  
  
  Running handlers:
  Running handlers complete
  Chef Infra Client failed. 0 resources updated in 09 seconds
[2019-06-21T00:17:22+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2019-06-21T00:17:22+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-06-21T00:17:22+00:00] FATAL: Errno::ENOENT: No such file or directory @ rb_sysopen - /var/opt/opscode/plugins/chef-ha-drbd.rb
```

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /var/opt/opscode/plugins/chef-ha-drbd.rb
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/enterprise_plugin_collection.rb:24:in `read'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/enterprise_plugin_collection.rb:24:in `load_from_file'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/enterprise_plugin_collection.rb:54:in `block in from_glob'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/enterprise_plugin_collection.rb:53:in `glob'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/enterprise_plugin_collection.rb:53:in `from_glob'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/plugin_discovery.rb:21:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/mixin/from_file.rb:34:in `instance_eval'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/mixin/from_file.rb:34:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/cookbook_version.rb:199:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context.rb:362:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context.rb:318:in `block in include_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context.rb:317:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context.rb:317:in `include_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:49:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/mixin/from_file.rb:34:in `instance_eval'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/mixin/from_file.rb:34:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/cookbook_version.rb:199:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context.rb:362:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context/cookbook_compiler.rb:166:in `block in compile_recipes'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context/cookbook_compiler.rb:163:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context/cookbook_compiler.rb:163:in `compile_recipes'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context/cookbook_compiler.rb:79:in `compile'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context.rb:212:in `load'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/policy_builder/expand_node_object.rb:103:in `setup_run_context'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/client.rb:488:in `setup_run_context'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/client.rb:285:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/application.rb:314:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/application.rb:290:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/local_mode.rb:41:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/application.rb:273:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/application/client.rb:447:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/application.rb:69:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-bin-15.0.300/bin/chef-client:25:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:23:in `load'
/opt/opscode/embedded/bin/chef-client:23:in `<main>'
```

**Comment by markan** [comment]
This looks like it's fixed in 13.0.14 by PR #1686
