### ISSUE TITLE
Chef - LDAP authentication make chef webui burns

### ISSUE THREAD

**Issue by Ashjoker24** [chef/chef-server#1720]
### Scenario: Enable LDAP authentication in chef WebUI
Hi i attached mt chef-server.rb file with this issue. I tried to enable LDAP in chef server webUI, but when i tried to login in webui using LDAP or chefadmin the dashboard shows 500
Smell something burning?
Sorry we have a small fire in the kitchen.
An unexpected error has occurred. Our staff are manning the fire extinguishers and have been alerted.
Try refreshing the page, or contact us if the problem persists.

what can i do for that??

# cat chef-server.rb

ldap['base_dn'] = 'cn=group,ou=organization,dc=domain,dc=com',

ldap['bind_dn'] = 'cn=Manager,dc=domain,dc=com',

ldap['bind_password'] = 'ldap admin password'

ldap['group_dn'] = 'cn=group,ou=organization,dc=domain,dc=com',

ldap['host'] = '<ldap machine IP>',

ldap['login_attribute'] = 'uid',

ldap['port'] = '389',

ldap['ssl_enabled'] = false,

ldap['system_adjective'] = 'Company LDAP',

ldap['timeout'] = 60000,

ldap['tls_enabled'] = true

**Comment by PrajaktaPurohit** [comment]
@Ashjoker24 It would be very helpful if you could post the output of your chef-manage logs(/var/log/chef-manage/web/current) and opscode-erchef logs (/var/log/opscode/opscode-erchef/current) around the time of the error. Let us know if you are uncomfortable posting logs on the public forum and we can set something up.

**Comment by PrajaktaPurohit** [comment]
@robbkidd would love to know you insights for debugging/fixing this issue.

**Comment by Ashjoker24** [comment]
[root@chefldap web]# tail -40 current
2019-09-05_10:36:22.45971 /opt/chef-manage/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
2019-09-05_10:36:22.45971 /opt/chef-manage/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
2019-09-05_10:36:22.45971 /opt/chef-manage/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli.rb:27:in `dispatch'
2019-09-05_10:36:22.45971 /opt/chef-manage/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
2019-09-05_10:36:22.45972 /opt/chef-manage/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli.rb:18:in `start'
2019-09-05_10:36:22.45972 /opt/chef-manage/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/exe/bundle:30:in `block in <top (required)>'
2019-09-05_10:36:22.45973 /opt/chef-manage/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
2019-09-05_10:36:22.45973 /opt/chef-manage/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/exe/bundle:22:in `<top (required)>'
2019-09-05_10:36:22.45973 /opt/chef-manage/embedded/bin/bundle:23:in `load'
2019-09-05_10:36:22.45973 /opt/chef-manage/embedded/bin/bundle:23:in `<main>'
2019-09-05_10:36:22.45973 I, [2019-09-05T10:36:22.456248 #3257]  INFO -- :   Rendered errors/error_500.haml within layouts/outside (0.1ms)
2019-09-05_10:36:22.45973 I, [2019-09-05T10:36:22.457464 #3257]  INFO -- :   Rendered shared/_header.html.erb (0.3ms)
2019-09-05_10:36:22.45974 I, [2019-09-05T10:36:22.458098 #3257]  INFO -- :   Rendered shared/_footer.html.haml (0.5ms)
2019-09-05_10:36:22.45974 I, [2019-09-05T10:36:22.458502 #3257]  INFO -- :   Rendered layouts/_client_config.html.erb (0.3ms)
2019-09-05_10:36:22.45974 I, [2019-09-05T10:36:22.458948 #3257]  INFO -- :   Rendered shared/_js.html.erb (0.1ms)
2019-09-05_10:36:22.45974 I, [2019-09-05T10:36:22.459065 #3257]  INFO -- :   Rendered shared/_marketo.html.erb (0.0ms)
2019-09-05_10:36:22.45975 I, [2019-09-05T10:36:22.459197 #3257]  INFO -- : Completed 500 Internal Server Error in 19ms (Views: 3.3ms)
2019-09-05_10:36:24.24400 I, [2019-09-05T10:36:24.242173 #3257]  INFO -- : Started GET "/login" for 127.0.0.1 at 2019-09-05 10:36:24 +0000
2019-09-05_10:36:24.24402 I, [2019-09-05T10:36:24.242952 #3257]  INFO -- : Processing by SessionsController#new as HTML
2019-09-05_10:36:24.24960 I, [2019-09-05T10:36:24.246340 #3257]  INFO -- :   Rendered sessions/new.html.erb within layouts/outside (1.2ms)
2019-09-05_10:36:24.24962 I, [2019-09-05T10:36:24.247317 #3257]  INFO -- :   Rendered shared/_header.html.erb (0.5ms)
2019-09-05_10:36:24.24962 I, [2019-09-05T10:36:24.247754 #3257]  INFO -- :   Rendered shared/_footer.html.haml (0.3ms)
2019-09-05_10:36:24.24963 I, [2019-09-05T10:36:24.248456 #3257]  INFO -- :   Rendered layouts/_client_config.html.erb (0.3ms)
2019-09-05_10:36:24.24963 I, [2019-09-05T10:36:24.248705 #3257]  INFO -- :   Rendered shared/_js.html.erb (0.1ms)
2019-09-05_10:36:24.24963 I, [2019-09-05T10:36:24.249109 #3257]  INFO -- :   Rendered shared/_marketo.html.erb (0.0ms)
2019-09-05_10:36:24.24963 I, [2019-09-05T10:36:24.249286 #3257]  INFO -- : Completed 200 OK in 6ms (Views: 4.4ms)
2019-09-05_10:38:03.36599 I, [2019-09-05T10:38:03.364058 #3254]  INFO -- : Started GET "/" for 127.0.0.1 at 2019-09-05 10:38:03 +0000
2019-09-05_10:38:03.36602 I, [2019-09-05T10:38:03.365076 #3254]  INFO -- : Processing by DashboardController#show as HTML
2019-09-05_10:38:03.36690 I, [2019-09-05T10:38:03.366630 #3254]  INFO -- : Redirected to https://192.168.2.48/login
2019-09-05_10:38:03.36691 I, [2019-09-05T10:38:03.366687 #3254]  INFO -- : Filter chain halted as :require_login rendered or redirected
2019-09-05_10:38:03.36691 I, [2019-09-05T10:38:03.366743 #3254]  INFO -- : Completed 302 Found in 2ms
2019-09-05_10:38:03.38820 I, [2019-09-05T10:38:03.385891 #3254]  INFO -- : Started GET "/login" for 127.0.0.1 at 2019-09-05 10:38:03 +0000
2019-09-05_10:38:03.38822 I, [2019-09-05T10:38:03.386964 #3254]  INFO -- : Processing by SessionsController#new as HTML
2019-09-05_10:38:03.39329 I, [2019-09-05T10:38:03.393198 #3254]  INFO -- :   Rendered sessions/new.html.erb within layouts/outside (3.8ms)
2019-09-05_10:38:03.39421 I, [2019-09-05T10:38:03.394133 #3254]  INFO -- :   Rendered shared/_header.html.erb (0.2ms)
2019-09-05_10:38:03.39486 I, [2019-09-05T10:38:03.394795 #3254]  INFO -- :   Rendered shared/_footer.html.haml (0.5ms)
2019-09-05_10:38:03.39665 I, [2019-09-05T10:38:03.395559 #3254]  INFO -- :   Rendered layouts/_client_config.html.erb (0.6ms)
2019-09-05_10:38:03.39666 I, [2019-09-05T10:38:03.395815 #3254]  INFO -- :   Rendered shared/_js.html.erb (0.1ms)
2019-09-05_10:38:03.39666 I, [2019-09-05T10:38:03.395946 #3254]  INFO -- :   Rendered shared/_marketo.html.erb (0.0ms)
2019-09-05_10:38:03.39666 I, [2019-09-05T10:38:03.396333 #3254]  INFO -- : Completed 200 OK in 9ms (Views: 7.7ms)

**Comment by Ashjoker24** [comment]
[root@chefldap web]# tail -40 /var/log/opscode/opscode-erchef/current
2019-09-05_10:38:16.08611 [info] Application opscoderl_folsom started on node 'erchef@127.0.0.1'
2019-09-05_10:38:16.08630 [info] Application observer started on node 'erchef@127.0.0.1'
2019-09-05_10:38:16.08653 [info] Application mini_s3 started on node 'erchef@127.0.0.1'
2019-09-05_10:38:16.08931 [info] Application gs started on node 'erchef@127.0.0.1'
2019-09-05_10:38:16.08954 [info] Folsom Graphite adaptor starting.
2019-09-05_10:38:16.08976 [info] Application folsom_graphite started on node 'erchef@127.0.0.1'
2019-09-05_10:38:16.08998 [info] Application et started on node 'erchef@127.0.0.1'
2019-09-05_10:38:16.09025 [info] Application cf started on node 'erchef@127.0.0.1'
2019-09-05_10:38:16.09093 [info] Application erlware_commons started on node 'erchef@127.0.0.1'
2019-09-05_10:38:16.09104 [info] Application envy started on node 'erchef@127.0.0.1'
2019-09-05_10:38:16.09118 [info] Application chef_authn started on node 'erchef@127.0.0.1'
2019-09-05_10:38:16.09127 [info] Application depsolver started on node 'erchef@127.0.0.1'
2019-09-05_10:38:16.09139 [info] Application runtime_tools started on node 'erchef@127.0.0.1'
2019-09-05_10:38:17.79578 [info] Application pooler started on node 'erchef@127.0.0.1'
2019-09-05_10:38:17.79674 [info] Application opscoderl_httpc started on node 'erchef@127.0.0.1'
2019-09-05_10:38:17.79845 [info] Application data_collector started on node 'erchef@127.0.0.1'
2019-09-05_10:38:17.79903 [info] Application chef_objects started on node 'erchef@127.0.0.1'
2019-09-05_10:38:17.79903 [info] Loading ibrowse configuration from /opt/opscode/embedded/service/opscode-erchef/etc/ibrowse/ibrowse.config
2019-09-05_10:38:17.79926 [info] Application sqerl started on node 'erchef@127.0.0.1'
2019-09-05_10:38:17.79952 [info] Application chef_db started on node 'erchef@127.0.0.1'
2019-09-05_10:38:17.80019 [info] Application oc_chef_authz started on node 'erchef@127.0.0.1'
2019-09-05_10:38:17.84919 [info] Starting oc_chef_action
2019-09-05_10:38:17.98264 [info] Vhost "/analytics", queue "alaska" not at capacity or RabbitMQ Management Plugin unavailable
2019-09-05_10:38:17.98271 [info] Starting actions queue monitoring for vhost "/analytics" and queue "alaska"
2019-09-05_10:38:17.98299 [info] Chef Actions: Connecting to RabbitMQ at {127,0,0,1}:5672/analytics (exchange: <<"actions">>)
2019-09-05_10:38:17.98932 [info] Negotiated maximums: (Channel = 0, Frame = 131072, Heartbeat = 60)
2019-09-05_10:38:17.99060 [info] Chef Keyring starting
2019-09-05_10:38:17.99096 [info] Starting chef_index_sup.
2019-09-05_10:38:17.99145 [info] Creating HTTP pool for Solr.
2019-09-05_10:38:17.99658 [info] Connecting to Rabbit at {127,0,0,1}:5672 {<<"/chef">>,<<>>}
2019-09-05_10:38:18.00270 [info] Negotiated maximums: (Channel = 0, Frame = 131072, Heartbeat = 60)
2019-09-05_10:38:18.01017 [info] chef_keygen_cache configured size: 10 start_size: 0 max_workers: 1
2019-09-05_10:38:18.01018 [info] chef_keygen_cache starting with 0 keys in cache
2019-09-05_10:38:18.01018 [info] Application oc_chef_wm started on node 'erchef@127.0.0.1'
2019-09-05_10:38:18.01018 [info] Application oc_erchef started on node 'erchef@127.0.0.1'
2019-09-05_10:38:18.01739 [info] Application mnesia started on node 'erchef@127.0.0.1'
2019-09-05_10:38:18.01757 [info] Application eper started on node 'erchef@127.0.0.1'
2019-09-05_10:38:18.01775 [info] Application recon started on node 'erchef@127.0.0.1'
2019-09-05_10:38:18.01792 [info] Application observer_cli started on node 'erchef@127.0.0.1'
2019-09-05_10:38:18.01807 [info] Application efast_xs started on node 'erchef@127.0.0.1'

**Comment by PrajaktaPurohit** [comment]
@Ashjoker24 thank you for your response. My apologies for the delay. This looks like the breakage due to upgrading for fixing the CVE's as described in #1642 . This issue should be fixed with the upcoming Chef-Infra-Server release that has erlang updated to R19. Meanwhile I can suggest trying to use Chef-InfraServer version 12.17.33. Sorry for the pain.

**Comment by PrajaktaPurohit** [comment]
Closing for now. Please feel free to reopen if needed.
