### ISSUE TITLE
Still getting ERROR: 413 "Request Entity Too Large" (Net::HTTPServerException)

### ISSUE THREAD

**Issue by vsingh-msys** [chef/chef-server#1729]
### Chef Server Version
Chef Infra Server 13.0.37, 12.17.33

### Platform Details
[Operating system distribution and release version. Cloud provider and instance type if running in the cloud. Total/Free RAM and disk space. Is this running in a container?]
Ubuntu 16.04
```
vagrant@chef-server:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:            992         607         145          32         239         180
Swap:           979         225         754
```

### Configuration
[Standalone, Tiered, HA, Chef Backend? New install or upgrade? Ideally include your /etc/opscode/chef-server.rb or otherwise provide details of changes from the default]
New Standalone chef-server.
```
data_collector['root_url'] = 'https://chef-automate.test/data-collector/v0/'
data_collector['proxy'] = true
profiles['root_url'] = 'https://chef-automate.test'
```

Chef Automate  Version: 2 Build: 20190813170406 

### Scenario:
Added multiple profiles using audit cookbook for and try to bootstrap ubuntu 16.04 vagrant node.

### Steps to Reproduce:
1. Setup Chef server and Chef automate.
2. Add multiple profiles using audit cookbook version(8.0.0 or 8.1.1)
3. Bootstrap the ubuntu node with empty run list.
4. Run chef client on node with audit cookbook run list.

### Expected Result:
As per the PR https://github.com/chef/chef-server/pull/1649 the request side is doubled but seems getting the same issue if request size below 5MB.

### Actual Result:
```
vagrant@node1:~$ sudo chef-client -o auditviv
Starting Chef Infra Client, version 15.2.20
[2019-08-26T06:10:52+00:00] WARN: Run List override has been provided.
[2019-08-26T06:10:52+00:00] WARN: Original Run List: []
[2019-08-26T06:10:52+00:00] WARN: Overridden Run List: [recipe[auditviv]]
resolving cookbooks for run list: ["auditviv"]
Synchronizing Cookbooks:
  - auditviv (0.2.11)
  - audit (8.1.1)
Installing Cookbook Gems:
Compiling Cookbooks...
Recipe: audit::inspec
  * inspec_gem[inspec] action install (up to date)
  Converging 1 resources
  * inspec_gem[inspec] action nothing (skipped due to action :nothing)
[2019-08-26T06:10:52+00:00] WARN: Skipping final node save because override_runlist was given

Running handlers:
[2019-08-26T06:10:52+00:00] WARN: Use of a hash array for the node['audit']['profiles'] is deprecated. Please refer to the README and use a hash of hashes.
controls/translated-controls.rb:2628: warning: regular expression has ']' without escape
[2019-08-26T06:10:56+00:00] WARN: Overwriting resource apache. To reference a specific version of apache use the resource() method
controls/translated-controls.rb:3285: warning: regular expression has ']' without escape
[2019-08-26T06:11:09+00:00] WARN: Compliance report size is 3.01 MB.
/var/chef/cache/cookbooks/audit/libraries/helper.rb:47: warning: constant Net::HTTPServerException is deprecated
[2019-08-26T06:11:09+00:00] ERROR: 413 "Request Entity Too Large" (Net::HTTPServerException)
/opt/chef/embedded/lib/ruby/2.6.0/net/http/response.rb:122:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/http.rb:152:in `request'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/http.rb:131:in `post'
/var/chef/cache/cookbooks/audit/libraries/reporters/cs_automate.rb:44:in `block in send_report'
/var/chef/cache/cookbooks/audit/libraries/helper.rb:41:in `with_http_rescue'
/var/chef/cache/cookbooks/audit/libraries/reporters/cs_automate.rb:43:in `send_report'
/var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:256:in `send_report'
/var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:88:in `block in report'
/var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:87:in `each'
/var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:87:in `report'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/handler.rb:256:in `run_report_unsafe'
/var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:100:in `run_report_safely'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/handler.rb:123:in `block in run_report_handlers'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/handler.rb:121:in `each'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/handler.rb:121:in `run_report_handlers'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/handler.rb:133:in `block in <class:Handler>'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/client.rb:418:in `block in run_completed_successfully'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/client.rb:417:in `each'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/client.rb:417:in `run_completed_successfully'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/client.rb:293:in `run'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/application.rb:320:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/application.rb:296:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/application.rb:279:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/application/base.rb:330:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/application.rb:69:in `run'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-bin-15.2.20/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:162:in `load'
/usr/bin/chef-client:162:in `<main>'
[2019-08-26T06:11:09+00:00] ERROR: Received HTTP error 413
  - Chef::Handler::AuditReport
Running handlers complete
Chef Infra Client finished, 0/2 resources updated in 19 seconds
```

**Comment by vsingh-msys** [comment]
Hi @PrajaktaPurohit 
Increasing the `max_request_size` is working as expected. 

only concerned was In https://github.com/chef/chef-server/pull/1649 we have double the  max_request_size size but still taking 2MB. This might be a version issue.

Thanks for your time!
