### ISSUE TITLE
Cannot install 13.0.17 on Ubuntu 18.04 undefined method `[]` for nil:NilClass

### ISSUE THREAD

**Issue by nitrocode** [chef/chef-server#1769]
### Chef Server Version
13.0.17

### Platform Details
ubuntu 18.04

### Configuration
New install

### Scenario:
[What you are trying to achieve and you can't?]

### Steps to Reproduce:

```
wget https://packages.chef.io/files/stable/chef-server/13.0.17/ubuntu/18.04/chef-server-core_13.0.17-1_amd64.deb
sudo dpkg -i chef*.deb
sudo chef-server-ctl reconfigure --chef-license=accept
```

### Expected Result:
Install is successful

### Actual Result:
```
# chef-server-ctl reconfigure --chef-license=accept
Starting Chef Infra Client, version 15.0.300
resolving cookbooks for run list: ["private-chef::default"]
Synchronizing Cookbooks:
  - runit (5.1.1)
  - yum-epel (3.3.0)
  - packagecloud (1.0.1)
  - private-chef (0.1.1)
  - enterprise (0.15.1)
Installing Cookbook Gems:
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/attributes/default.rb
================================================================================

NoMethodError
-------------
undefined method `[]' for nil:NilClass

Cookbook Trace:
---------------
  /var/opt/opscode/local-mode-cache/cookbooks/private-chef/attributes/default.rb:616:in `from_file'

Relevant File Content:
----------------------
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/attributes/default.rb:

609:  default['private_chef']['postgresql']['db_superuser'] = 'opscode-pgsql'
610:  default['private_chef']['postgresql']['shell'] = "/bin/sh"
611:  default['private_chef']['postgresql']['home'] = "/var/opt/opscode/postgresql"
612:  default['private_chef']['postgresql']['user_path'] = "/opt/opscode/embedded/bin:/opt/opscode/bin:$PATH"
613:  default['private_chef']['postgresql']['vip'] = "127.0.0.1"
614:  default['private_chef']['postgresql']['port'] = 5432
615:  # We want to listen on all the loopback addresses, because we can't control which one localhost resolves to.616>> default['private_chef']['postgresql']['listen_address'] = node['network']['interfaces']['lo']['addresses'].keys.join(',')
617:  default['private_chef']['postgresql']['max_connections'] = 350
618:  default['private_chef']['postgresql']['keepalives_idle'] = 60
619:  default['private_chef']['postgresql']['keepalives_interval'] = 15
620:  default['private_chef']['postgresql']['keepalives_count'] = 2
621:  default['private_chef']['postgresql']['md5_auth_cidr_addresses'] = [ '127.0.0.1/32', '::1/128' ]
622:  default['private_chef']['postgresql']['wal_level'] = "minimal"
623:  default['private_chef']['postgresql']['archive_mode'] = "off" # "cannot be enabled when wal_level is set to minimal"
624:  default['private_chef']['postgresql']['archive_command'] = ""
625:  default['private_chef']['postgresql']['archive_timeout'] = 0 # 0 is disabled.

System Info:
------------
chef_version=15.0.300
platform=ubuntu
platform_version=18.04
ruby=ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
program_name=/opt/opscode/embedded/bin/chef-client
executable=/opt/opscode/embedded/bin/chef-client


Running handlers:
Running handlers complete
Chef Infra Client failed. 0 resources updated in 02 seconds
[2019-09-25T16:47:32+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2019-09-25T16:47:32+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report[2019-09-25T16:47:32+00:00] FATAL: NoMethodError: undefined method `[]' for nil:NilClass
```

chef-stacktrace.out

```
# cat /var/opt/opscode/local-mode-cache/chef-stacktrace.out
Generated at 2019-09-25 16:51:36 +0000
NoMethodError: undefined method `[]' for nil:NilClass
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/attributes/default.rb:616:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/mixin/from_file.rb:34:in `instance_eval'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/mixin/from_file.rb:34:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/dsl/include_attribute.rb:39:in `block in include_attribute'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/dsl/include_attribute.rb:31:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/dsl/include_attribute.rb:31:in `include_attribute'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context/cookbook_compiler.rb:217:in `load_attribute_file'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context/cookbook_compiler.rb:205:in `load_attributes_from_cookbook'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context/cookbook_compiler.rb:135:in `block in compile_attributes'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context/cookbook_compiler.rb:134:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context/cookbook_compiler.rb:134:in `compile_attributes'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context/cookbook_compiler.rb:76:in `compile'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/run_context.rb:212:in `load'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/policy_builder/expand_node_object.rb:103:in `setup_run_context'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/client.rb:488:in `setup_run_context'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/client.rb:285:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/application.rb:314:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/application.rb:290:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/local_mode.rb:41:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/application.rb:273:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/application/client.rb:447:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-15.0.300/lib/chef/application.rb:69:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-bin-15.0.300/bin/chef-client:25:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:23:in `load'
/opt/opscode/embedded/bin/chef-client:23:in `<main>'
```

This issue may be related https://github.com/chef/chef-server/issues/1008 which suggests rerunning the command. If I rerun the reconfigure command, I receive the same error. I also tried doing a cleanse before.

**Comment by lnxslck** [comment]
2020 and I still have this issue with chef-server-core-13.2.0 and Ubuntu 18.04

**Comment by stevendanna** [comment]
@lnxslck Apologies that you are hitting an issue. If you have a chance, could you try running 

```
 PATH=/opt/opscode/embedded/bin:/opt/opscode/bin:$PATH sudo -E /opt/opscode/embedded/bin/ohai network
```
on the machine where you've experienced this failure.

**Comment by lnxslck** [comment]
> @lnxslck Apologies that you are hitting an issue. If you have a chance, could you try running
> 
> ```
>  PATH=/opt/opscode/embedded/bin:/opt/opscode/bin:$PATH sudo -E /opt/opscode/embedded/bin/ohai network
> ```
> 
> on the machine where you've experienced this failure.

Its a docker container if that matters.

{
  "interfaces": {
    "eth0:": {
      "type": "eth",
      "number": "0:"
    },
    "lo:": {

    }
  },
  "default_gateway": "172.17.0.1",
  "default_interface": "eth0"
}

**Comment by neonidian** [comment]
> @lnxslck Apologies that you are hitting an issue. If you have a chance, could you try running
> 
> ```
>  PATH=/opt/opscode/embedded/bin:/opt/opscode/bin:$PATH sudo -E /opt/opscode/embedded/bin/ohai network
> ```
> 
> on the machine where you've experienced this failure.

I ran this command in a Ubuntu 20.04 docker container with a dedicated user having sudo permissions and i got an empty object 

`
cheff@bf57cf17c1ed:/chef-server$ PATH=/opt/opscode/embedded/bin:/opt/opscode/bin:$PATH sudo -E /opt/opscode/embedded/bin/ohai network
{
  "interfaces": {

  }
}
`

**Comment by zfasel** [comment]
@nitrocode @neonidian @lnxslck / others who are having the same issue and searched for a fix, ohai needs `iproute2` (or ifconfig, but it's 2021, so....) and the ubuntu docker images aren't bloated with it. See https://github.com/chef/ohai/blob/d6ccd995f47034ce8c2b3f31ebd503f610e7ee03/spec/unit/plugins/linux/network_spec.rb#L653 . 

Fix (or workaround? idk) is adding `RUN apt-get install -y iproute2` to your Dockerfile (or otherwise as fits in your config).

**Comment by lnxslck** [comment]
thanks @zfasel

**Comment by tas50** [comment]
I'm going to close this out at this point since this isn't an issue with the code in the chef-server repo, but a package that should be added to a minimal container to make sure it provides data to services. There's a workaround here for anyone running into this in the future.
