### ISSUE TITLE
[terraform] ldap ipv6 errors

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#1954]
```

null_resource.chef_server_test (remote-exec): Failures:
--
  |  
  | null_resource.chef_server_test (remote-exec):   1) authenticate_user POST /authenticate_user with correct credentials superuser user returns 200 ("OK")
  | null_resource.chef_server_test (remote-exec):      Failure/Error:
  | null_resource.chef_server_test (remote-exec):        post(request_url, superuser, :payload => body).should look_like({
  | null_resource.chef_server_test (remote-exec):            :status => 200,
  | null_resource.chef_server_test (remote-exec):            :body_exact => response_body
  | null_resource.chef_server_test (remote-exec):          })
  | null_resource.chef_server_test (remote-exec):
  | null_resource.chef_server_test (remote-exec):        Response should have HTTP status code 200 ('OK'), but it was actually 504 ('Gateway Timeout')
  | null_resource.chef_server_test (remote-exec):          Reponse Body: {"error":["Authentication server is unavailable."]}
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/authenticate_user_spec.rb:119:in `block (4 levels) in <top (required)>'
  |  
  | null_resource.chef_server_test (remote-exec):   2) authenticate_user POST /authenticate_user with invalid username superuser returns 401 ("Unauthorized")
  | null_resource.chef_server_test (remote-exec):      Failure/Error:
  | null_resource.chef_server_test (remote-exec):        response.should look_like({
  | null_resource.chef_server_test (remote-exec):          :status => 401
  | null_resource.chef_server_test (remote-exec):        })
  | null_resource.chef_server_test (remote-exec):
  | null_resource.chef_server_test (remote-exec):        Response should have HTTP status code 401 ('Unauthorized'), but it was actually 504 ('Gateway Timeout')
  | null_resource.chef_server_test (remote-exec):          Reponse Body: {"error":["Authentication server is unavailable."]}
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/authenticate_user_spec.rb:204:in `block (4 levels) in <top (required)>'
  |  
  | null_resource.chef_server_test (remote-exec):   3) authenticate_user POST /authenticate_user with incorrect password superuser returns 401 ("Unauthorized")
  | null_resource.chef_server_test (remote-exec):      Failure/Error:
  | null_resource.chef_server_test (remote-exec):        post(request_url, superuser, :payload => body).should look_like({
  | null_resource.chef_server_test (remote-exec):            :status => 401
  | null_resource.chef_server_test (remote-exec):          })
  | null_resource.chef_server_test (remote-exec):
  | null_resource.chef_server_test (remote-exec):        Response should have HTTP status code 401 ('Unauthorized'), but it was actually 504 ('Gateway Timeout')
  | null_resource.chef_server_test (remote-exec):          Reponse Body: {"error":["Authentication server is unavailable."]}
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/authenticate_user_spec.rb:236:in `block (4 levels) in <top (required)>'
  |  
  | null_resource.chef_server_test (remote-exec):   4) users /users/<name> endpoint PUT /users/<name> superuser authenticating after updates when password is unchanged can authenticate as the modified user when password has not been changed.
  | null_resource.chef_server_test (remote-exec):      Failure/Error:
  | null_resource.chef_server_test (remote-exec):        post(auth_url, superuser, :payload => { 'username' => username,
  | null_resource.chef_server_test (remote-exec):                                                'password' => password }).should look_like({
  | null_resource.chef_server_test (remote-exec):            :status => 200
  | null_resource.chef_server_test (remote-exec):        })
  | null_resource.chef_server_test (remote-exec):
  | null_resource.chef_server_test (remote-exec):        Response should have HTTP status code 200 ('OK'), but it was actually 504 ('Gateway Timeout')
  | null_resource.chef_server_test (remote-exec):          Reponse Body: {"error":["Authentication server is unavailable."]}
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/user_spec.rb:1041:in `block (7 levels) in <top (required)>'
  |  
  | null_resource.chef_server_test (remote-exec): Finished in 57.13 seconds (files took 3.91 seconds to load)
  | null_resource.chef_server_test (remote-exec): 172 examples, 4 failures, 2 pending
  |  
  | null_resource.chef_server_test (remote-exec): Failed examples:
  |  
  | null_resource.chef_server_test (remote-exec): rspec ./spec/api/authenticate_user_spec.rb:118 # authenticate_user POST /authenticate_user with correct credentials superuser user returns 200 ("OK")
  | null_resource.chef_server_test (remote-exec): rspec ./spec/api/authenticate_user_spec.rb:199 # authenticate_user POST /authenticate_user with invalid username superuser returns 401 ("Unauthorized")
  | null_resource.chef_server_test (remote-exec): rspec ./spec/api/authenticate_user_spec.rb:235 # authenticate_user POST /authenticate_user with incorrect password superuser returns 401 ("Unauthorized")
  | null_resource.chef_server_test (remote-exec): rspec ./spec/api/user_spec.rb:1039 # users /users/<name> endpoint PUT /users/<name> superuser authenticating after updates when password is unchanged can authenticate as the modified user when password has not been changed.

```

**Comment by PrajaktaPurohit** [comment]
REF: https://github.com/chef/chef-server/pull/2016
