### ISSUE TITLE
[terraform] oc_id errors in FIPS enabled scenarios ipv4 and ipv6.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#1955]
### Chef Server Version
Observed from 12.17.33.

### Platform Details
All supported platforms

### Configuration
Standalone

```
null_resource.chef_server_test (remote-exec): Failures:
--
  |  
  | null_resource.chef_server_test (remote-exec):   1) oc_id API status endpoint GET /id/v1/status returns 200
  | null_resource.chef_server_test (remote-exec):      Failure/Error:
  | null_resource.chef_server_test (remote-exec):        get(request_url, platform.superuser).should look_like({:status => 200,
  | null_resource.chef_server_test (remote-exec):                                                               :body => good_status})
  | null_resource.chef_server_test (remote-exec):
  | null_resource.chef_server_test (remote-exec):        Response should have HTTP status code 200 ('OK'), but it was actually 503 ('Service Unavailable')
  | null_resource.chef_server_test (remote-exec):          Reponse Body: {"status":"not ok","erchef":{"status":"authentication error"},"postgres":{"status":"reachable","connections":41}}
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:46:in `block (4 levels) in <top (required)>'
  |  
  | null_resource.chef_server_test (remote-exec):   2) oc_id API key reset returns a non-zero file
  | null_resource.chef_server_test (remote-exec):      Failure/Error: cookie = response.headers[:set_cookie][1].split(";").first
  | null_resource.chef_server_test (remote-exec):
  | null_resource.chef_server_test (remote-exec):      NoMethodError:
  | null_resource.chef_server_test (remote-exec):        undefined method `split' for nil:NilClass
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:64:in `signin'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:71:in `block (3 levels) in <top (required)>'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:9:in `block (2 levels) in <top (required)>'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:74:in `block (3 levels) in <top (required)>'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:77:in `block (3 levels) in <top (required)>'
  |  
  | null_resource.chef_server_test (remote-exec):   3) oc_id API key reset returns a valid key
  | null_resource.chef_server_test (remote-exec):      Failure/Error: cookie = response.headers[:set_cookie][1].split(";").first
  | null_resource.chef_server_test (remote-exec):
  | null_resource.chef_server_test (remote-exec):      NoMethodError:
  | null_resource.chef_server_test (remote-exec):        undefined method `split' for nil:NilClass
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:64:in `signin'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:71:in `block (3 levels) in <top (required)>'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:9:in `block (2 levels) in <top (required)>'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:74:in `block (3 levels) in <top (required)>'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:82:in `block (3 levels) in <top (required)>'
  |  
  | null_resource.chef_server_test (remote-exec):   4) oc_id API signin with correct password POST /id/auth/chef/callback redirects us to authorized applications
  | null_resource.chef_server_test (remote-exec):      Failure/Error: expect(response.headers[:location]).to end_with('/id/oauth/authorized_applications')
  | null_resource.chef_server_test (remote-exec):        expected "/id/auth/failure?message=invalid_credentials&strategy=chef" to end with "/id/oauth/authorized_applications"
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:101:in `block (5 levels) in <top (required)>'
  |  
  | null_resource.chef_server_test (remote-exec):   5) oc_id API /id/profile#show shows the profile
  | null_resource.chef_server_test (remote-exec):      Failure/Error: cookie = response.headers[:set_cookie][1].split(";").first
  | null_resource.chef_server_test (remote-exec):
  | null_resource.chef_server_test (remote-exec):      NoMethodError:
  | null_resource.chef_server_test (remote-exec):        undefined method `split' for nil:NilClass
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:64:in `signin'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:119:in `block (3 levels) in <top (required)>'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:9:in `block (2 levels) in <top (required)>'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:122:in `block (3 levels) in <top (required)>'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:125:in `block (3 levels) in <top (required)>'
  |  
  | null_resource.chef_server_test (remote-exec):   6) oc_id API /id/profile#update redirects to /id/profile and updates the user record
  | null_resource.chef_server_test (remote-exec):      Failure/Error: cookie = response.headers[:set_cookie][1].split(";").first
  | null_resource.chef_server_test (remote-exec):
  | null_resource.chef_server_test (remote-exec):      NoMethodError:
  | null_resource.chef_server_test (remote-exec):        undefined method `split' for nil:NilClass
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:64:in `signin'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:138:in `block (3 levels) in <top (required)>'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:9:in `block (2 levels) in <top (required)>'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:146:in `block (3 levels) in <top (required)>'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:153:in `block (3 levels) in <top (required)>'
  |  
  | null_resource.chef_server_test (remote-exec):   7) oc_id API /id/profile#password redirects to /id/profile and updates the user's password
  | null_resource.chef_server_test (remote-exec):      Failure/Error: cookie = response.headers[:set_cookie][1].split(";").first
  | null_resource.chef_server_test (remote-exec):
  | null_resource.chef_server_test (remote-exec):      NoMethodError:
  | null_resource.chef_server_test (remote-exec):        undefined method `split' for nil:NilClass
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:64:in `signin'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:176:in `block (3 levels) in <top (required)>'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:9:in `block (2 levels) in <top (required)>'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:184:in `block (3 levels) in <top (required)>'
  | null_resource.chef_server_test (remote-exec):      # ./spec/api/oc_id_spec.rb:187:in `block (3 levels) in <top (required)>'
  |  
  | null_resource.chef_server_test (remote-exec): Finished in 33 minutes 1 second (files took 5.3 seconds to load)
  | null_resource.chef_server_test (remote-exec): 5171 examples, 7 failures, 129 pending
  |  
  | null_resource.chef_server_test (remote-exec): Failed examples:
  |  
  | null_resource.chef_server_test (remote-exec): rspec ./spec/api/oc_id_spec.rb:45 # oc_id API status endpoint GET /id/v1/status returns 200
  | null_resource.chef_server_test (remote-exec): rspec ./spec/api/oc_id_spec.rb:76 # oc_id API key reset returns a non-zero file
  | null_resource.chef_server_test (remote-exec): rspec ./spec/api/oc_id_spec.rb:81 # oc_id API key reset returns a valid key
  | null_resource.chef_server_test (remote-exec): rspec ./spec/api/oc_id_spec.rb:99 # oc_id API signin with correct password POST /id/auth/chef/callback redirects us to authorized applications
  | null_resource.chef_server_test (remote-exec): rspec ./spec/api/oc_id_spec.rb:124 # oc_id API /id/profile#show shows the profile
  | null_resource.chef_server_test (remote-exec): rspec ./spec/api/oc_id_spec.rb:152 # oc_id API /id/profile#update redirects to /id/profile and updates the user record
  | null_resource.chef_server_test (remote-exec): rspec ./spec/api/oc_id_spec.rb:186 # oc_id API /id/profile#password redirects to /id/profile and updates the user's password
```

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-server/pull/2025
https://github.com/chef/chef_authn/pull/39
