### ISSUE TITLE
[terraform] external_postgres fails on ipv6

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#1956]
```

null_resource.chef_server_config (remote-exec):
--
  | null_resource.chef_server_config (remote-exec):   ================================================================================
  | null_resource.chef_server_config (remote-exec):   Recipe Compile Error in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb
  | null_resource.chef_server_config (remote-exec):   ================================================================================
  |  
  | null_resource.chef_server_config (remote-exec):   PG::ConnectionBad
  | null_resource.chef_server_config (remote-exec):   -----------------
  | null_resource.chef_server_config (remote-exec):   could not connect to server: Connection timed out
  | null_resource.chef_server_config (remote-exec):   	Is the server running on host "2600:1f14:996:f01:da84:f00d:aadd:2c64" and accepting
  | null_resource.chef_server_config (remote-exec):   	TCP/IP connections on port 5432?
  | null_resource.chef_server_config (remote-exec):
  | null_resource.chef_server_config (remote-exec):   Cookbook Trace:
  | null_resource.chef_server_config (remote-exec):   ---------------
  | null_resource.chef_server_config (remote-exec):     /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:22:in `initialize'
  | null_resource.chef_server_config (remote-exec):     /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:22:in `new'
  | null_resource.chef_server_config (remote-exec):     /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:22:in `with_connection'
  | null_resource.chef_server_config (remote-exec):     /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/preflight_checks.rb:93:in `connect_as'
  | null_resource.chef_server_config (remote-exec):     /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/preflight_bootstrap_validator.rb:95:in `pivotal_user_exists?'
  | null_resource.chef_server_config (remote-exec):     /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/preflight_bootstrap_validator.rb:42:in `run!'
  | null_resource.chef_server_config (remote-exec):     /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/preflight_checks.rb:140:in `run!'
  | null_resource.chef_server_config (remote-exec):     /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/config.rb:94:in `from_file'
  | null_resource.chef_server_config (remote-exec):     /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:51:in `from_file'
  |  
  | null_resource.chef_server_config (remote-exec):   Relevant File Content:
  | null_resource.chef_server_config (remote-exec):   ----------------------
  | null_resource.chef_server_config (remote-exec):   /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:
  | null_resource.chef_server_config (remote-exec):
  | null_resource.chef_server_config (remote-exec):    15:        retries = opts['retries'] \|\| 1
  | null_resource.chef_server_config (remote-exec):    16:      else
  | null_resource.chef_server_config (remote-exec):    17:        silent = false
  | null_resource.chef_server_config (remote-exec):    18:        retries = opts['retries'] \|\| 5
  | null_resource.chef_server_config (remote-exec):    19:      end
  | null_resource.chef_server_config (remote-exec):    20:      max_retries = retries
  | null_resource.chef_server_config (remote-exec):    21:      begin
  | null_resource.chef_server_config (remote-exec):    22>>       connection = PG::Connection.open('user' =>     postgres['db_connection_superuser'] \|\| postgres['db_superuser'],
  | null_resource.chef_server_config (remote-exec):    23:                                         'host' =>     postgres['vip'],
  | null_resource.chef_server_config (remote-exec):    24:                                         'password' => postgres['db_superuser_password'],
  | null_resource.chef_server_config (remote-exec):    25:                                         'port' =>     postgres['port'],
  | null_resource.chef_server_config (remote-exec):    26:                                         'sslmode' =>  postgres['sslmode'],
  | null_resource.chef_server_config (remote-exec):    27:                                         'dbname' =>   database)
  | null_resource.chef_server_config (remote-exec):    28:      rescue => e
  | null_resource.chef_server_config (remote-exec):    29:        if retries > 0
  | null_resource.chef_server_config (remote-exec):    30:          sleep_time = 2**((max_retries - retries))
  | null_resource.chef_server_config (remote-exec):    31:          retries -= 1
  | null_resource.chef_server_config (remote-exec):
  | null_resource.chef_server_config (remote-exec):   System Info:
  | null_resource.chef_server_config (remote-exec):   ------------
  | null_resource.chef_server_config (remote-exec):   chef_version=15.8.23
  | null_resource.chef_server_config (remote-exec):   platform=redhat
  | null_resource.chef_server_config (remote-exec):   platform_version=6.10
  | null_resource.chef_server_config (remote-exec):   ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
  | null_resource.chef_server_config (remote-exec):   program_name=/opt/opscode/embedded/bin/chef-client
  | null_resource.chef_server_config (remote-exec):   executable=/opt/opscode/embedded/bin/chef-client
  |  
  | null_resource.chef_server_config (remote-exec):
  | null_resource.chef_server_config (remote-exec):   Running handlers:
  | null_resource.chef_server_config (remote-exec):   Running handlers complete
  | null_resource.chef_server_config (remote-exec):   Chef Infra Client failed. 1 resources updated in 06 minutes 54 seconds
  | null_resource.chef_server_config (remote-exec): [2020-04-07T20:13:56+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
  | null_resource.chef_server_config (remote-exec): [2020-04-07T20:13:56+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
  | null_resource.chef_server_config (remote-exec): [2020-04-07T20:13:56+00:00] FATAL: PG::ConnectionBad: could not connect to server: Connection timed out
  | null_resource.chef_server_config (remote-exec): 	Is the server running on host "2600:1f14:996:f01:da84:f00d:aadd:2c64" and accepting
  | null_resource.chef_server_config (remote-exec): 	TCP/IP connections on port 5432?


```

**Comment by PrajaktaPurohit** [comment]
Fixed: https://buildkite.com/chef/chef-chef-server-master-integration-test/builds/129
with: https://github.com/chef/chef-server/commit/9932d9e9e57213b38df3561a580f7ef0ad87b694
