### ISSUE TITLE
Failing FIPS tests on upgrade to chef 16.1.16 via chef-cli

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2033]
### Chef Server Version
13.2.44 onwards

### Platform Details
Tried on rhel-8

### Configuration
FIPS mode

### Scenario:
https://buildkite.com/chef/chef-chef-server-master-integration-test/builds/139 fails in FIPS tests.

### Steps to Reproduce:
Create an instance with omnibus-fips-ipv4-rhel-8. That will cause cookbook upload tests to fail.

Tracing this further down:
Chef Infra server uses different version fo ruby:
omnibus_overrides: chef-15.8.23
oc-id: chef-12.22.5
chefspec -> chef-cli : chef-16.1.16

Chefspec pulls chef-cli: https://github.com/chefspec/chefspec/blob/master/chefspec.gemspec#L27
chef-cli pulls the latest chef: https://github.com/chef/chef-cli/blob/master/chef-cli.gemspec#L46
(16.1.16 in this case) 

It fails with:
```
[root@ip-10-0-19-207 ec2-user]# /opt/opscode/embedded/service/gem/ruby/2.6.0/bin/knife cookbook upload packagecloud -VV
INFO: Using configuration from /home/ec2-user/.chef/knife.rb
DEBUG: FIPS mode is enabled.
DEBUG: No chefignore file found. No files will be ignored!
DEBUG: No chefignore file found. No files will be ignored!
DEBUG: No chefignore file found. No files will be ignored!
Traceback (most recent call last):
	31: from /opt/opscode/embedded/service/gem/ruby/2.6.0/bin/knife:23:in `<main>'
	30: from /opt/opscode/embedded/service/gem/ruby/2.6.0/bin/knife:23:in `load'
	29: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/bin/knife:24:in `<top (required)>'
	28: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/application/knife.rb:163:in `run'
	27: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/knife.rb:229:in `run'
	26: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/knife.rb:489:in `run_with_pretty_exceptions'
	25: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/local_mode.rb:42:in `with_server_connectivity'
# Copyright:: Copyright (c) Chef Software Inc.
# Copyright:: Copyright 2009-2016, Daniel DeLeo
	24: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/knife.rb:490:in `block in run_with_pretty_exceptions'
	23: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/knife/cookbook_upload.rb:98:in `run'
	22: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/knife/cookbook_upload.rb:182:in `cookbooks_to_upload'
	21: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/knife/cookbook_upload.rb:182:in `each'
	20: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/knife/cookbook_upload.rb:185:in `block in cookbooks_to_upload'
	19: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/cookbook_loader.rb:107:in `[]'
	18: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/cookbook_loader.rb:100:in `load_cookbook'
	17: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/cookbook/cookbook_version_loader.rb:107:in `cookbook_version'
	16: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/cookbook/cookbook_version_loader.rb:107:in `tap'
	15: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/cookbook/cookbook_version_loader.rb:109:in `block in cookbook_version'
	14: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/cookbook_version.rb:166:in `metadata='
	13: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/cookbook/metadata.rb:392:in `recipes_from_cookbook_version'
	12: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/cookbook_version.rb:189:in `fully_qualified_recipe_names'
	11: from /opt/opscode/embedded/lib/ruby/2.6.0/forwardable.rb:230:in `files_for'
	10: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/cookbook_manifest.rb:176:in `files_for'
	 9: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/cookbook_manifest.rb:104:in `manifest'
	 8: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/cookbook_manifest.rb:235:in `generate_manifest'
	 7: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/cookbook_manifest.rb:235:in `each'
	 6: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/cookbook_manifest.rb:240:in `block in generate_manifest'
	 5: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/cookbook_manifest.rb:309:in `checksum_cookbook_file'
	 4: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/cookbook_version.rb:80:in `checksum_cookbook_file'
	 3: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/digester.rb:49:in `generate_md5_checksum_for_file'
	 2: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/digester.rb:53:in `generate_md5_checksum_for_file'
	 1: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/digester.rb:53:in `new'
/opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-16.1.16/lib/chef/digester.rb:53:in `initialize': Digest initialization failed: disabled for fips (OpenSSL::Digest::DigestError)
```

The failing line is traced to https://github.com/chef/chef/commit/003fbc132935961e93667f11c3f45ce4914b83ac

On reverting that change on Chef Infra Server, the error gores away and cookbook upload is successful

```
[root@ip-10-0-19-207 ec2-user]# /opt/opscode/embedded/service/gem/ruby/2.6.0/bin/knife cookbook upload packagecloud -VV
INFO: Using configuration from /home/ec2-user/.chef/knife.rb
DEBUG: FIPS mode is enabled.
DEBUG: No chefignore file found. No files will be ignored!
DEBUG: No chefignore file found. No files will be ignored!
DEBUG: No chefignore file found. No files will be ignored!
Uploading packagecloud   [1.0.1]
INFO: Validating ruby files
INFO: Validating templates
INFO: Syntax OK
INFO: Saving packagecloud
INFO: Uploading files
INFO: Upload complete!
Uploaded 1 cookbook.
```

On close examination though, this is not reproducible in irb:

```
irb(main):002:0> require 'openssl'
=> true
irb(main):003:0> OpenSSL::Digest.new("MD5")
=> #<OpenSSL::Digest: d41d8cd98f00b204e9800998ecf8427e>
irb(main):004:0> OpenSSL::Digest::MD5.new
=> #<OpenSSL::Digest::MD5: d41d8cd98f00b204e9800998ecf8427e>
irb(main):002:0> RUBY_VERSION
=> "2.6.5"
```

Versions as seen on the system:

```
[root@ip-10-0-19-207 ec2-user]# ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
[root@ip-10-0-19-207 ec2-user]# irb --version
irb 1.0.0 (2018-12-18)
[root@ip-10-0-19-207 ec2-user]# which ruby
/opt/opscode/embedded/bin/ruby
[root@ip-10-0-19-207 ec2-user]# which irb
/opt/opscode/embedded/bin/irb
```

**Comment by PrajaktaPurohit** [comment]
Pinning has the following issues so far:
v16.0.251 - has the bcrypt change that we need, so pick a version after this,(https://github.com/chef/chef/commit/58e0958595bb7f673c442dd925961aa144dff6c0)
16.1.15 - Change that breaks FIPS (https://github.com/chef/chef/commit/003fbc132935961e93667f11c3f45ce4914b83ac) so we need a version before this
16.0.27 - Switches to bundler 2.1 from 1.17.3, causes a bundler in the build, so pick a build before this.

**Comment by PrajaktaPurohit** [comment]
Looks like https://github.com/chef/chef/blob/master/chef-config/lib/chef-config/config.rb#L1221-L1233 is what got the build to pass previously and the new chance in chef invalidates this.

It now fails in IRB:
```
[root@ip-10-0-27-157 ec2-user]# irb
irb(main):001:0> require 'openssl'
=> true
irb(main):002:0> OpenSSL.fips_mode = true
=> true
irb(main):003:0> OpenSSL::Digest::MD5.new
Traceback (most recent call last):
        7: from /opt/opscode/embedded/bin/irb:23:in `<main>'
        6: from /opt/opscode/embedded/bin/irb:23:in `load'
        5: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        4: from (irb):3
        3: from (irb):3:in `new'
        2: from /opt/opscode/embedded/lib/ruby/2.6.0/openssl/digest.rb:40:in `block (3 levels) in <class:Digest>'
        1: from /opt/opscode/embedded/lib/ruby/2.6.0/openssl/digest.rb:40:in `initialize'
OpenSSL::Digest::DigestError (Digest initialization failed: disabled for fips)
irb(main):004:0> OpenSSL::Digest.new("MD5")
Traceback (most recent call last):
        7: from /opt/opscode/embedded/bin/irb:23:in `<main>'
        6: from /opt/opscode/embedded/bin/irb:23:in `load'
        5: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        4: from (irb):4
        3: from (irb):4:in `rescue in irb_binding'
        2: from (irb):4:in `new'
        1: from (irb):4:in `initialize'
OpenSSL::Digest::DigestError (Digest initialization failed: disabled for fips)
```
