### ISSUE TITLE
chef-server reconfigure not working for RHEL7.8 

### ISSUE THREAD

**Issue by ravanelli** [chef/chef-server#2044]
### Chef Server Version
chef-server-core-12.19.31-1.el7.x86_64
chef-manage-2.5.16-1.el7

### Platform Details
Baremetal x86
Kernel 3.10.0-1127.10.1.el7.x86_64
RHEL 7.8

### Scenario:
I got an issue running chef-server, the login interface stopped working,  I got 400 error after the login attempt, the knife was not working neither, it happened after a few package updates including the Kernel.

I did a reinstall removing all configs files, also used chef-server-ctl cleanse, then the chef-server-ctl reconfigure didn't work.

**I tried to update it to chef-server-core-13.2.0-1.el7.x86_64, and got the same issues.** 

[What you are trying to achieve and you can't?]
chef-server-ctl reconfigure done

### Actual Result:

**sudo chef-server-ctl reconfigure**
================================================================================
    Error executing action `restart` on resource 'runit_service[redis_lb]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/redis_lb ----
    STDOUT: fail: /opt/opscode/service/redis_lb: runsv not running
    STDERR:
    ---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/redis_lb ----
    Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/redis_lb returned 1

================================================================================
    Error executing action `restart` on resource 'runit_service[nginx]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
    STDOUT: fail: /opt/opscode/service/nginx: unable to change to service directory: file does not exist
    STDERR:
    ---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
    Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx returned 1

================================================================================
    Error executing action `run` on resource 'execute[set initial migration level]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of cd /opt/opscode/embedded/service/partybus && ./bin/partybus init ----
    STDOUT:
    STDERR: /opt/opscode/embedded/service/gem/ruby/2.5.0/gems/sequel-3.34.1/lib/sequel/database/schema_generator.rb:19: warning: constant ::Fixnum is deprecated
    /opt/opscode/embedded/service/gem/ruby/2.5.0/gems/sequel-3.34.1/lib/sequel/database/schema_generator.rb:19: warning: constant ::Bignum is deprecated
    ./bin/partybus:11:in `require': cannot load such file -- /opt/opscode/embedded/service/partybus/config.rb (LoadError)
    	from ./bin/partybus:11:in `<main>'
    ---- End output of cd /opt/opscode/embedded/service/partybus && ./bin/partybus init ----
    Ran cd /opt/opscode/embedded/service/partybus && ./bin/partybus init returned 1

**Full /var/opt/opscode/local-mode-cache/chef-stacktrace.out**

```
Generated at 2020-06-25 09:39:07 -0400
Chef::Exceptions::MultipleFailures: Chef::Exceptions::MultipleFailures
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout.rb:297:in `invalid!'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout.rb:284:in `error!'
/var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:174:in `tap'
/var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:174:in `safe_sv_shellout!'
/var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:202:in `restart_service'
/var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/provider_runit_service.rb:330:in `block in <class:RunitService>'
(eval):2:in `block in action_restart'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider.rb:236:in `instance_eval'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider.rb:236:in `compile_and_converge_action'
(eval):2:in `action_restart'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider.rb:182:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource.rb:578:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:70:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:98:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:98:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
ck'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:97:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:720:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:715:in `catch'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:715:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:754:in `converge_and_save'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:286:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:261:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application/client.rb:444:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:66:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/bin/chef-client:25:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:23:in `load'
/opt/opscode/embedded/bin/chef-client:23:in `<main>'
>>>> Caused by Mixlib::ShellOut::ShellCommandFailed: runit_service[redis_lb] (private-chef::redis_lb line 83) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/redis_lb ----
STDOUT: fail: /opt/opscode/service/redis_lb: runsv not running
STDERR:
---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/redis_lb ----
Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/redis_lb returned 1
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout.rb:297:in `invalid!'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout.rb:284:in `error!'
/var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:174:in `tap'
/var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:174:in `safe_sv_shellout!'
/var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:202:in `restart_service'
/var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/provider_runit_service.rb:330:in `block in <class:RunitService>'
(eval):2:in `block in action_restart'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider.rb:236:in `instance_eval'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider.rb:236:in `compile_and_converge_action'
(eval):2:in `action_restart'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider.rb:182:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource.rb:578:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:70:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:98:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:98:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:97:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:720:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:715:in `catch'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:715:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:754:in `converge_and_save'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:286:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:261:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application/client.rb:444:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:66:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/bin/chef-client:25:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:23:in `load'
/opt/opscode/embedded/bin/chef-client:23:in `<main>'
>>>> Caused by Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/redis_lb ----
STDOUT: fail: /opt/opscode/service/redis_lb: runsv not running
STDERR:
---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/redis_lb ----
Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/redis_lb returned 1
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout.rb:297:in `invalid!'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout.rb:284:in `error!'
/var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:174:in `tap'
/var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:174:in `safe_sv_shellout!'
/var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:202:in `restart_service'
/var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/provider_runit_service.rb:330:in `block in <class:RunitService>'
(eval):2:in `block in action_restart'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider.rb:236:in `instance_eval'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider.rb:236:in `compile_and_converge_action'
(eval):2:in `action_restart'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider.rb:182:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource.rb:578:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:70:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:98:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:98:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/runner.rb:97:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:720:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:715:in `catch'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:715:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:754:in `converge_and_save'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:286:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:261:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application/client.rb:444:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:66:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/bin/chef-client:25:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:23:in `load'
/opt/opscode/embedded/bin/chef-client:23:in `<main>'

```

**Comment by PrajaktaPurohit** [comment]
@ravanelli ,Sorry to  see you are running into this  issue with the install. Looking at the informations  provided, no issue  jumps out at  us currently. We would  request  you to please try a fresh install on a new box and let us know if you  still see an issue. We have not seen  this in the testing done with our test matrix as a part of the 13.2.0 release.

@PrajaktaPurohit : Test with RHEL 7.8 on an upgrade after running `chef-server-ctl cleanse`

**Comment by ravanelli** [comment]
@PrajaktaPurohit Thanks for the answer. I think we can close this issue.
