### ISSUE TITLE
[dev-vm] chef-server omnibus vm broken unable to build locally.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2466]
As a Chef Infra Server dev I would like to be able to build omnibus packages locally.

currently 
# cd chef-server/omnibus
# kitchen converge ubuntu-1804
fails with 
```
 Transferring files to <default-ubuntu-1804>
       +---------------------------------------------+
       ✔ 2 product licenses accepted.
       +---------------------------------------------+
       Starting Chef Infra Client, version 17.0.242
       Patents: https://www.chef.io/patents
       Creating a new client identity for default-ubuntu-1804 using the validator key.
       resolving cookbooks for run list: ["apt::default", "omnibus::default", "zip"]
       Synchronizing Cookbooks:
         - chef-sugar (5.1.8)
         - omnibus (5.7.2)
         - apt (7.2.0)
         - build-essential (8.2.1)
         - remote_install (2.0.0)
         - zip (1.1.0)
         - git (10.0.0)
         - wix (5.0.0)
         - chef-ingredient (3.1.2)
         - homebrew (5.0.8)
         - seven_zip (3.1.2)
         - mingw (2.1.0)
         - windows (6.0.1)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       [2021-05-03T20:44:21+00:00] WARN: Resource windows_user_privilege built into Chef Infra Client is being overridden by the resource from a cookbook. Please upgrade your cookbook or remove the cookbook from your run_list.
       [2021-05-03T20:44:21+00:00] WARN: chef-sugar::default no longer needs to be included in your runlist. Instead simply depend on the chef-sugar cookbook and the gem will be installed and loaded automatically.

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/omnibus/recipes/default.rb
       ================================================================================

       NoMethodError
       -------------
       undefined method `chef_ingredient' for cookbook: omnibus, recipe: _omnibus_toolchain :Chef::Recipe

       Cookbook Trace: (most recent call first)
       ----------------------------------------
         /tmp/kitchen/cache/cookbooks/omnibus/recipes/_omnibus_toolchain.rb:22:in `from_file'
         /tmp/kitchen/cache/cookbooks/omnibus/recipes/_user.rb:24:in `from_file'
         /tmp/kitchen/cache/cookbooks/omnibus/recipes/_common.rb:33:in `from_file'
         /tmp/kitchen/cache/cookbooks/omnibus/recipes/default.rb:21:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/omnibus/recipes/_omnibus_toolchain.rb:

        15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        16:  # See the License for the specific language governing permissions and
        17:  # limitations under the License.
        18:  #
        19:
        20:  arch = (windows_arch_i386? || i386?) ? 'i386' : node['kernel']['machine']
        21:
        22>> chef_ingredient node['omnibus']['toolchain_name'] do
        23:    version node['omnibus']['toolchain_version']
        24:    channel node['omnibus']['toolchain_channel'].to_sym
        25:    architecture arch
        26:    platform_version_compatibility_mode true
        27:    action(windows? ? :install : :upgrade)
        28:  end
        29:
        30:  omnibus_env['OMNIBUS_TOOLCHAIN_INSTALL_DIR'] << toolchain_install_dir
        31:  omnibus_env['SSL_CERT_FILE'] << windows_safe_path_join(toolchain_install_dir, 'embedded', 'ssl', 'certs', 'cacert.pem')

       System Info:
       ------------
       chef_version=17.0.242
       platform=ubuntu
       platform_version=18.04
       ruby=ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
       program_name=/opt/chef/bin/chef-client
       executable=/opt/chef/bin/chef-client


       Running handlers:
       [2021-05-03T20:44:21+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2021-05-03T20:44:21+00:00] ERROR: Exception handlers complete
       Chef Infra Client failed. 0 resources updated in 03 seconds
```

Acceptance criteria:
Dev is able to build omnibus packages locally.

**Comment by tas50** [comment]
We probably want to remove the omnibus cookbook which isn't maintained anymore and instead use the omnibus-toolchain like our builders/testers do

**Comment by PrajaktaPurohit** [comment]
I needed to upgrade the versions of the software involved to get this working.

**Comment by tas50** [comment]
This was fixed in https://github.com/chef/chef-server/pull/3149
