### ISSUE TITLE
[automate] Chef Infra Server 14.2 update in automate currently failing.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2467]
As a Chef Infra Server developer I would like to update the latest stable release of Chef Infra Server in Automate.

It currently fails with: 
```
1) Testing Status API with config Status API GET /_status should respond with valid health data
     Failure/Error: let (:config) { JSON.parse(IO.read("/etc/opscode/chef-server-running.json"))['private_chef'] }

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /etc/opscode/chef-server-running.json
     # /hab/pkgs/chef/chef-server-ctl/14.3.14/20210422123134/oc-chef-pedant/spec/api/status_spec.rb:3:in `read'
     # /hab/pkgs/chef/chef-server-ctl/14.3.14/20210422123134/oc-chef-pedant/spec/api/status_spec.rb:3:in `block (2 levels) in <top (required)>'
     # /hab/pkgs/chef/chef-server-ctl/14.3.14/20210422123134/oc-chef-pedant/spec/api/status_spec.rb:9:in `block (3 levels) in <top (required)>'

Finished in 1 minute 11.5 seconds (files took 4.53 seconds to load)
170 examples, 1 failure, 2 pending
```

The status endpoint we added in 14.2 looks for the /etc/opscode/chef-server-running.json file which is not present in the habitat installed chef-server.

[Place holder for some background and info]

Acceptance Criteria:
- Automate can get the latest version of Chef Infra Server.

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/automate/pull/5250 and https://github.com/chef/automate/pull/5213
