### ISSUE TITLE
Dozens of Chef warnings on reconfigure

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#265]
On the latest nighties, we are seeing dozens of warnings again during reconfigure.  Here is a breakdown:

```
root@api:~# chef-server-ctl reconfigure 2>&1 | grep WARN | awk '{ $1=""; $2=""; print}' | sort | uniq -c | sort -nr
     42   This will no longer work in Chef 13: you must use 'provides' to provide DSL.
     17   Class Chef::Resource::RunitService does not declare 'provides :runit_service'.
      8   In Chef 13, this will break: you must call provides to mark the names you provide, even if you also override provides? yourself.
      6   Using an LWRP by its name (PrivateChefPgUser) directly is no longer supported in Chef 12 and will be removed. Use Chef::Resource.resource_for_node(node, name) instead.
      6   Class Chef::Resource::PrivateChefPgUser does not declare 'provides :private_chef_pg_user'.
      5   Using an LWRP by its name (PrivateChefPgUserTableAccess) directly is no longer supported in Chef 12 and will be removed. Use Chef::Resource.resource_for_node(node, name) instead.
      5   Using an LWRP by its name (PrivateChefPgDatabase) directly is no longer supported in Chef 12 and will be removed. Use Chef::Resource.resource_for_node(node, name) instead.
      5   Class Chef::Resource::PrivateChefPgUserTableAccess does not declare 'provides :private_chef_pg_user_table_access'.
      5   Class Chef::Resource::PrivateChefPgDatabase does not declare 'provides :private_chef_pg_database'.
      3   No analytics oc-id-application present. Skipping
      2   Using an LWRP by its name (PrivateChefPgUpgrade) directly is no longer supported in Chef 12 and will be removed. Use Chef::Resource.resource_for_node(node, name) instead.
      2   Using an LWRP by its name (PrivateChefPgCluster) directly is no longer supported in Chef 12 and will be removed. Use Chef::Resource.resource_for_node(node, name) instead.
      2   Using an LWRP by its name (PrivateChefKeepalivedSafemode) directly is no longer supported in Chef 12 and will be removed. Use Chef::Resource.resource_for_node(node, name) instead.
      2   Class Chef::Resource::PrivateChefPgUpgrade does not declare 'provides :private_chef_pg_upgrade'.
      2   Class Chef::Resource::PrivateChefPgCluster does not declare 'provides :private_chef_pg_cluster'.
      2   Class Chef::Resource::PrivateChefKeepalivedSafemode does not declare 'provides :private_chef_keepalived_safemode'.
      2   Class Chef::Resource::ChefRun does not declare 'provides :chef_run'.
      1   Previous runit_service[redis_lb]: /opt/opscode/embedded/cookbooks/cache/cookbooks/enterprise/definitions/component_runit_service.rb:37:in `block in from_file'
      1   Previous directory[/var/opt/opscode/nginx/etc/addon.d]: /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/oc_id.rb:173:in `from_file'
      1   'path' attribute of 'execute' is not used by any provider in Chef 11 and Chef 12. Use 'environment' attribute to configure 'PATH'. This attribute will be removed in Chef 13.
      1   Current runit_service[redis_lb]: /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/redis_lb.rb:83:in `from_file'
      1   Current directory[/var/opt/opscode/nginx/etc/addon.d]: /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/nginx.rb:33:in `block in from_file'
      1   Cloning resource attributes for runit_service[redis_lb] from prior resource (CHEF-3694)
      1   Cloning resource attributes for directory[/var/opt/opscode/nginx/etc/addon.d] from prior resource (CHEF-3694)
      1   Class Chef::Provider::ChefRun does not declare 'provides :chef_run'.
      1   #<Class:0x00000004a25fb8> is marked as providing DSL private_chef_keepalived_safemode, but provides :private_chef_keepalived_safemode was never called!
      1   #<Class:0x00000004a0f6f0> is marked as providing DSL private_chef_pg_cluster, but provides :private_chef_pg_cluster was never called!
      1   #<Class:0x00000004a0d8a0> is marked as providing DSL private_chef_pg_database, but provides :private_chef_pg_database was never called!
      1   #<Class:0x000000049fe760> is marked as providing DSL private_chef_pg_upgrade, but provides :private_chef_pg_upgrade was never called!
      1   #<Class:0x000000049fc488> is marked as providing DSL private_chef_pg_user, but provides :private_chef_pg_user was never called!
      1   #<Class:0x000000049f5958> is marked as providing DSL private_chef_pg_user_table_access, but provides :private_chef_pg_user_table_access was never called!
      1   Chef::Resource::RunitService is marked as providing DSL runit_service, but provides :runit_service was never called!
      1   Chef::Resource::ChefRun is marked as providing DSL chef_run, but provides :chef_run was never called!
```

**Comment by stevendanna** [comment]
It looks like the situation has improved in the most recent RC:

```
root@api:~# chef-server-ctl reconfigure 2>&1 | grep WARN
[2015-06-15T09:46:00+01:00] WARN: 'path' attribute of 'execute' is not used by any provider in Chef 11 and Chef 12. Use 'environment' attribute to configure 'PATH'. This attribute will be removed in Chef 13.
[2015-06-15T09:46:00+01:00] WARN: Cloning resource attributes for runit_service[redis_lb] from prior resource (CHEF-3694)
[2015-06-15T09:46:00+01:00] WARN: Previous runit_service[redis_lb]: /opt/opscode/embedded/cookbooks/cache/cookbooks/enterprise/definitions/component_runit_service.rb:37:in `block in from_file'
[2015-06-15T09:46:00+01:00] WARN: Current  runit_service[redis_lb]: /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/redis_lb.rb:83:in `from_file'
[2015-06-15T09:46:00+01:00] WARN: Cloning resource attributes for directory[/var/opt/opscode/nginx/etc/addon.d] from prior resource (CHEF-3694)
[2015-06-15T09:46:00+01:00] WARN: Previous directory[/var/opt/opscode/nginx/etc/addon.d]: /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/oc_id.rb:173:in `from_file'
[2015-06-15T09:46:00+01:00] WARN: Current  directory[/var/opt/opscode/nginx/etc/addon.d]: /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/nginx.rb:33:in `block in from_file'
[2015-06-15T09:46:00+01:00] WARN: Class Chef::Provider::ChefRun does not declare 'provides :chef_run'.
[2015-06-15T09:46:00+01:00] WARN: This will no longer work in Chef 13: you must use 'provides' to provide DSL.
[2015-06-15T09:46:12+01:00] WARN: No analytics oc-id-application present. Skipping
[2015-06-15T09:46:12+01:00] WARN: No analytics oc-id-application present. Skipping
[2015-06-15T09:46:12+01:00] WARN: No analytics oc-id-application present. Skipping
```

**Comment by jjasghar** [comment]
Doing a fresh install of the the chef server today (2016-12-07) I saw this at the end of my `chef-server-ctl reconfigure`:

```
Running handlers:
Running handlers complete

Deprecated features used!
  node.set is deprecated and will be removed in Chef 14, please use node.default/node.override (or node.normal only if you really need persistence) at 7 locations:
    - /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/private_keys.rb:31:in `from_file'
    - /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:21:in `from_file'
    - /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:22:in `from_file'
    - /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:23:in `from_file'
    - /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:24:in `from_file'
    - /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:25:in `from_file'
    - /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:26:in `from_file'
   See https://docs.chef.io/deprecations_attributes.html for further details.
  An attempt was made to change sysvinit_id from "SV" to nil by calling sysvinit_id(nil). In Chef 12, this does a get rather than a set. In Chef 13, this will change to set the value to nil. at 1 location:
    - /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:31:in `block in from_file'
   See https://docs.chef.io/deprecations_custom_resource_cleanups.html for further details.
  Cloning resource attributes for runit_service[redis_lb] from prior resource
Previous runit_service[redis_lb]: /var/opt/opscode/local-mode-cache/cookbooks/enterprise/definitions/component_runit_service.rb:37:in `block in from_file'
Current  runit_service[redis_lb]: /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/redis_lb.rb:83:in `from_file' at 1 location:
    - /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/redis_lb.rb:83:in `from_file'
   See https://docs.chef.io/deprecations_resource_cloning.html for further details.
  Cloning resource attributes for directory[/var/opt/opscode/nginx/etc/addon.d] from prior resource
Previous directory[/var/opt/opscode/nginx/etc/addon.d]: /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/oc_id.rb:173:in `from_file'
Current  directory[/var/opt/opscode/nginx/etc/addon.d]: /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/nginx.rb:35:in `block in from_file' at 1 location:
    - /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/nginx.rb:35:in `block in from_file'
   See https://docs.chef.io/deprecations_resource_cloning.html for further details.

Chef Client finished, 396/470 resources updated in 03 minutes 25 seconds
Chef Server Reconfigured!
```

From a user experience this seems not very delightful.

**Comment by stevendanna** [comment]
The fight continues unfortunately: https://github.com/chef/chef-server/issues/1243

I think we should also consider writing a custom output formatter that hides deprecation warnings outside of some "Development mode".  From the perspective of `chef-server-ctl` these warnings are not actionable for our users.

**Comment by PrajaktaPurohit** [comment]
Closing since the work is done in the PR linked above. Can reopen if needed.
