### ISSUE TITLE
Errors upgrading to Chef Infra Server 14.6.32

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2676]
When installing Chef Infra Server 14.6.32 from scratch, I was having errors related to the oc-id integration with my Supermarket server.

I've created a paired down config with Test Kitchen to try and isolate the error.

I used the example format from https://docs.chef.io/server/config_rb_server_optional_settings/#oc-id-14

/etc/opscode/chef-server.rb looks like this:

```

# This file is managed by Chef. Manual modifications will be overwritten.
fqdn 'defaultcentos79-abc-xyz-123'
api_fqdn 'chef.vagrant.dev.local'
notification_email 'icare@company.com'
default_orgname 'videocloud'

license['nodes'] = 99999

estatsd['enable'] = true
estatsd['vip'] = '127.0.0.1'
estatsd['port'] = 8125
estatsd['protocol'] = 'statsd'
oc_id['applications'] ||= {}
oc_id['applications']['supermarket'] = {
'redirect_uri' => 'https://supermarket.mycompany.com/auth/chef_oauth2/callback',
}

rabbitmq['enable'] = false
rabbitmq['management_enabled'] = false
rabbitmq['queue_length_monitor_enabled'] = false
opscode_expander['enable'] = false
dark_launch['actions'] = false

```

And when I run `chef-server-ctl reconfigure` I get this error:

```

Recipe: private-chef::oc_id
* oc_id_application[supermarket] action create

================================================================================
Error executing action `create` on resource 'oc_id_application[supermarket]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of veil-env-helper --use-file -s chef-server.webui_key -s oc_id.sql_password -s oc_id.secret_key_base -- bin/rails runner -e production 'app = Doorkeeper::Application.find_or_create_by(:name => "supermarket");
app.update_attributes(:redirect_uri => "https://supermarket.mycompany.com/auth/chef_oauth2/callback");
puts app.to_json
' ----
STDOUT: W, [2021-07-20T19:00:20.294254 #1126] WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /opt/opscode/embedded/service/gem/ruby/2.7.0/gems/omniauth-1.3.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
CHEF_SECRETS_FD=5
I, [2021-07-20T19:00:20.294903 #1126] INFO -- : Raven 3.1.2 configured not to capture errors: DSN not set
STDERR: Warning: the running version of Bundler (2.1.4) is older than the version that created the lockfile (2.2.19). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.2.19`.
Please specify a valid ruby command or the path of a script to run.
Run 'rails runner -h' for help.

undefined method `confidential' for #<Doorkeeper::Application:0x0000000008160eb0>
---- End output of veil-env-helper --use-file -s chef-server.webui_key -s oc_id.sql_password -s oc_id.secret_key_base -- bin/rails runner -e production 'app = Doorkeeper::Application.find_or_create_by(:name => "supermarket");
app.update_attributes(:redirect_uri => "https://supermarket.mycompany.com/auth/chef_oauth2/callback");
puts app.to_json
' ----
Ran veil-env-helper --use-file -s chef-server.webui_key -s oc_id.sql_password -s oc_id.secret_key_base -- bin/rails runner -e production 'app = Doorkeeper::Application.find_or_create_by(:name => "supermarket");
app.update_attributes(:redirect_uri => "https://supermarket.mycompany.com/auth/chef_oauth2/callback");
puts app.to_json
' returned 1

Cookbook Trace: (most recent call first)
----------------------------------------
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/resources/oc_id_application.rb:64:in `create!'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/resources/oc_id_application.rb:27:in `block (2 levels) in class_from_file'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/resources/oc_id_application.rb:26:in `block in class_from_file'

Resource Declaration:
---------------------
# In /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/oc_id.rb

205: oc_id_application name do
206: write_to_disk node['private_chef']['insecure_addon_compat']
207: redirect_uri app['redirect_uri']
208: only_if { is_data_master? }
209: end
210: end

Compiled Resource:
------------------
# Declared in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/oc_id.rb:205:in `block in from_file'

oc_id_application("supermarket") do
action [:create]
default_guard_interpreter :default
declared_type :oc_id_application
cookbook_name "private-chef"
recipe_name "oc_id"
write_to_disk true
redirect_uri "https://supermarket.mycompany.com/auth/chef_oauth2/callback"
only_if { #code block }
end

System Info:
------------
chef_version=16.13.16
platform=centos
platform_version=7.9.2009
ruby=ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]
program_name=/opt/opscode/embedded/bin/chef-client
executable=/opt/opscode/embedded/bin/chef-client

Running handlers:
Running handlers complete
Chef Infra Client failed. 21 resources updated in 25 seconds
[2021-07-20T19:00:21+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2021-07-20T19:00:21+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2021-07-20T19:00:21+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: oc_id_application[supermarket] (private-chef::oc_id line 205) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of veil-env-helper --use-file -s chef-server.webui_key -s oc_id.sql_password -s oc_id.secret_key_base -- bin/rails runner -e production 'app = Doorkeeper::Application.find_or_create_by(:name => "supermarket");
app.update_attributes(:redirect_uri => "https://supermarket.mycompany.com/auth/chef_oauth2/callback");
puts app.to_json
' ----
STDOUT: W, [2021-07-20T19:00:20.294254 #1126] WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /opt/opscode/embedded/service/gem/ruby/2.7.0/gems/omniauth-1.3.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
CHEF_SECRETS_FD=5
I, [2021-07-20T19:00:20.294903 #1126] INFO -- : Raven 3.1.2 configured not to capture errors: DSN not set
STDERR: Warning: the running version of Bundler (2.1.4) is older than the version that created the lockfile (2.2.19). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.2.19`.
Please specify a valid ruby command or the path of a script to run.
Run 'rails runner -h' for help.

undefined method `confidential' for #<Doorkeeper::Application:0x0000000008160eb0>
---- End output of veil-env-helper --use-file -s chef-server.webui_key -s oc_id.sql_password -s oc_id.secret_key_base -- bin/rails runner -e production 'app = Doorkeeper::Application.find_or_create_by(:name => "supermarket");
app.update_attributes(:redirect_uri => "https://supermarket.mycompany.com/auth/chef_oauth2/callback");
puts app.to_json
' ----
Ran veil-env-helper --use-file -s chef-server.webui_key -s oc_id.sql_password -s oc_id.secret_key_base -- bin/rails runner -e production 'app = Doorkeeper::Application.find_or_create_by(:name => "supermarket");
app.update_attributes(:redirect_uri => "https://supermarket.mycompany.com/auth/chef_oauth2/callback");
puts app.to_json
' returned 1

```

This looks like a bug to me, but maybe I'm doing something out of the ordinary.  Can you see if you can reproduce this error?

**To Reproduce**

1. Start a CentOS 7.9 machine.
2. Download and install chef-server

```

curl -L -O https://packages.chef.io/stable/el/7/chef-server-core-14.6.32-1.el7.x86_64.rpm
yum install chef-server-core-14.6.32-1.el7.x86_64.rpm

```

 

3. edit /etc/opscode/chef-server.rb

 

```

fqdn 'chef.vagrant.dev.local'
api_fqdn 'chef.vagrant.dev.local'
notification_email 'foo@bar.com'

license['nodes'] = 99999

estatsd['enable'] = true
estatsd['vip'] = '127.0.0.1'
estatsd['port'] = 8125
estatsd['protocol'] = 'statsd'
oc_id['applications'] ||= {}
oc_id['applications']['supermarket'] = {
'redirect_uri' => 'https://supermarket.mycompany.com/auth/chef_oauth2/callback',
}

rabbitmq['enable'] = false
rabbitmq['management_enabled'] = false
rabbitmq['queue_length_monitor_enabled'] = false
opscode_expander['enable'] = false
dark_launch['actions'] = false

```

 

4. run `chef-server-ctl reconfigure`

 

And I get the error 

**Expected behavior**

Chef Reconfigure should works successfulyl as per something like this:

Chef Infra Client finished, 413/884 resources updated in 02 minutes 05 seconds
Chef Server Reconfigured!

**Actual behavior**

Reconfigure fails and produces error:

```

Recipe: private-chef::oc_id
* oc_id_application[supermarket] action create

================================================================================
Error executing action `create` on resource 'oc_id_application[supermarket]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of veil-env-helper --use-file -s chef-server.webui_key -s oc_id.sql_password -s oc_id.secret_key_base -- bin/rails runner -e production 'app = Doorkeeper::Application.find_or_create_by(:name => "supermarket");
app.update_attributes(:redirect_uri => "https://supermarket.mycompany.com/auth/chef_oauth2/callback");
puts app.to_json
' ----
STDOUT: W, [2021-07-20T19:00:20.294254 #1126] WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /opt/opscode/embedded/service/gem/ruby/2.7.0/gems/omniauth-1.3.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
CHEF_SECRETS_FD=5
I, [2021-07-20T19:00:20.294903 #1126] INFO -- : Raven 3.1.2 configured not to capture errors: DSN not set
STDERR: Warning: the running version of Bundler (2.1.4) is older than the version that created the lockfile (2.2.19). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.2.19`.
Please specify a valid ruby command or the path of a script to run.
Run 'rails runner -h' for help.

undefined method `confidential' for #<Doorkeeper::Application:0x0000000008160eb0>
---- End output of veil-env-helper --use-file -s chef-server.webui_key -s oc_id.sql_password -s oc_id.secret_key_base -- bin/rails runner -e production 'app = Doorkeeper::Application.find_or_create_by(:name => "supermarket");
app.update_attributes(:redirect_uri => "https://supermarket.mycompany.com/auth/chef_oauth2/callback");
puts app.to_json
' ----
Ran veil-env-helper --use-file -s chef-server.webui_key -s oc_id.sql_password -s oc_id.secret_key_base -- bin/rails runner -e production 'app = Doorkeeper::Application.find_or_create_by(:name => "supermarket");
app.update_attributes(:redirect_uri => "https://supermarket.mycompany.com/auth/chef_oauth2/callback");
puts app.to_json
' returned 1

Cookbook Trace: (most recent call first)
----------------------------------------
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/resources/oc_id_application.rb:64:in `create!'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/resources/oc_id_application.rb:27:in `block (2 levels) in class_from_file'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/resources/oc_id_application.rb:26:in `block in class_from_file'

Resource Declaration:
---------------------
# In /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/oc_id.rb

205: oc_id_application name do
206: write_to_disk node['private_chef']['insecure_addon_compat']
207: redirect_uri app['redirect_uri']
208: only_if { is_data_master? }
209: end
210: end

Compiled Resource:
------------------
# Declared in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/oc_id.rb:205:in `block in from_file'

oc_id_application("supermarket") do
action [:create]
default_guard_interpreter :default
declared_type :oc_id_application
cookbook_name "private-chef"
recipe_name "oc_id"
write_to_disk true
redirect_uri "https://supermarket.mycompany.com/auth/chef_oauth2/callback"
only_if { #code block }
end

System Info:
------------
chef_version=16.13.16
platform=centos
platform_version=7.9.2009
ruby=ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]
program_name=/opt/opscode/embedded/bin/chef-client
executable=/opt/opscode/embedded/bin/chef-client

Running handlers:
Running handlers complete
Chef Infra Client failed. 21 resources updated in 25 seconds
[2021-07-20T19:00:21+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2021-07-20T19:00:21+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2021-07-20T19:00:21+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: oc_id_application[supermarket] (private-chef::oc_id line 205) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of veil-env-helper --use-file -s chef-server.webui_key -s oc_id.sql_password -s oc_id.secret_key_base -- bin/rails runner -e production 'app = Doorkeeper::Application.find_or_create_by(:name => "supermarket");
app.update_attributes(:redirect_uri => "https://supermarket.mycompany.com/auth/chef_oauth2/callback");
puts app.to_json
' ----
STDOUT: W, [2021-07-20T19:00:20.294254 #1126] WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /opt/opscode/embedded/service/gem/ruby/2.7.0/gems/omniauth-1.3.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
CHEF_SECRETS_FD=5
I, [2021-07-20T19:00:20.294903 #1126] INFO -- : Raven 3.1.2 configured not to capture errors: DSN not set
STDERR: Warning: the running version of Bundler (2.1.4) is older than the version that created the lockfile (2.2.19). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.2.19`.
Please specify a valid ruby command or the path of a script to run.
Run 'rails runner -h' for help.

undefined method `confidential' for #<Doorkeeper::Application:0x0000000008160eb0>
---- End output of veil-env-helper --use-file -s chef-server.webui_key -s oc_id.sql_password -s oc_id.secret_key_base -- bin/rails runner -e production 'app = Doorkeeper::Application.find_or_create_by(:name => "supermarket");
app.update_attributes(:redirect_uri => "https://supermarket.mycompany.com/auth/chef_oauth2/callback");
puts app.to_json
' ----
Ran veil-env-helper --use-file -s chef-server.webui_key -s oc_id.sql_password -s oc_id.secret_key_base -- bin/rails runner -e production 'app = Doorkeeper::Application.find_or_create_by(:name => "supermarket");
app.update_attributes(:redirect_uri => "https://supermarket.mycompany.com/auth/chef_oauth2/callback");
puts app.to_json
' returned 1

```

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/customer-bugs/issues/439

**Comment by PrajaktaPurohit** [comment]
fixed with: https://docs.chef.io/release_notes_server/?v=14.7.13
