### ISSUE TITLE
chef-server-ctl reconfigure silently hangs when connecting to a blackholed external datbase

### ISSUE THREAD

**Issue by btm** [chef/chef-server#3040]
When configured for an external postgresql with Amazon RDS: `/etc/opscode/chef-server.rb`:
```
postgresql['external'] = true
postgresql['db_superuser'] = 'postgres'
postgresql['db_superuser_password'] = 'supersecretpassword'
postgresql['vip'] = 'infra-server.asdfasdfasdf.planet-earch.rds.amazonaws.com'
```

Running `chef-server-ctl reconfigure` the first time silently hangs as it tries to connect to the database if there aren't proper ACLs set to allow access.

Adding a log message here saying what we're connecting to and/or a 

```
[2021-12-23T20:59:59+00:00] FATAL: SIGINT received, stopping

  ================================================================================
  Recipe Compile Error in /var/opt/opscode/local-mode-cache/cookbooks/infra-server/recipes/default.rb
  ================================================================================

  SystemExit
  ----------
  exit

  Cookbook Trace: (most recent call first)
  ----------------------------------------
    /var/opt/opscode/local-mode-cache/cookbooks/infra-server/libraries/ec_postgres.rb:22:in `initialize'
    /var/opt/opscode/local-mode-cache/cookbooks/infra-server/libraries/ec_postgres.rb:22:in `new'
    /var/opt/opscode/local-mode-cache/cookbooks/infra-server/libraries/ec_postgres.rb:22:in `with_connection'
    /var/opt/opscode/local-mode-cache/cookbooks/infra-server/libraries/preflight_checks.rb:96:in `connect_as'
    /var/opt/opscode/local-mode-cache/cookbooks/infra-server/libraries/preflight_bootstrap_validator.rb:92:in `pivotal_user_exists?'
    /var/opt/opscode/local-mode-cache/cookbooks/infra-server/libraries/preflight_bootstrap_validator.rb:41:in `run!'
    /var/opt/opscode/local-mode-cache/cookbooks/infra-server/libraries/preflight_checks.rb:143:in `run!'
    /var/opt/opscode/local-mode-cache/cookbooks/infra-server/recipes/config.rb:98:in `from_file'
    /var/opt/opscode/local-mode-cache/cookbooks/infra-server/recipes/default.rb:49:in `from_file'

  Relevant File Content:
  ----------------------
  /var/opt/opscode/local-mode-cache/cookbooks/infra-server/libraries/ec_postgres.rb:

   15:        retries = opts['retries'] || 1
   16:      else
   17:        silent = false
   18:        retries = opts['retries'] || 5
   19:      end
   20:      max_retries = retries
   21:      begin
   22>>       connection = PG::Connection.open('user' =>     postgres['db_connection_superuser'] || postgres['db_superuser'],
   23:                                         'host' =>     postgres['vip'],
   24:                                         'password' => postgres['db_superuser_password'],
   25:                                         'port' =>     postgres['port'],
   26:                                         'sslmode' =>  postgres['sslmode'],
   27:                                         'dbname' =>   database)
   28:      rescue => e
   29:        if retries > 0
   30:          sleep_time = 2**((max_retries - retries))
   31:          retries -= 1

  System Info:
  ------------
  chef_version=16.17.4
  platform=ubuntu
  platform_version=20.04
  ruby=ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]
  program_name=/opt/opscode/embedded/bin/chef-client
  executable=/opt/opscode/embedded/bin/chef-client


  Running handlers:
  Running handlers complete
  Chef Infra Client failed. 0 resources updated in 02 minutes 14 seconds
[2021-12-23T21:00:00+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2021-12-23T21:00:00+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
```

We might be able to simply add a `connect_timeout` there, e.g.

```
2.7.4 :005 > conn = PG::Connection.open(:connect_timeout => '1', :hostaddr => '240.0.0.0')
Traceback (most recent call last):
        7: from /home/btm/.rvm/rubies/ruby-2.7.4/bin/irb:23:in `<main>'
        6: from /home/btm/.rvm/rubies/ruby-2.7.4/bin/irb:23:in `load'
        5: from /home/btm/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        4: from (irb):4
        3: from (irb):5:in `rescue in irb_binding'
        2: from (irb):5:in `new'
        1: from (irb):5:in `initialize'
PG::ConnectionBad (timeout expired)
```

**Comment by tas50** [comment]
Closing in favor of https://github.com/chef/chef-server/issues/4
