### ISSUE TITLE
Chef Automate 2022-01 failing chef-server-ctl test

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#3150]
When we bootstrap a fresh Chef Automate server and run chef-server-ctl test, we get the following error -

    Testing Status API with config
      Status API
        GET /_status should respond with valid health data (FAILED - 1)

    Failures:

      1) Testing Status API with config Status API GET /_status should respond with valid health data
         Failure/Error: let (:config) { JSON.parse(IO.read("/etc/opscode/chef-server-running.json"))['private_chef'] }

         Errno::ENOENT:
           No such file or directory @ rb_sysopen - /etc/opscode/chef-server-running.json
         # /hab/pkgs/chef/chef-server-ctl/14.11.36/20211227114241/oc-chef-pedant/spec/api/status_spec.rb:3:in `read'
         # /hab/pkgs/chef/chef-server-ctl/14.11.36/20211227114241/oc-chef-pedant/spec/api/status_spec.rb:3:in `block (2 levels) in <top (required)>'
         # /hab/pkgs/chef/chef-server-ctl/14.11.36/20211227114241/oc-chef-pedant/spec/api/status_spec.rb:9:in `block (3 levels) in <top (required)>'

    Finished in 1 minute 54.69 seconds (files took 5.59 seconds to load)
    170 examples, 1 failure, 2 pending

    Failed examples:

    rspec /hab/pkgs/chef/chef-server-ctl/14.11.36/20211227114241/oc-chef-pedant/spec/api/status_spec.rb:5 # Testing Status API with config Status API GET /_status should respond with valid health data

Could you please help us with this issue?
 
To Reproduce

Install Chef-infra with Automate on a single instance
Run the command chef-server-ctl test
Expected behavior

The test should complete successfully

Actual behavior

It is being failed with the automate version Automate v2 20220103112354

**Comment by PrajaktaPurohit** [comment]
Fixed with 14.13.43 of Infra Server
