### ISSUE TITLE
chef-server-ctl test failure: Search API endpoint using POST 

### ISSUE THREAD

**Issue by jtimberman** [chef/chef-server#321]
Failure from pedant:

```
Failures:

  1) Search API endpoint /search/<data_bag> using POST for an existing data bag with nested keys (CHEF-3975) when searching a nested key should succeed
     Failure/Error: r.should look_like search_success_response

       Expected a full match of the result

         {"total"=>0, "start"=>0, "rows"=>[]}


       to the spec

         {"total"=>1,
        "start"=>0,
        "rows"=>
         [{"url"=>
            "https://ec2-52-24-27-201.us-west-2.compute.amazonaws.com/organizations/pedant_testorg_ip-172-31-39-63_6753/data/pedant_temporary_bag_1433221834-914085284-6753/alice",
           "data"=>
            {"private_key"=>"---RSA Private Key-- Alice",
             "public_key"=>"---RSA Public Key--- Alice"}}]}


       to succeed, but it didn't!
     # ./lib/pedant/rspec/search_util.rb:101:in `block (2 levels) in performing_a_search'
     # ./lib/pedant/rspec/search_util.rb:715:in `with_search_polling'
     # ./lib/pedant/rspec/search_util.rb:88:in `block in performing_a_search'

Finished in 5 minutes 15 seconds
151 examples, 1 failure, 7 pending

Failed examples:

rspec ./lib/pedant/rspec/search_util.rb:87 # Search API endpoint /search/<data_bag> using POST for an existing data bag with nested keys (CHEF-3975) when searching a nested key should succeed
```

Steps to reproduce:
1. Create Ubuntu 14.04 instance in EC2
2. Install Chef Server 12.0.8
3. Set `api_fqdn` in `/etc/opscode/chef-server.rb` to the public hostname of the EC2 instance.
4. Run `chef-server-ctl reconfigure`
5. Run `chef-server-ctl test`

I didn't try creating a new instance, but this failure did happen twice in a row on the same system.

**Comment by stevendanna** [comment]
I'm going to close this out.  If such an error re-appears in our build pipeline or if we see it again, we will certainly investigate.
