### ISSUE TITLE
 Chef server install fails at "add internal user to opensearch security plugin" on local proxmox host but not AWS

### ISSUE THREAD

**Issue by Ghostbroker** [chef/chef-server#3451]
### Chef Server Version
15.1.7

### Platform Details
Local proxmox, 4GB RAM on each VM with 2 CPUs, newly provisioned VMs:
Centos7 - Selinux disabled, FQDN configured
Rocky8.6 - Selinux disabled, FQDN configured
Ubuntu 22.04.1 LTS - Apparmor was disabled, FQDN configured

### Configuration

VM inside proxmox, new install. /etc/opscode/chef-server.rb was not yet generated

### Scenario

We are trying to install chef server in VM on-site inside proxmox and it is failing.

### Steps to Reproduce

1) Configure VM per prerequisites , verify FQDN is resolvable, disable selinux/apparmor
2) Wget chef package
3) Install chef package
4) Run chef-server-ctl reconfigure as root 

### Expected Result

Chef server to be installed

### Actual Result

In AWS, install was successful. In proxmox environment with 3 different images, we were met with failure at the following step:

**execute[add internal user to opensearch security plugin] action run**

**/var/opt/opscode/local-mode-cache/chef-stacktrace.out**

```
Generated at 2022-09-15 02:47:40 +0000
Mixlib::ShellOut::ShellCommandFailed: execute[add internal user to opensearch security plugin] (infra-server::opensearch line 187) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '255'
---- Begin output of export JAVA_HOME="/opt/opscode/embedded/open-jre/"; ./securityadmin.sh   -f ../securityconfig/internal_users.yml   -icl -nhnv -cert /opt/opscode/embedded/opensearch/config/admin.pem   -cacert /opt/opscode/embedded/opensearch/config/root-ca.pem   -key /opt/opscode/embedded/opensearch/config/admin-key.pem ----
STDOUT: Security Admin v7
Will connect to localhost:9300
ERR: Seems there is no OpenSearch running on localhost:9300 - Will exit
STDERR:
---- End output of export JAVA_HOME="/opt/opscode/embedded/open-jre/"; ./securityadmin.sh   -f ../securityconfig/internal_users.yml   -icl -nhnv -cert /opt/opscode/embedded/opensearch/config/admin.pem   -cacert /opt/opscode/embedded/opensearch/config/root-ca.pem   -key /opt/opscode/embedded/opensearch/config/admin-key.pem ----
Ran export JAVA_HOME="/opt/opscode/embedded/open-jre/"; ./securityadmin.sh   -f ../securityconfig/internal_users.yml   -icl -nhnv -cert /opt/opscode/embedded/opensearch/config/admin.pem   -cacert /opt/opscode/embedded/opensearch/config/root-ca.pem   -key /opt/opscode/embedded/opensearch/config/admin-key.pem returned 255
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout.rb:300:in `invalid!'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout.rb:287:in `error!'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout/helper.rb:130:in `shell_out_compacted!'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout/helper.rb:54:in `shell_out!'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider/execute.rb:52:in `block (2 levels) in <class:Execute>'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider.rb:265:in `converge_by'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider/execute.rb:50:in `block in <class:Execute>'
(eval):2:in `block in action_run'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider.rb:276:in `instance_eval'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider.rb:276:in `compile_and_converge_action'
(eval):2:in `action_run'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider.rb:217:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource.rb:599:in `block in run_action'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource.rb:626:in `with_umask'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource.rb:598:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:74:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:108:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:108:in `run_all_actions'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:132:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/opscode/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:130:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/client.rb:687:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/client.rb:682:in `catch'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/client.rb:682:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/client.rb:706:in `converge_and_save'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/client.rb:286:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/application.rb:264:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/application/base.rb:337:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/application.rb:67:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.17.51/bin/chef-client:25:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:23:in `load'
/opt/opscode/embedded/bin/chef-client:23:in `<main>'

>>>> Caused by Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '255'
---- Begin output of export JAVA_HOME="/opt/opscode/embedded/open-jre/"; ./securityadmin.sh   -f ../securityconfig/internal_users.yml   -icl -nhnv -cert /opt/opscode/embedded/opensearch/config/admin.pem   -cacert /opt/opscode/embedded/opensearch/config/root-ca.pem   -key /opt/opscode/embedded/opensearch/config/admin-key.pem ----
STDOUT: Security Admin v7
Will connect to localhost:9300
ERR: Seems there is no OpenSearch running on localhost:9300 - Will exit
STDERR:
---- End output of export JAVA_HOME="/opt/opscode/embedded/open-jre/"; ./securityadmin.sh   -f ../securityconfig/internal_users.yml   -icl -nhnv -cert /opt/opscode/embedded/opensearch/config/admin.pem   -cacert /opt/opscode/embedded/opensearch/config/root-ca.pem   -key /opt/opscode/embedded/opensearch/config/admin-key.pem ----
Ran export JAVA_HOME="/opt/opscode/embedded/open-jre/"; ./securityadmin.sh   -f ../securityconfig/internal_users.yml   -icl -nhnv -cert /opt/opscode/embedded/opensearch/config/admin.pem   -cacert /opt/opscode/embedded/opensearch/config/root-ca.pem   -key /opt/opscode/embedded/opensearch/config/admin-key.pem returned 255
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout.rb:300:in `invalid!'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout.rb:287:in `error!'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout/helper.rb:130:in `shell_out_compacted!'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout/helper.rb:54:in `shell_out!'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider/execute.rb:52:in `block (2 levels) in <class:Execute>'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider.rb:265:in `converge_by'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider/execute.rb:50:in `block in <class:Execute>'
(eval):2:in `block in action_run'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider.rb:276:in `instance_eval'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider.rb:276:in `compile_and_converge_action'
(eval):2:in `action_run'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider.rb:217:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource.rb:599:in `block in run_action'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource.rb:626:in `with_umask'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource.rb:598:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:74:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:108:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:108:in `run_all_actions'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:132:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/opscode/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:130:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/client.rb:687:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/client.rb:682:in `catch'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/client.rb:682:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/client.rb:706:in `converge_and_save'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/client.rb:286:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/application.rb:264:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/application/base.rb:337:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/application.rb:67:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.17.51/bin/chef-client:25:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:23:in `load'
/opt/opscode/embedded/bin/chef-client:23:in `<main>'root@chef:/var/opt/opscode/local-mode-cache# cat /etc/opscode/
```

[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by Ghostbroker** [comment]
Changing the proxmox CPU type from 'kvm64' to 'host' resolved this issue.

**Comment by PrajaktaPurohit** [comment]
Thank you for the update! Will close the issue for now.
