### ISSUE TITLE
Chef AWS HA split brain after reboot of primary node

### ISSUE THREAD

**Issue by jslusher** [chef/chef-server#415]
This issue is by request from Sean Horn at Chef. I will try to be as detailed as I can. I set up a 4 node Chef AWS HA cluster with the EBS-backed volume, following the documentation. I then loaded it with my roles, cookbooks, etc and began failover testing. Stopping keepalived and stopping the primary instance created the expected failover scenario, although the time it took to completely failover was a couple of minutes. If I simply reboot the primary instance however, the secondary node does not completely fail over. The primary comes up too quickly and it results in a master/master split-brain scenario that causes 503 errors from chef clients. I will post a separate gist that has some configuration details.

**Comment by jslusher** [comment]
Here is the chef-server.rb configuration as requested. Nothing out of the ordinary as far as I know.
https://gist.github.com/jslusher/1e98a23a8deb76ffb97e

**Comment by jslusher** [comment]
And here is the HA status after rebooting the primary and the secondary. Rebooting the primary actually did end up successfully failing over to the secondary after a few minutes, which seems an extreme amount of time to fail over. I then rebooted the secondary to see if it would fail back and it went split-brain.

https://gist.github.com/jslusher/1cda9b1b724f4760f005

**Comment by sean-horn** [comment]
Hi @jslusher would you repost a link for your last gist? It's returning a 404 when I try to follow it.

**Comment by sean-horn** [comment]
1. Mostly sort of works with `chef-server-ctl stop keepalived` test failovers

2. In real world situations, with AWS instances rebooting or
   stopping, there are multiple causes for failed failovers.

  On Secondary in cluster.log. Transition to backup by
  stopping Primary, failover occurs, failover fails, because VBD
  on Secondary (new Primary) needs a reboot to attach and mount the storage device.

```
Mon, 27 Jul 2015 19:13:17 +0000: Attempting HA storage detach
Volume vol-e8e19702 is not attached to i-6ef2b0c6!
Mon, 27 Jul 2015 19:13:18 +0000: HA storage detach success
Mon, 27 Jul 2015 19:13:18 +0000: Attempting HA BACKEND IP to go standby
Nothing to do to relinquish IP
Mon, 27 Jul 2015 19:13:19 +0000: HA BACKEND IP detach success
Mon, 27 Jul 2015 19:13:19 +0000: Transitioned to backup
Mon, 27 Jul 2015 19:15:36 +0000: Transitioning to master
Mon, 27 Jul 2015 19:15:36 +0000: Attempting HA storage takeover
[   11.216386] vbd vbd-51728: 16 Device in use; refusing to close
/opt/chef-ha/embedded/service/chef-ha/ha_backend_storage_aws:136:in `action_attach': ERROR: Stuck VBD device, please reboot this machine(http://zhigang.org/wiki/XenVirtualDisk#what-happens-when-detaching-a-virtual-disk-while-the-disk-is-opened-in-the-guest-eg-mounted) (RuntimeError)
        from /opt/chef-ha/embedded/service/chef-ha/ha_backend_storage_aws:238:in `<top (required)>'
        from /var/opt/opscode/keepalived/bin/ha_backend_storage:9:in `load'
        from /var/opt/opscode/keepalived/bin/ha_backend_storage:9:in `<main>'
Mon, 27 Jul 2015 19:15:38 +0000: HA storage attach failed
```

  Rebooted the original Secondary and was still unable to take over the storage
  device from the stopped Primary.

```
Mon, 27 Jul 2015 19:19:41 +0000: Transitioning to backup
Mon, 27 Jul 2015 19:19:41 +0000: Stopping service redis_lb
Mon, 27 Jul 2015 19:19:44 +0000: Stopping service rabbitmq
Mon, 27 Jul 2015 19:19:46 +0000: Stopping service postgresql
Mon, 27 Jul 2015 19:19:46 +0000: Requested transition to master
Mon, 27 Jul 2015 19:19:46 +0000: Requested transition to master, but state transition already running.
Mon, 27 Jul 2015 19:19:47 +0000: Stopping service opscode-solr4
Mon, 27 Jul 2015 19:19:49 +0000: Stopping service opscode-expander-reindexer
Mon, 27 Jul 2015 19:19:50 +0000: Stopping service opscode-expander
Mon, 27 Jul 2015 19:19:52 +0000: Stopping service opscode-erchef
Mon, 27 Jul 2015 19:19:53 +0000: Stopping service oc_id
Mon, 27 Jul 2015 19:19:55 +0000: Stopping service oc_bifrost
Mon, 27 Jul 2015 19:19:57 +0000: Stopping service nginx
Mon, 27 Jul 2015 19:19:58 +0000: Stopping service bookshelf
Mon, 27 Jul 2015 19:20:00 +0000: Attempting HA storage detach
Volume vol-e8e19702 is not attached to i-6ef2b0c6!
Mon, 27 Jul 2015 19:20:02 +0000: HA storage detach success
Mon, 27 Jul 2015 19:20:02 +0000: Attempting HA BACKEND IP to go standby
Nothing to do to relinquish IP
Mon, 27 Jul 2015 19:20:04 +0000: HA BACKEND IP detach success
Mon, 27 Jul 2015 19:20:04 +0000: Transitioned to backup
Mon, 27 Jul 2015 19:20:04 +0000: Transitioning to master
Mon, 27 Jul 2015 19:20:04 +0000: Attempting HA storage takeover
/opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/middlewares/expects.rb:10:in `response_call': IncorrectState => Volume 'vol-e8e19702'is in the 'available' state. (Fog::Compute::AWS::Error)
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/middlewares/response_parser.rb:8:in `response_call'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/connection.rb:363:in `response'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/connection.rb:233:in `request'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/middlewares/idempotent.rb:22:in `error_call'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/middlewares/base.rb:10:in `error_call'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/middlewares/base.rb:10:in `error_call'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/connection.rb:253:in `rescue in request'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/connection.rb:201:in `request'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/middlewares/idempotent.rb:22:in `error_call'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/middlewares/base.rb:10:in `error_call'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/middlewares/base.rb:10:in `error_call'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/connection.rb:253:in `rescue in request'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/connection.rb:201:in `request'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/middlewares/idempotent.rb:22:in `error_call'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/middlewares/base.rb:10:in `error_call'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/middlewares/base.rb:10:in `error_call'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/connection.rb:253:in `rescue in request'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/excon-0.39.5/lib/excon/connection.rb:201:in `request'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/fog-1.22.1/lib/fog/xml/sax_parser_connection.rb:35:in `request'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/fog-1.22.1/lib/fog/xml.rb:21:in `request'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/fog-1.22.1/lib/fog/aws/compute.rb:462:in `_request'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/fog-1.22.1/lib/fog/aws/compute.rb:457:in `request'
        from /opt/chef-ha/embedded/service/gem/ruby/1.9.1/gems/fog-1.22.1/lib/fog/aws/requests/compute/detach_volume.rb:33:in `detach_volume'
        from /opt/chef-ha/embedded/service/chef-ha/ha_backend_storage_aws:50:in `nice_detacher'
        from /opt/chef-ha/embedded/service/chef-ha/ha_backend_storage_aws:148:in `action_attach'
        from /opt/chef-ha/embedded/service/chef-ha/ha_backend_storage_aws:238:in `<top (required)>'
        from /var/opt/opscode/keepalived/bin/ha_backend_storage:9:in `load'
        from /var/opt/opscode/keepalived/bin/ha_backend_storage:9:in `<main>'
invoking the nice_detacher
............
Timed out waiting for volume to be available after 60s
Detaching myself
...........
Timed out waiting for volume to be available after 60s
Force Detaching
Mon, 27 Jul 2015 19:22:06 +0000: HA storage attach failed
```

  No further attempts by the Secondary to become Primary. The failover failed.

  Maybe we need to go through the entire sequence a few times, maybe
  three times, and call it a success if it succeeds and give up after
  all tries are complete. We retry many times on the storage
  detach/attach but never try the complete initialization process again. 
  
  Maybe a pause and complete retry is necessary in there, because I
  run this to get another complete transition attempt after the above
  failure on the same Secondary (new Primary) system and it works.

    sudo chef-server-ctl stop keepalived
    sudo chef-server-ctl start keepalived

```
Mon, 27 Jul 2015 19:24:38 +0000: Transitioning to backup
Mon, 27 Jul 2015 19:24:38 +0000: Stopping service redis_lb
Mon, 27 Jul 2015 19:24:40 +0000: Stopping service rabbitmq
Mon, 27 Jul 2015 19:24:41 +0000: Stopping service postgresql
Mon, 27 Jul 2015 19:24:43 +0000: Stopping service opscode-solr4
Mon, 27 Jul 2015 19:24:44 +0000: Stopping service opscode-expander-reindexer
Mon, 27 Jul 2015 19:24:46 +0000: Stopping service opscode-expander
Mon, 27 Jul 2015 19:24:47 +0000: Requested transition to backup
Mon, 27 Jul 2015 19:24:47 +0000: Requested transition to backup, but state transition already running.
Mon, 27 Jul 2015 19:24:48 +0000: Stopping service opscode-erchef
Mon, 27 Jul 2015 19:24:49 +0000: Stopping service oc_id
Mon, 27 Jul 2015 19:24:51 +0000: Stopping service oc_bifrost
Mon, 27 Jul 2015 19:24:52 +0000: Requested transition to master
Mon, 27 Jul 2015 19:24:52 +0000: Requested transition to master, but state transition already running.
Mon, 27 Jul 2015 19:24:52 +0000: Stopping service nginx
Mon, 27 Jul 2015 19:24:54 +0000: Stopping service bookshelf
Mon, 27 Jul 2015 19:24:56 +0000: Attempting HA storage detach
Volume vol-e8e19702 is not attached to i-6ef2b0c6!
Mon, 27 Jul 2015 19:24:57 +0000: HA storage detach success
Mon, 27 Jul 2015 19:24:57 +0000: Attempting HA BACKEND IP to go standby
Nothing to do to relinquish IP
Mon, 27 Jul 2015 19:24:58 +0000: HA BACKEND IP detach success
Mon, 27 Jul 2015 19:24:58 +0000: Transitioned to backup
Mon, 27 Jul 2015 19:24:58 +0000: Transitioning to master
Mon, 27 Jul 2015 19:24:58 +0000: Attempting HA storage takeover
Attaching volume vol-e8e19702 to server i-6ef2b0c6

Volume vol-e8e19702 is now in-use
Waiting for LVM volume to become available
..Found LVM volume /dev/chef/data
  1 logical volume(s) in volume group "chef" now active

Mounting /var/opt/opscode/drbd/data
Mon, 27 Jul 2015 19:25:07 +0000: HA storage attach success
Mon, 27 Jul 2015 19:25:07 +0000: Starting service bookshelf
Mon, 27 Jul 2015 19:25:09 +0000: Starting service nginx
Mon, 27 Jul 2015 19:25:11 +0000: Starting service oc_bifrost
Mon, 27 Jul 2015 19:25:13 +0000: Starting service oc_id
Mon, 27 Jul 2015 19:25:15 +0000: Starting service opscode-erchef
Mon, 27 Jul 2015 19:25:17 +0000: Starting service opscode-expander
Mon, 27 Jul 2015 19:25:20 +0000: Starting service opscode-expander-reindexer
Mon, 27 Jul 2015 19:25:22 +0000: Starting service opscode-solr4
Mon, 27 Jul 2015 19:25:24 +0000: Starting service postgresql
Mon, 27 Jul 2015 19:25:26 +0000: Starting service rabbitmq
Mon, 27 Jul 2015 19:25:28 +0000: Doing post-start hook for rabbitmq
Mon, 27 Jul 2015 19:25:35 +0000: Starting service redis_lb
Mon, 27 Jul 2015 19:25:39 +0000: Attempting HA BACKEND IP primary takeover
Binding the AWS VPC VIP to me
Mon, 27 Jul 2015 19:25:41 +0000: HA BACKEND IP attach success
Mon, 27 Jul 2015 19:25:41 +0000: Transitioned to master
```

  I start the original Master back up after 20+ minutes stopped....And takes
  over as MASTER, even though it reports "Preempt disabled" during its
  startup and it starts up in BACKUP mode, both of which indicate that
  it should not preempt at all. It should just join as a BACKUP node
  and go to sleep, waiting for a failure of the current MASTER.

**Comment by sean-horn** [comment]
Today, I will look at any difference in keepalived advertisement packets between a system Stop/Reboot and just a `chef-server-ctl stop keepalived`, as the latter seems to be much better behaved.

**Comment by sean-horn** [comment]
Listen to the interface on the current Secondary (172.31.40.7). It's receiving adverts from the current Primary (172.31.40.5) for a VIP.   

```
ubuntu@ip-172-31-40-7:~$ sudo tcpdump -n -i eth0 'host 172.31.40.7 and proto VRRP'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
17:29:57.379334 IP 172.31.40.5 > 172.31.40.7: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
17:29:58.380384 IP 172.31.40.5 > 172.31.40.7: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
```

Stop the keepalived on the current Primary, 172.31.40.5
It issues an advertisement with a priority of 0 to it's partner, 172.31.40.7 , meaning "I'm relinquishing control of the VIP now, please take over for me"
```
17:30:09.079879 IP 172.31.40.5 > 172.31.40.7: VRRPv2, Advertisement, vrid 1, prio 0, authtype simple, intvl 1s, length 20
```

The current Secondary, 172.31.40.7, takes over as Primary with priority 100 advertisements back to 172.31.40.5, the new Secondary.
```
17:30:09.690086 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
17:30:10.691548 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
```

Same thing initiating a test failover from 172.31.40.7 -> 172.31.40.5

```
ubuntu@ip-172-31-40-5:~$ sudo tcpdump -n -i eth0 'host 172.31.40.7 and proto VRRP'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
17:49:13.909953 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
17:49:14.910213 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20

17:49:23.641146 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 0, authtype simple, intvl 1s, length 20

17:49:24.251375 IP 172.31.40.5 > 172.31.40.7: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
17:49:25.252908 IP 172.31.40.5 > 172.31.40.7: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
^C
17 packets captured
18 packets received by filter
0 packets dropped by kernel
```

Test - AWS Stop Current Secondary
----------------------------------------------------

Behavior in tcpdump shows that current Primary (172.31.40.7) is advertising itself as master at prio 100.

Current Secondary (172.31.40.5) is stopped, then is started back up at 18:23:11.470579 and initiates an election, which 172.31.40.7 wins, as it is already running in master status
```
18:23:06.954654 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
18:23:07.955787 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
18:23:08.956925 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
18:23:09.958039 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
18:23:10.959179 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
18:23:11.470579 IP 172.31.40.5 > 172.31.40.7: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
18:23:12.471788 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
18:23:12.471951 IP 172.31.40.5 > 172.31.40.7: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
18:23:13.473086 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
18:23:14.474211 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
```

Test - AWS Stop Current Primary for 4 minutes
----------------------------------------------------------------

At 18:31:46.052572, the current Primary instance is shutdown using the AWS Stop and it hands control to the other instance.

```
18:31:44.452612 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
18:31:45.453677 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20

18:31:46.052572 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 0, authtype simple, intvl 1s, length 20

18:31:46.662637 IP 172.31.40.5 > 172.31.40.7: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
18:31:47.664455 IP 172.31.40.5 > 172.31.40.7: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
```

Then, the Stopped Primary comes up again after 4 minutes of downtime and preempts the current Primary.

```
ubuntu@ip-172-31-40-5:~$ sudo tcpdump -n -i eth0 'proto VRRP'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
18:34:25.832042 IP 172.31.40.5 > 172.31.40.7: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
...
...
...
18:35:11.883881 IP 172.31.40.5 > 172.31.40.7: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
18:35:11.950702 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
18:35:12.952090 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
```

Test - AWS Stop Current Primary (172.31.40.7) for 20+ minutes
-------------------------------------------------------------------------------------

Same undesired result. Original Primary (172.31.40.7) preempts the current one rather than joining the cluster as a backup, as it should.
```
22:41:28.031923 IP 172.31.40.5 > 172.31.40.7: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
22:41:29.033087 IP 172.31.40.5 > 172.31.40.7: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
22:41:29.406588 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
22:41:30.407939 IP 172.31.40.7 > 172.31.40.5: VRRPv2, Advertisement, vrid 1, prio 100, authtype simple, intvl 1s, length 20
```

**Comment by sean-horn** [comment]
In testing, I found several problems.

* I cannot find any configuration where if the original Primary comes back, it will not preempt the current Primary. This does not happen with Vagrant, the same version of keepalived, and same config.
* This VBD thing sometimes happens, causing failovers to fail. Once the system is rebooted, it acquires Primary status and functions.

```
Fri, 31 Jul 2015 19:45:09 +0000: Transitioning to backup
Fri, 31 Jul 2015 19:45:09 +0000: Stopping service redis_lb
Fri, 31 Jul 2015 19:45:11 +0000: Stopping service rabbitmq
Fri, 31 Jul 2015 19:45:13 +0000: Stopping service postgresql
Fri, 31 Jul 2015 19:45:13 +0000: Requested transition to master
Fri, 31 Jul 2015 19:45:13 +0000: Requested transition to master, but state transition already running.
Fri, 31 Jul 2015 19:45:14 +0000: Stopping service opscode-solr4
Fri, 31 Jul 2015 19:45:16 +0000: Stopping service opscode-expander-reindexer
Fri, 31 Jul 2015 19:45:18 +0000: Stopping service opscode-expander
Fri, 31 Jul 2015 19:45:19 +0000: Stopping service opscode-erchef
Fri, 31 Jul 2015 19:45:21 +0000: Stopping service oc_id
Fri, 31 Jul 2015 19:45:22 +0000: Stopping service oc_bifrost
Fri, 31 Jul 2015 19:45:24 +0000: Stopping service nginx
Fri, 31 Jul 2015 19:45:26 +0000: Stopping service bookshelf
Fri, 31 Jul 2015 19:45:27 +0000: Attempting HA storage detach
Volume vol-e8e19702 is not attached to i-6cf2b0c4!
Fri, 31 Jul 2015 19:45:29 +0000: HA storage detach success
Fri, 31 Jul 2015 19:45:29 +0000: Attempting HA BACKEND IP to go standby
Nothing to do to relinquish IP
Fri, 31 Jul 2015 19:45:30 +0000: HA BACKEND IP detach success
Fri, 31 Jul 2015 19:45:30 +0000: Transitioned to backup
Fri, 31 Jul 2015 19:45:30 +0000: Transitioning to master
Fri, 31 Jul 2015 19:45:30 +0000: Attempting HA storage takeover
[69293.875161] vbd vbd-51728: 16 Device in use; refusing to close
/opt/chef-ha/embedded/service/chef-ha/ha_backend_storage_aws:136:in `action_attach': ERROR: Stuck VBD device, please reboot this machine(http://zhigang.org/wiki/XenVirtualDisk#what-happens-when-detaching-a-virtual-disk-while-the-disk-is-opened-in-the-guest-eg-mounted) (RuntimeError)
        from /opt/chef-ha/embedded/service/chef-ha/ha_backend_storage_aws:238:in `<top (required)>'
        from /var/opt/opscode/keepalived/bin/ha_backend_storage:9:in `load'
        from /var/opt/opscode/keepalived/bin/ha_backend_storage:9:in `<main>'
Fri, 31 Jul 2015 19:45:32 +0000: HA storage attach failed
```

**Comment by mivok** [comment]
I know this is an old ticket, and we have a much improved chef-ha product now, but I found a solution to at least part of this issue.

You need to explicitly allow VRRP traffic in the backend's security group. Find the security group set up for the backend instance and edit it, choose the Inbound tab, and then 'Custom Protocol' from the 'Type' dropdown. This will let you pick VRRP from the protocol dropdown (protocol 112). Choose the IP range of your VPC (or just the IPs of the two backends if you wish) and save the changes.

The reason things kind of work normally is that by default, all outbound traffic is allowed, so once both sides start transmitting VRRP packets, a state is established and traffic can flow normally. 

However, when you reboot an instance, the state is lost, and no VRRP packets are transmitted by backup instances, which means that in turn it won't receive the advertisements by the current primary. Once a timeout has passed, the current secondary attempts to take over and begins advertising, at which point it then starts to hear the packets coming from the current primary, tries to go back to a secondary state and you end up in this half failed over state because it's still running the failover script to move the EBS volume and IP.

**Comment by marcparadise** [comment]
@mivok I owe you a beverage of choice when we next meet - great find!

**Comment by PrajaktaPurohit** [comment]
Closing, since Chef AWS HA is EOLed.
