### ISSUE TITLE
Intermittent upgrade error with nightly chef-server-core_12.2.0+20150730184117

### ISSUE THREAD

**Issue by wrightp** [chef/chef-server#460]
This was a Tier CS 12.1.2 -> 12.2.0+20150730184117

Re-running the upgrade will work (probably the db started by then)

```
execute[chef-server-ctl upgrade] action run

                                           ================================================================================
                                           Error executing action `run` on resource 'execute[chef-server-ctl upgrade]'
                                           ================================================================================

                                           Mixlib::ShellOut::ShellCommandFailed
                                           ------------------------------------
                                           Expected process to exit with [0], but received '1'
                                           ---- Begin output of chef-server-ctl upgrade ----
                                           STDOUT: Upgrading with options #<OpenStruct skip_confirmation=false, chef11_server_url="https://localhost", chef12_server_url="https://localhost", upload_threads=10, chef11_admin_client_name="admin", chef11_admin_client_key="/etc/chef-server/admin.pem">
                                           [2015-07-30T22:15:38+00:00] INFO: Port 8889 in use: Address already in use - bind(2) for 127.0.0.1:8889

                                           ================================================================================
                                           Error executing action `create` on resource 'private_chef_pg_user[opscode-pgsql]'
                                           ================================================================================

                                           PG::ConnectionBad
                                           -----------------
                                           FATAL:  the database system is starting up

                                           Cookbook Trace:
                                           ---------------
                                           /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/libraries/ec_postgres.rb:25:in `initialize'
                                           /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/libraries/ec_postgres.rb:25:in `new'
                                           /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/libraries/ec_postgres.rb:25:in `block in with_local_connection'
                                           /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/libraries/ec_postgres.rb:42:in `as_user'
                                           /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/libraries/ec_postgres.rb:24:in `with_local_connection'
                                           /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/providers/pg_user.rb:12:in `block in class_from_file'

                                           Resource Declaration:
                                           ---------------------
                                           # In /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/postgresql.rb

                                           128:   private_chef_pg_user node['private_chef']['postgresql']['db_superuser'] do
                                           129:     password node['private_chef']['postgresql']['db_superuser_password']
                                           130:     # This initial password set must be done over local socket:
                                           131:     local_connection true
                                           132:     # Don't make superuser into a non-superuser...
                                           133:     superuser true
                                           134:   end
                                           135:
                                           136:   # Set up a database for the opscode-pgsql user to log into automatically
                                           137:   private_chef_pg_database "opscode-pgsql"
                                           138:   include_recipe "private-chef::erchef_database"
                                           139:   include_recipe "private-chef::bifrost_database"
                                           140:   include_recipe "private-chef::oc_id_database"
                                           141: end

                                           Compiled Resource:
                                           ------------------
                                           # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/postgresql.rb:128:in `from_file'

                                           private_chef_pg_user("opscode-pgsql") do
                                             action [:create]
                                             retries 0
                                             retry_delay 2
                                             default_guard_interpreter :default
                                             declared_type :private_chef_pg_user
                                             cookbook_name "private-chef"
                                             recipe_name "postgresql"
                                             password "0a414a3cbc010be16b14d36cea968ac2fea08e264baccabe249690f508f9b9de01b22b3da8c148cb93b2e0dc283e5d7ba28d"
                                             local_connection true
                                             superuser true
                                           end
```

**Comment by PrajaktaPurohit** [comment]
Please feel free to reopen if the issue persists with the newer (Stable release for Chef-Server is 13.2.0). Sorry we could not get back to you earlier.
