### ISSUE TITLE
chef-sync crashes when installed from scratch

### ISSUE THREAD

**Issue by albsOps** [chef/chef-server#517]
I have chef-sync enabled in the past, it was working without problems.

Today I tried to set it again, following the steps mentioned in the official guide with no success. the sync process crashes in the replica servers just after start. 
The log says:
```
2015-09-08_15:44:45.61363 /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:217:in `initialize': PG::ConnectionBad: fe_sendauth: no password supplied (Sequel::Dat
abaseConnectionError)
2015-09-08_15:44:45.61365       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:217:in `new'
2015-09-08_15:44:45.61366       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:217:in `connect'
2015-09-08_15:44:45.61366       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool.rb:96:in `make_new'
2015-09-08_15:44:45.61367       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:158:in `make_new'
2015-09-08_15:44:45.61368       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:137:in `available'
2015-09-08_15:44:45.61368       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:127:in `block in acquire'
2015-09-08_15:44:45.61369       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:194:in `block in sync'
2015-09-08_15:44:45.61371       from <internal:prelude>:10:in `synchronize'
2015-09-08_15:44:45.61371       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:194:in `sync'
2015-09-08_15:44:45.61372       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:126:in `acquire'
2015-09-08_15:44:45.61373       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:94:in `hold'
2015-09-08_15:44:45.61373       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/database/connecting.rb:250:in `synchronize'
2015-09-08_15:44:45.61374       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/shared/postgres.rb:446:in `server_version'
2015-09-08_15:44:45.61374       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/shared/postgres.rb:1563:in `server_version'
2015-09-08_15:44:45.61375       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/sql.rb:228:in `select_sql'
2015-09-08_15:44:45.61376       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:139:in `each'
2015-09-08_15:44:45.61377       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:639:in `single_record'
2015-09-08_15:44:45.61378       from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:191:in `first'
2015-09-08_15:44:45.61379       from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/org.rb:28:in `last_seq'
2015-09-08_15:44:45.61379       from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/orgsyncer.rb:114:in `bootstrap_required?'
2015-09-08_15:44:45.61380       from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/orgsyncer.rb:52:in `start'
2015-09-08_15:44:45.61380       from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:114:in `block in start_worker'
2015-09-08_15:44:45.61381       from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:110:in `fork'
2015-09-08_15:44:45.61382       from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:110:in `start_worker'
2015-09-08_15:44:45.61382       from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:191:in `block in handle_command_connection'
2015-09-08_15:44:45.61385       from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:163:in `loop'
2015-09-08_15:44:45.61386       from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:163:in `handle_command_connection'
2015-09-08_15:44:45.61386       from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:139:in `block (3 levels) in manage'
2015-09-08_15:44:45.62049 I, [2015-09-08T17:44:45.620360 #5871]  INFO -- : Worker for fyber died unexpectedly!
2015-09-08_15:44:47.78260 I, [2015-09-08T17:44:47.782487 #5871]  INFO -- : ec_sync_client: starting new command connection handler
```
The ec_sync_user.pem is the same for the master and the replica.
Did someone have the same issue?

**Comment by marcparadise** [comment]
Hi @albsOps, I'm sorry to hear you ran into this trouble. I took a look, and it appears that this is a side effect of the changes we made in Chef Server 12.2+ to support external postgresql. 

I have an update building now - if you wouldn't mind trying it out, I can post a link to it once it's ready.

**Comment by marcparadise** [comment]
The changes in question are in this PR: https://github.com/chef/omnibus-sync/pull/13

**Comment by albsOps** [comment]
Sure, I will be very happy trying it out. Thanks for your response.

**Comment by marcparadise** [comment]
I'm not sure what platform you're on, but if you head over to the  [https://packagecloud.io/chef/current](package cloud - chef/current) site, and paste this into the search box, it will show you the platform-specific builds that contain the fix:  1.0.0-rc.6+20150909122022

Once you verify this, we'll be able to promote it as the next RC of chef-sync.

**Comment by albsOps** [comment]
I can confirm that is working perfectly now!
Thank you very much @marcparadise for the fast response and the quick fix.

**Comment by marcparadise** [comment]
Excellent, glad to hear it! I'm going to close this out and we'll get the release tagged and out the door.
