### ISSUE TITLE
nginx won't start post installation

### ISSUE THREAD

**Issue by meson10** [chef/chef-server#595]
```
================================================================================
    Error executing action `restart` on resource 'runit_service[nginx]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
    STDOUT: fail: /opt/opscode/service/nginx: unable to change to service directory: file does not exist
    STDERR: 
    ---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
    Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx returned 1
    
    Cookbook Trace:
    ---------------
    /opt/opscode/embedded/cookbooks/cache/cookbooks/runit/libraries/provider_runit_service.rb:184:in `restart_service'
    
    Resource Declaration:
    ---------------------
    # In /opt/opscode/embedded/cookbooks/cache/cookbooks/enterprise/definitions/component_runit_service.rb
    
     37:   runit_service component do
     38:     action :enable
     39:     retries 20
     40:     control params[:control] if params[:control]
     41:     options(
     42:       :log_directory => log_directory
     43:     )
     44:     params[:runit_attributes].each do |attr_name, attr_value|
     45:       send(attr_name.to_sym, attr_value)
     46:     end
     47:   end
     48: 
    
    Compiled Resource:
    ------------------
    # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/enterprise/definitions/component_runit_service.rb:37:in `block in from_file'
    
    runit_service("nginx") do
      params {:package=>"private_chef", :log_directory=>nil, :svlogd_size=>nil, :svlogd_num=>nil, :ha=>nil, :control=>nil, :runit_attributes=>{}, :action=>:enable, :name=>"nginx"}
      provider Chef::Provider::Service::Runit
      action [:enable]
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 20
      retry_delay 2
      default_guard_interpreter :default
      service_name "nginx"
      pattern "nginx"
      status_command "/opt/opscode/embedded/bin/sv status /opt/opscode/service"
      sv_bin "/opt/opscode/embedded/bin/sv"
      sv_dir "/opt/opscode/sv"
      service_dir "/opt/opscode/service"
      lsb_init_dir "/opt/opscode/init"
      options {:log_directory=>"/var/log/opscode/nginx"}
      log true
      restart_on_update true
      run_template_name "nginx"
      log_template_name "nginx"
      check_script_template_name "nginx"
      finish_script_template_name "nginx"
      sv_templates true
      service_mirror # Declared in 
    
    service("nginx") do
      provider Chef::Provider::Service::Simple
      action [:nothing]
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "nginx"
      pattern "nginx"
      start_command "/opt/opscode/embedded/bin/sv start /opt/opscode/service/nginx"
      stop_command "/opt/opscode/embedded/bin/sv stop /opt/opscode/service/nginx"
      status_command "/opt/opscode/embedded/bin/sv status /opt/opscode/service/nginx"
      restart_command "/opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx"
    end
    
      declared_type :runit_service
      cookbook_name "private-chef"
      recipe_name "nginx"
    end
```

**Comment by marcparadise** [comment]
Hi @meson1, sorry to hear that you're having troubles.   From what I am seeing here I think there is probably an error that occurred earlier in the reconfigure.  Could you check further up in the backscroll?

Also, what version are you installing, and on what platform?

**Comment by meson10** [comment]
I am installing 12.2.0-1 on Ubuntu 14.04. Yeah I see something like this on scrollback

```
================================================================================
    Error executing action `run` on resource 'execute[bootstrap-platform]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----
    STDOUT: 
    STDERR: /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Connection refused - connect(2) for "127.0.0.1" port 9463 (Errno::ECONNREFUSED)
    	from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `open'
    	from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
    	from /opt/opscode/embedded/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
    	from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:878:in `connect'
    	from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
    	from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
    	from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:206:in `transmit'
    	from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:68:in `execute'
    	from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:35:in `execute'
    	from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient.rb:74:in `post'
    	from ./bin/bootstrap-platform:101:in `create_object_in_authz'
    	from ./bin/bootstrap-platform:47:in `bootstrap'
    	from ./bin/bootstrap-platform:120:in `<main>'
    ---- End output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----
    Ran /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml returned 1
    
    Resource Declaration:
    ---------------------
    # In /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/bootstrap.rb
    
     45: execute "bootstrap-platform" do
     46:   command "/opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml"
     47:   cwd opscode_test_dir
     48:   not_if { OmnibusHelper.has_been_bootstrapped? }
     49:   notifies :restart, 'service[opscode-erchef]'
     50: end
     51: 
    
    Compiled Resource:
    ------------------
    # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/bootstrap.rb:45:in `from_file'
    
    execute("bootstrap-platform") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :execute
      command "/opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml"
      backup 5
      cwd "/opt/opscode/embedded/service/chef-server-bootstrap"
      returns 0
      declared_type :execute
      cookbook_name "private-chef"
      recipe_name "bootstrap"
      not_if { #code block }
    end
```

Does that give any clues?

**Comment by marcparadise** [comment]
Thanks for the additional details @meson10. It looks like this is the same issue as #584 - I'm goignt o close this one, and we'll track further updates there.

**Comment by meson10** [comment]
Alright. Makes sense.
