### ISSUE TITLE
Error executing action `run` on resource 'execute[bootstrap-platform]'

### ISSUE THREAD

**Issue by meson10** [chef/chef-server#598]
```
================================================================================
    Error executing action `run` on resource 'execute[bootstrap-platform]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----
    STDOUT: 
    STDERR: /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Connection refused - connect(2) for "127.0.0.1" port 9463 (Errno::ECONNREFUSED)
    	from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `open'
    	from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
    	from /opt/opscode/embedded/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
    	from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:878:in `connect'
    	from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
    	from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
    	from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:206:in `transmit'
    	from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:68:in `execute'
    	from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:35:in `execute'
    	from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient.rb:74:in `post'
    	from ./bin/bootstrap-platform:101:in `create_object_in_authz'
    	from ./bin/bootstrap-platform:47:in `bootstrap'
    	from ./bin/bootstrap-platform:120:in `<main>'
    ---- End output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----
    Ran /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml returned 1
    
    Resource Declaration:
    ---------------------
    # In /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/bootstrap.rb
    
     45: execute "bootstrap-platform" do
     46:   command "/opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml"
     47:   cwd opscode_test_dir
     48:   not_if { OmnibusHelper.has_been_bootstrapped? }
     49:   notifies :restart, 'service[opscode-erchef]'
     50: end
     51: 
    
    Compiled Resource:
    ------------------
    # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/bootstrap.rb:45:in `from_file'
    
    execute("bootstrap-platform") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :execute
      command "/opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml"
      backup 5
      cwd "/opt/opscode/embedded/service/chef-server-bootstrap"
      returns 0
      declared_type :execute
      cookbook_name "private-chef"
      recipe_name "bootstrap"
      not_if { #code block }
    end
    
Recipe: private-chef::rabbitmq
  * execute[restart_rabbitmq_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/rabbitmq/log
Recipe: private-chef::oc_bifrost
  * runit_service[oc_bifrost] action restart
    - restart service runit_service[oc_bifrost]
  * execute[restart_oc_bifrost_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/oc_bifrost/log
Recipe: private-chef::oc_id
  * runit_service[oc_id] action restart
    - restart service runit_service[oc_id]
  * execute[restart_oc_id_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/oc_id/log
Recipe: private-chef::nginx
  * runit_service[nginx] action restart
    
    ================================================================================
    Error executing action `restart` on resource 'runit_service[nginx]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
    STDOUT: fail: /opt/opscode/service/nginx: unable to change to service directory: file does not exist
    STDERR: 
    ---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
    Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx returned 1
    
    Cookbook Trace:
    ---------------
    /opt/opscode/embedded/cookbooks/cache/cookbooks/runit/libraries/provider_runit_service.rb:184:in `restart_service'
    
    Resource Declaration:
    ---------------------
    # In /opt/opscode/embedded/cookbooks/cache/cookbooks/enterprise/definitions/component_runit_service.rb
    
     37:   runit_service component do
     38:     action :enable
     39:     retries 20
     40:     control params[:control] if params[:control]
     41:     options(
     42:       :log_directory => log_directory
     43:     )
     44:     params[:runit_attributes].each do |attr_name, attr_value|
     45:       send(attr_name.to_sym, attr_value)
     46:     end
     47:   end
     48: 
    
    Compiled Resource:
    ------------------
    # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/enterprise/definitions/component_runit_service.rb:37:in `block in from_file'
    
    runit_service("nginx") do
      params {:package=>"private_chef", :log_directory=>nil, :svlogd_size=>nil, :svlogd_num=>nil, :ha=>nil, :control=>nil, :runit_attributes=>{}, :action=>:enable, :name=>"nginx"}
      provider Chef::Provider::Service::Runit
      action [:enable]
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 20
      retry_delay 2
      default_guard_interpreter :default
      service_name "nginx"
      pattern "nginx"
      status_command "/opt/opscode/embedded/bin/sv status /opt/opscode/service"
      sv_bin "/opt/opscode/embedded/bin/sv"
      sv_dir "/opt/opscode/sv"
      service_dir "/opt/opscode/service"
      lsb_init_dir "/opt/opscode/init"
      options {:log_directory=>"/var/log/opscode/nginx"}
      log true
      restart_on_update true
      run_template_name "nginx"
      log_template_name "nginx"
      check_script_template_name "nginx"
      finish_script_template_name "nginx"
      sv_templates true
      service_mirror # Declared in 
    
    service("nginx") do
      provider Chef::Provider::Service::Simple
      action [:nothing]
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "nginx"
      pattern "nginx"
      start_command "/opt/opscode/embedded/bin/sv start /opt/opscode/service/nginx"
      stop_command "/opt/opscode/embedded/bin/sv stop /opt/opscode/service/nginx"
      status_command "/opt/opscode/embedded/bin/sv status /opt/opscode/service/nginx"
      restart_command "/opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx"
    end
    
      declared_type :runit_service
      cookbook_name "private-chef"
      recipe_name "nginx"
    end
    
Recipe: private-chef::opscode-solr4
  * runit_service[opscode-solr4] action restart
    - restart service runit_service[opscode-solr4]
  * execute[restart_opscode-solr4_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/opscode-solr4/log
Recipe: private-chef::opscode-expander
  * runit_service[opscode-expander] action restart
    - restart service runit_service[opscode-expander]
  * runit_service[opscode-expander-reindexer] action restart
    - restart service runit_service[opscode-expander-reindexer]
  * execute[restart_opscode-expander_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/opscode-expander/log
  * execute[restart_opscode-expander-reindexer_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/opscode-expander-reindexer/log
Recipe: private-chef::opscode-erchef
  * runit_service[opscode-erchef] action restart
    - restart service runit_service[opscode-erchef]
  * execute[restart_opscode-erchef_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/opscode-erchef/log

Running handlers:
[2015-11-02T19:38:17+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-11-02T19:38:17+00:00] ERROR: Exception handlers complete
Chef Client failed. 200 resources updated in 123.025225485 seconds
[2015-11-02T19:38:17+00:00] FATAL: Stacktrace dumped to /opt/opscode/embedded/cookbooks/cache/chef-stacktrace.out
[2015-11-02T19:38:17+00:00] FATAL: Chef::Exceptions::MultipleFailures: Multiple failures occurred:
* Mixlib::ShellOut::ShellCommandFailed occurred in chef run: execute[bootstrap-platform] (private-chef::bootstrap line 45) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----
STDOUT: 
STDERR: /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Connection refused - connect(2) for "127.0.0.1" port 9463 (Errno::ECONNREFUSED)
	from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `open'
	from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
	from /opt/opscode/embedded/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
	from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:878:in `connect'
	from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:206:in `transmit'
	from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:68:in `execute'
	from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:35:in `execute'
	from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient.rb:74:in `post'
	from ./bin/bootstrap-platform:101:in `create_object_in_authz'
	from ./bin/bootstrap-platform:47:in `bootstrap'
	from ./bin/bootstrap-platform:120:in `<main>'
---- End output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----
Ran /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml returned 1
* Mixlib::ShellOut::ShellCommandFailed occurred in delayed notification: runit_service[nginx] (private-chef::nginx line 37) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
STDOUT: fail: /opt/opscode/service/nginx: unable to change to service directory: file does not exist
STDERR: 
---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx returned 1
```

**Comment by meson10** [comment]
Installing https://web-dl.packagecloud.io/chef/stable/packages/ubuntu/trusty/chef-server-core_12.2.0-1_amd64.deb on Ubuntu 14.04

**Comment by marcparadise** [comment]
Thanks @meson10 - though this does look like the same issue we talked about earlier, that we're covering in https://github.com/chef/chef-server/issues/584?

**Comment by meson10** [comment]
Yeah but that thread suggests that It could get resolved with a few retries. I am able to reproduce this on every single run.

**Comment by marcparadise** [comment]
He was saying that if we add a retry to the execute resource that's trying to run `bootstrap`, it will resolve as it apparently gives time for the bifrost service to come online.  It's not clear yet why it's not coming online in time (these recent reports are the first we're hearing that sometimes it doesn't), and so that issue is being left open while we look into that. 

Your having a reproducible case is definitely helpful. Let's keep the conversation in that issue though, so that we can track it in one place.

**Comment by meson10** [comment]
:+1:

**Comment by vish123al** [comment]
i got this error during executing dcos cookbook

    [execute] /usr/bin/docker-current: Error response from daemon: driver failed programming external connectivity on endpoint dcos-genconf.a5ecc9af5d9ca903f5-ff88379126df825594.tar (e7df26b9b210f2f7fa2c25e63929dae7d8e151303633a299815e27fea19516e4): Bind for 0.0.0.0:9000 failed: port is already allocated.

    ================================================================================
    Error executing action `run` on resource 'execute[dcos-genconf]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '125'
    ---- Begin output of /usr/src/dcos/dcos_generate_config.sh --genconf ----
    STDOUT:
    STDERR: /usr/bin/docker-current: Error response from daemon: driver failed programming external connectivity on endpoint dcos-genconf.a5ecc9af5d9ca903f5-ff88379126df825594.tar (e7df26b9b210f2f7fa2c25e63929dae7d8e151303633a299815e27fea19516e4): Bind for 0.0.0.0:9000 failed: port is already allocated.
    ---- End output of /usr/src/dcos/dcos_generate_config.sh --genconf ----
    Ran /usr/src/dcos/dcos_generate_config.sh --genconf returned 125

    Resource Declaration:
    ---------------------
    # In /root/chef-repo/.chef/local-mode-cache/cache/cookbooks/dcos/recipes/default.rb

     71: execute 'dcos-genconf' do
     72:   command '/usr/src/dcos/dcos_generate_config.sh --genconf'
     73:   user 'root'
     74:   cwd '/usr/src/dcos'
     75:   creates '/usr/src/dcos/genconf/cluster_packages.json'
     76: end
     77:

    Compiled Resource:
    ------------------
    # Declared in /root/chef-repo/.chef/local-mode-cache/cache/cookbooks/dcos/recipes/default.rb:71:in `from_file'

    execute("dcos-genconf") do
      action [:run]
      default_guard_interpreter :execute
      command "/usr/src/dcos/dcos_generate_config.sh --genconf"
      backup 5
      creates "/usr/src/dcos/genconf/cluster_packages.json"
      cwd "/usr/src/dcos"
      returns 0
      user "root"
      declared_type :execute
      cookbook_name "dcos"
      recipe_name "default"
      domain nil
    end

    System Info:
    ------------
    chef_version=13.4.19
    platform=centos
    platform_version=7.4.1708
    ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
    program_name=chef-client worker: ppid=28423;start=00:58:41;
    executable=/opt/chefdk/bin/chef-client

[2017-11-17T00:59:03-05:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2017-11-17T00:59:03-05:00] ERROR: Running exception handlers
Running handlers complete
[2017-11-17T00:59:03-05:00] ERROR: Exception handlers complete
Chef Client failed. 2 resources updated in 21 seconds
[2017-11-17T00:59:03-05:00] FATAL: Stacktrace dumped to /root/chef-repo/.chef/local-mode-cache/cache/chef-stacktrace.out
[2017-11-17T00:59:03-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-11-17T00:59:03-05:00] ERROR: execute[dcos-genconf] (dcos::default line 71) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '125'
---- Begin output of /usr/src/dcos/dcos_generate_config.sh --genconf ----
STDOUT:
STDERR: /usr/bin/docker-current: Error response from daemon: driver failed programming external connectivity on endpoint dcos-genconf.a5ecc9af5d9ca903f5-ff88379126df825594.tar (e7df26b9b210f2f7fa2c25e63929dae7d8e151303633a299815e27fea19516e4): Bind for 0.0.0.0:9000 failed: port is already allocated.
---- End output of /usr/src/dcos/dcos_generate_config.sh --genconf .


any one plz help

**Comment by stevendanna** [comment]
@vish123al Sorry that you've hit this problem, but from your error output it looks like this is a problem with a specific cookbook and not the chef-server.  We use this GitHub bug tracker to track bugs and feature requests with the Chef Server

You might have better luck on the mailing list. You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community).
