### ISSUE TITLE
chef FATAL: Net::HTTPServerException: 403 "Forbidden"

### ISSUE THREAD

**Issue by gokulnath** [chef/chef-server#63]
Towards the end of my chef-client run, the following error appears (sudo chef-client -l debug)

```
[2015-01-16T06:56:37+00:00] DEBUG: Saving the current state of node vas-netmagic-cloud-git-deploy
[2015-01-16T06:56:37+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
[2015-01-16T06:56:37+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_request
[2015-01-16T06:56:37+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
[2015-01-16T06:56:37+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
[2015-01-16T06:56:37+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
[2015-01-16T06:56:37+00:00] DEBUG: Signing the request as vas-netmagic-cloud-git-deploy
[2015-01-16T06:56:37+00:00] DEBUG: String to sign: 'Method:PUT
Hashed Path:O9nOlTTP4Om5QeHdkq8Iu0qTqF8=
X-Ops-Content-Hash:1Nt/7y3OeEbJRPxqc2E/xz+XcvY=
X-Ops-Timestamp:2015-01-16T06:56:37Z
X-Ops-UserId:vas-netmagic-cloud-git-deploy'
Header hash: {"X-Ops-Sign"=>"algorithm=sha1;version=1.0;", "X-Ops-Userid"=>"vas-netmagic-cloud-git-deploy", "X-Ops-Timestamp"=>"2015-01-16T06:56:37Z", "X-Ops-Content-Hash"=>"contenthash", "X-Ops-Authorization-1"=>"authorization-hash", "X-Ops-Authorization-2"=>"authorization-hash", "X-Ops-Authorization-3"=>"authorization-hash", "X-Ops-Authorization-4"=>"aurhorization-hash", "X-Ops-Authorization-5"=>"anotherhash", "X-Ops-Authorization-6"=>"last hash :)"}
[2015-01-16T06:56:37+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
[2015-01-16T06:56:37+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
[2015-01-16T06:56:37+00:00] DEBUG: Initiating PUT to https://chef.mobme.in/nodes/vas-netmagic-cloud-git-deploy
[2015-01-16T06:56:37+00:00] DEBUG: ---- HTTP Request Header Data: ----
[2015-01-16T06:56:37+00:00] DEBUG: Content-Type: application/json
[2015-01-16T06:56:37+00:00] DEBUG: Accept: application/json
[2015-01-16T06:56:37+00:00] DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
[2015-01-16T06:56:37+00:00] DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.0;
[2015-01-16T06:56:37+00:00] DEBUG: X-OPS-USERID: vas-netmagic-cloud-git-deploy
[2015-01-16T06:56:37+00:00] DEBUG: X-OPS-TIMESTAMP: 2015-01-16T06:56:37Z
[2015-01-16T06:56:37+00:00] DEBUG: X-OPS-CONTENT-HASH: 1Nt/7y3OeEbJRPxqc2E/xz+XcvY=
[2015-01-16T06:56:37+00:00] DEBUG: X-OPS-AUTHORIZATION-1: 
authorizationhash
[2015-01-16T06:56:37+00:00] DEBUG: X-OPS-AUTHORIZATION-2: 
authorizationhash
[2015-01-16T06:56:37+00:00] DEBUG: X-OPS-AUTHORIZATION-3: 
authorizationhash
[2015-01-16T06:56:37+00:00] DEBUG: X-OPS-AUTHORIZATION-4: authorizationhash
[2015-01-16T06:56:37+00:00] DEBUG: X-OPS-AUTHORIZATION-5: authorizationhash
[2015-01-16T06:56:37+00:00] DEBUG: X-OPS-AUTHORIZATION-6: authorizationhash
[2015-01-16T06:56:37+00:00] DEBUG: HOST: chef.mobme.in:443
[2015-01-16T06:56:37+00:00] DEBUG: X-REMOTE-REQUEST-ID: bd99e189-21c3-4ee0-a563-ba2f4b5c9136
[2015-01-16T06:56:37+00:00] DEBUG: Content-Length: 71537
[2015-01-16T06:56:37+00:00] DEBUG: ---- End HTTP Request Header Data ----
[2015-01-16T06:56:37+00:00] DEBUG: ---- HTTP Status and Header Data: ----
[2015-01-16T06:56:37+00:00] DEBUG: HTTP 1.1 403 Forbidden
[2015-01-16T06:56:37+00:00] DEBUG: server: ngx_openresty/1.4.3.6
[2015-01-16T06:56:37+00:00] DEBUG: date: Fri, 16 Jan 2015 06:56:37 GMT
[2015-01-16T06:56:37+00:00] DEBUG: content-length: 39
[2015-01-16T06:56:37+00:00] DEBUG: connection: close
[2015-01-16T06:56:37+00:00] DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=0.29.4
[2015-01-16T06:56:37+00:00] DEBUG: ---- End HTTP Status/Header Data ----
[2015-01-16T06:56:37+00:00] DEBUG: ---- HTTP Response Body ----
[2015-01-16T06:56:37+00:00] DEBUG: {"error":["missing update permission"]}
[2015-01-16T06:56:37+00:00] DEBUG: ---- End HTTP Response Body -----
[2015-01-16T06:56:37+00:00] DEBUG: ---- HTTP Request Body ----
[2015-01-16T06:56:37+00:00] DEBUG: { "content" :
  "A big JSON }
[2015-01-16T06:56:37+00:00] DEBUG: ---- End HTTP Request Body ----
[2015-01-16T06:56:37+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
[2015-01-16T06:56:37+00:00] DEBUG: Content-Length validated correctly.
[2015-01-16T06:56:37+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
[2015-01-16T06:56:37+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
[2015-01-16T06:56:37+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
[2015-01-16T06:56:37+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
[2015-01-16T06:56:37+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_response
[2015-01-16T06:56:37+00:00] DEBUG: Expected JSON response, but got content-type ''
[2015-01-16T06:56:37+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
[2015-01-16T06:56:37+00:00] INFO: HTTP Request Returned 403 Forbidden: error
[2015-01-16T06:56:37+00:00] DEBUG: Re-raising exception: Net::HTTPServerException - 403 "Forbidden"
/opt/chef/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
  /opt/chef/embedded/apps/chef/lib/chef/http.rb:145:in `request'
  /opt/chef/embedded/apps/chef/lib/chef/http.rb:118:in `put'
  /opt/chef/embedded/apps/chef/lib/chef/node.rb:512:in `save'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:257:in `save_updated_node'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:403:in `run'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:355:in `block in interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:345:in `loop'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:345:in `interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:335:in `run_application'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
  /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:40:in `load'
  /usr/bin/chef-client:40:in `<main>'

Running handlers:
[2015-01-16T06:56:37+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-01-16T06:56:37+00:00] ERROR: Exception handlers complete
[2015-01-16T06:56:37+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-01-16T06:56:37+00:00] DEBUG: Net::HTTPServerException: 403 "Forbidden"
/opt/chef/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:145:in `request'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:118:in `put'
/opt/chef/embedded/apps/chef/lib/chef/node.rb:512:in `save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:257:in `save_updated_node'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:403:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:355:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:345:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:345:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:335:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:40:in `load'
/usr/bin/chef-client:40:in `<main>'
Chef Client failed. 6 resources updated in 68.290737107 seconds
[2015-01-16T06:56:37+00:00] DEBUG: Server doesn't support resource history, skipping resource report.
[2015-01-16T06:56:38+00:00] ERROR: 403 "Forbidden"
[2015-01-16T06:56:38+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

I suspect this can be solved with https://docs.chef.io/errors.html#forbidden. But I don't have chef management console. Can I fix this with knife or by any other way.

BTW, this issue started appearing after my upgrade from chef 11.0.8 to 12.0.1

**Comment by stevendanna** [comment]
Thanks for the report @gokulnath.  Let's start by investigating the ACLs for the node in question.  Can you run the following knife command (as an admin user):

```
knife show /acls/nodes/NODENAME.json
```

Replacing NODENAME for the name of the node that is failing in the stacktrace above and post the output here?  That command will dump the JSON representation of the node's access control list (ACL).

**Comment by gokulnath** [comment]
I guess there's something wrong. I am getting: 
```
ERROR: /acls/nodes/MYNODENAME.json: No such file or directory
```

**Comment by russss** [comment]
We had this happen after re-creating a machine by deleting the client and then re-provisioning (while maintaining the existing node). 

Since Chef 12 has ACLs, the client needs to have permission to update its own node. If the client and the node are created simultaneously, this gets correctly set. If a new client is created for an existing node, it isn't.

The fix is to install the [knife-acl](https://github.com/chef/knife-acl) gem and then run:

    knife acl add nodes NODENAME update client NODENAME

(I also had the same issue with `knife show` not working as above.)

**Comment by stevendanna** [comment]
@gokulnath Is this still an issue for you?

**Comment by jakshi** [comment]
I have the same issue with hosted chef.

**Comment by gokulnath** [comment]
This is what I get.
% knife acl add nodes gokul-vagrant update client gokul-vagrant
ffi-yajl/json_gem is deprecated, these monkeypatches will be dropped shortly

```
ERROR: The data in your request was invalid
Response: <html><head><title>400 Bad Request</title></head><body><h1>Bad Request</h1>Bad Request<p><hr><address>mochiweb+webmachine web server</address></body></html>
```

**Comment by stevendanna** [comment]
@gokulnath The 400 likely indicates that either the client or node gokkul-vagrant doesn't exist.  You should be able to tell which with `knife node show gokul-vagrant` and `knife client show gokul-vagrant`.  If the node doesn't exist, try creating the node, running the knife-acl command again, and then running chef-client.  If the client doesn't exist, try removing /etc/chef/client.pem from the chef node and then letting the validation client recreate it.

@jakshi If you are having a similar issue on Hosted Chef, please contact support@chef.io; they can help you out.

**Comment by wojnosystems** [comment]
@stevendanna you beautiful man. I saw that the ACL's were registered to me and not the server client. I added that in to the PUT permission using:

```
knife edit /acls/nodes/MYNODENAME.json
```

and fixed that up without a problem. You rock!

**Comment by pelletiermaxime** [comment]
I fixed it for all my nodes by downloading their acls, adding the line with sed and then reuploading:

```
knife download /acls/nodes
sed -i '31i "clients",' *.json
knife upload /acls/nodes
```

There's probably less hacky ways to do it, but this worked for me, so I tought I'd share for anyone having this problem after upgrading to chef server 12.

**Comment by pepov** [comment]
The knife acl command should work, however not with 1.0.0.beta, try using 0.0.12 (and upgrade knife of course).

If you are OK letting all clients update any node, than you can use:
```
knife acl add containers nodes update group clients
```

**Comment by e100** [comment]
I ran into this problem after upgrading to Chef 12, chef-server-ctl upgrade failed forcing me to massage the data and import everything manually.

Comparing the working vs non-working, the broken nodes did not have permissions to update themselves like @russss pointed out above.

I downloaded the acls, fixed the broken json and re-uploaded them:
```
knife download /acls/nodes
cd /path/to/acls/nodes
ls *.json -1|sed 's/\.json//'|awk '{print "grep -L " $1 " " $1 ".json"}'|sh|sed 's/\.json//'|awk '{print "sed -i \47s/pivotal\"/pivotal\",\\n      \"" $1 "\"/\47 " $1 ".json"}'|sh
knife upload /acls/nodes
```

**Comment by JohnMorales** [comment]
@pepov that solves it for new nodes, but you need to update the ACEs of the existing nodes:

`knife acl bulk add group clients nodes '.*' update,read`

this one liner is effectively what @e100  is doing with his sed/awk/sh/sed/awk/sh pipeline.

**Comment by CVTJNII** [comment]
I hit this by preconfiguring a node with 'knife node from file' before the initial chef-run, with the intention of having the run list and node attributes already populated when the node came online.  The result was the node converged as expected but hit this 403 at the end of the run, resulting in client failures and bad node state data in the chef server.

**Comment by popsikle** [comment]
I ran into this when dealing with a chef-11 to chef-12 migration.

```for n in $(knife status | cut -f2 -d','); do knife acl add nodes ${n} update client ${n}; done```

Was slow but worked to update all the client / node acls.

**Comment by RossHarvey** [comment]
If you knew this was going to happen you could just backup the acls first. In one case I lucked out, my old workstation knife dir was still pointing at the old server.

So I only had to:
```bash
oldws: knife download /acls/nodes
oldws: scp -r acls/nodes newws:acls/.
newws: knife upload   /acls/nodes
```

It's a rather complex bug for lots of people to deal with and the error message is crude exception fallout.

I believe this has happened to me when
* Renaming a node
* Restoring a backup

**Comment by chewi** [comment]
Here's my version!

```
knife download /acls/nodes
cd /path/to/acls/nodes
ls | xargs -I{} sh -c 'X={}; sed -i "s/yourusername/${X%.json}/g" {}'
knife upload /acls/nodes
```

**Comment by albeekj** [comment]
How was "ERROR: acls/nodes/MYNODENAME.json: No such file or directory" solved?  After my upgrade I get that error and when I try knife download /acls it gives me a nil error too.  I tried installing the knife-acl, however the latest version disallows "knife acl add nodes NODENAME update client NODENAME"  When i install knife-acl 0.0.12 it gives an error of unexpected response...  My acls seem totally broken.  Any help would be much appreciated.

**Comment by albeekj** [comment]
in chef 11, should I do a "knife upload /acls" to make sure they are in place?

**Comment by vskubriev** [comment]
Dear @JohnMorales
Thank you for a tip.

**Comment by r4hulgupta** [comment]
@CVTJNII I have the same issue, I am using `machine` resource to create the node and bootstrapping is done by the client itself and I am hitting the same problem where the client does not seem to have write permissions to update its object on the Chef Server. Is there a way to set it for all new clients when they run for the first time?

**Comment by cheeseplus** [comment]
This issue was resolved long ago and is almost always ACL related, closing.
