### ISSUE TITLE
nginx_status settings not working

### ISSUE THREAD

**Issue by chilicheech** [chef/chef-server#633]
I followed the instructions here https://github.com/chef/chef-server/blob/12.3.0/RELEASE_NOTES.md#nginx and got the following error when reconfiguring:
```
$ sudo chef-server-ctl reconfigure
Starting Chef Client, version 12.5.1
resolving cookbooks for run list: ["private-chef::default"]
Synchronizing Cookbooks:
  - private-chef (0.1.0)
  - yum (3.6.1)
  - enterprise (0.5.1)
  - apt (2.7.0)
  - runit (1.6.0)
  - openssl (4.4.0)
  - chef-sugar (3.1.1)
  - packagecloud (0.0.18)
Compiling Cookbooks...
Recipe: private-chef::default
  * directory[/etc/opscode] action create (up to date)
  * directory[/etc/opscode/logrotate.d] action create (up to date)

  ================================================================================
  Recipe Compile Error in /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/default.rb
  ================================================================================

  RuntimeError
  ------------
  Error loading file: /etc/opscode/chef-server.rb:52:in `from_file': undefined method `[]=' for nil:NilClass

  Cookbook Trace:
  ---------------
    /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/libraries/private_chef.rb:111:in `rescue in from_file'
    /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/libraries/private_chef.rb:108:in `from_file'
    /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/config.rb:75:in `from_file'
    /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/default.rb:38:in `from_file'


  Relevant File Content:
  ----------------------
  /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/libraries/private_chef.rb:

  104:        # the reconfigure chef run; we don't particularly care what line in the chef
  105:        # recipes is failing to evaluate the loaded file (in the case of what
  106:        # originally triggered this, private_chef.rb), what we care about is which
  107:        # line in the loaded file is causing the error.
  108:        begin
  109:          self.instance_eval(IO.read(filename), filename, 1)
  110:        rescue
  111>>         raise "Error loading file: #{$!.backtrace[0]}: #{$!.message}"
  112:        end
  113:      end
  114:
  115:      def import_legacy_service_config(old_service_key, new_service_key, keys)
  116:        keys.each do |configkey|
  117:          if PrivateChef[old_service_key].has_key? configkey
  118:            PrivateChef[new_service_key][configkey] ||= PrivateChef[old_service_key][configkey]
  119:            PrivateChef[old_service_key].delete configkey
  120:          end


  Running handlers:
[2015-11-19T22:36:33+00:00] ERROR: Running exception handlers
  Running handlers complete
[2015-11-19T22:36:33+00:00] ERROR: Exception handlers complete
  Chef Client failed. 0 resources updated in 03 seconds
[2015-11-19T22:36:33+00:00] FATAL: Stacktrace dumped to /opt/opscode/embedded/cookbooks/cache/chef-stacktrace.out
[2015-11-19T22:36:33+00:00] FATAL: RuntimeError: Error loading file: /etc/opscode/chef-server.rb:52:in `from_file': undefined method `[]=' for nil:NilClass
$
```
The chef-server.rb file has the following snippet with line number prepended to the line:
```
     51 nginx['enable_stub_status'] = true
     52 nginx['stub_status']['listen_host'] = "127.0.0.1"
     53 nginx['stub_status']['listen_port'] = "9999"
     54 nginx['stub_status']['location'] = "/nginx_status"
```
What gives? If I add `nginx['stub_status'] = {}` before line 52 I can reconfigure fine. But when I browse to https://my_awesome_chef_server_url:9999/nginx_status I get a 404.

I've also tried to reconfigure opscode-manage-ctl and to restart both chef-server-ctl and opscode-manage-ctl.

What gives?

Also, why are these attributes not documented here: https://docs.chef.io/config_rb_server.html ?

**Comment by stevendanna** [comment]
Thanks for the report!

> What gives?

The config-file parsing is not as robust as we would like at the moment.  I'll get the RELEASE_NOTES updated to point people towards a config entry that'll work on the firs try.

> But when I browse to https://my_awesome_chef_server_url:9999/nginx_status I get a 404.

If my_awesome_chef_server_url resolves to an IP different from 127.0.0.1, you'll need to configure listen_host to listen on that IP as well.  By default the configuration only listens on localhost and thus won't respond to requests on other IPs.  Might that be the issue?

> Also, why are these attributes not documented here: https://docs.chef.io/config_rb_server.html ?

Looking into it.  Once it is sorted the place to find smaller options like this is on this page:

https://docs.chef.io/config_rb_server_optional_settings.html#nginx

**Comment by chilicheech** [comment]
Awesome, thanks for the quick reply @stevendanna. I changed the IP to the IP the hostname resolves to and when I hit it I get this error:
```
$ curl -v https://my_awesome_chef_server_url:9999/nginx_status
*   Trying x.x.x.x...
* Connected to my_awesome_chef_server_url (x.x.x.x) port 9999 (#0)
* Unknown SSL protocol error in connection to my_awesome_chef_server_url:-9847
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to my_awesome_chef_server_url:-9847
```
It actually responds with that for any of the endpoints. Same on a browser. I can't even log in.

**Comment by stevendanna** [comment]
I believe the nginx_status endpoint is only served over http at the moment.

> Same on a browser. I can't even log in.

I'd have to see the logs as the management console should definitely be served over https.

**Comment by chilicheech** [comment]
Ok, I got the endpoint to work, but all the other endpoints on https are still failing with that ssl protocol error. I'm looking for stuff in the logs. BTW, I'm only setting this on the FE, not the BE. Should it be set on the BE too?

**Comment by chilicheech** [comment]
Ok, so, if I have the FE's listening on port 9999 with https and I add the nginx_status config to also listen on 9999 it breaks the https server. However, if I set the nginx_status port to a different port, say 9998, both servers work.

If it's not intended to work on the same port as the https server this should be documented.
