### ISSUE TITLE
Error with default settings for bootstrap

### ISSUE THREAD

**Issue by dukecovidien** [chef/chef-server#684]
* execute[bootstrap-platform] action run

    ================================================================================
    Error executing action `run` on resource 'execute[bootstrap-platform]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----
    STDOUT:
    STDERR: /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Connection refused - connect(2) for "127.0.0.1" port 9463 (Errno::ECONNREFUSED)
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `open'
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
        from /opt/opscode/embedded/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:878:in `connect'
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:206:in `transmit'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:68:in `execute'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:35:in `execute'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient.rb:74:in `post'
        from ./bin/bootstrap-platform:101:in `create_object_in_authz'
        from ./bin/bootstrap-platform:47:in `bootstrap'
        from ./bin/bootstrap-platform:120:in `<main>'
    ---- End output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----
    Ran /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml returned 1

    Resource Declaration:
    ---------------------
    # In /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/bootstrap.rb

     45: execute "bootstrap-platform" do
     46:   command "/opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml"
     47:   cwd opscode_test_dir
     48:   retries 3
     49:   not_if { OmnibusHelper.has_been_bootstrapped? }
     50:   notifies :restart, 'service[opscode-erchef]'
     51: end
     52:

    Compiled Resource:
    ------------------
    # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/bootstrap.rb:45:in `from_file'

    execute("bootstrap-platform") do
      action [:run]
      retries 3
      retry_delay 2
      default_guard_interpreter :execute
      command "/opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml"
      backup 5
      cwd "/opt/opscode/embedded/service/chef-server-bootstrap"
      returns 0
      declared_type :execute
      cookbook_name "private-chef"
      recipe_name "bootstrap"
      not_if { #code block }
    end

Running handlers:
[2016-01-11T12:39:36-05:00] ERROR: Running exception handlers
Running handlers complete
[2016-01-11T12:39:36-05:00] ERROR: Exception handlers complete
Chef Client failed. 22 resources updated in 38 seconds
[2016-01-11T12:39:36-05:00] FATAL: Stacktrace dumped to /opt/opscode/embedded/cookbooks/cache/chef-stacktrace.out
[2016-01-11T12:39:36-05:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[bootstrap-platform] (private-chef::bootstrap line 45) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----
STDOUT:
STDERR: /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Connection refused - connect(2) for "127.0.0.1" port 9463 (Errno::ECONNREFUSED)
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `open'
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
        from /opt/opscode/embedded/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:878:in `connect'
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:206:in `transmit'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:68:in `execute'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:35:in `execute'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient.rb:74:in `post'
        from ./bin/bootstrap-platform:101:in `create_object_in_authz'
        from ./bin/bootstrap-platform:47:in `bootstrap'
        from ./bin/bootstrap-platform:120:in `<main>'
---- End output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----
Ran /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml returned 1
[root@vm1729701]~# Error executing action `run` on resource 'execute[bootstrap-platform]'
-bash: run: command not found
-bash: Error: command not found

Try to perform re-run, but still fails, not sure where the issue lies

**Comment by ynk** [comment]
same here, i don't have any clue. tried to install 12.3.1 and 12.4 so it's should not be version related. i suspect something in the setup but i don't really know what. i'm only running gitlab on my server.

**Comment by stevendanna** [comment]
```

**Comment by stevendanna** [comment]
```
STDERR: /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in initialize': Connection refused - connect(2) for "127.0.0.1" port 9463
```

9463 is the port by used by the authorization service.  Can you provide the output of:

```
chef-server-ctl status
```

```
tail -100 /var/log/opscode/oc_bifrost/current
```

**Comment by ynk** [comment]
sorry @stevendanna , i wiped my vps (ovh) and can't reproduce ; for the record, it was a debian8/64 so i decided to go by the book and i installed a clean ubuntu 14.04 64. I couldn't finish the install of the latest version properly, everytime a different bug (i had the [502 error on all the api calls](http://stackoverflow.com/questions/23957504/502-bad-gateway-nginx-chef-server) and also the [pivotal.rb doesn't exist]((/etc/opscode/pivotal.rb does not exist))). Thinking about to shift to ansible/puppet but still giving a try until monday ; available for debug if you're in the will .

**Comment by MaRuifeng** [comment]
Not sure whether this is related. But for my case I was trying to install the Chef server in a docker container, and below error occurred. 

`Connection refused - connect(2) for "127.0.0.1" port 9463`

And I checked the log from `/var/log/opscode/oc_bifrost/current` which says below:

`2018-01-16_17:11:25.41720 /opt/opscode/embedded/service/oc_bifrost/bin/oc_bifrost: line 107: which: command not found` 

Pretty dumb error but installing the `which` package fixed my problem.
