### ISSUE TITLE
CS12: chef server 12.0.1 upgrade to latest (12.0.1+20150123091710.git.58.af97194-1) postgres failure

### ISSUE THREAD

**Issue by patrick-wright** [chef/chef-server#70]
Standalone Ubuntu 12.04

End of upgrade output:
```
                 opscode Reconfigured!
                 ok: down: bookshelf: 0s, normally up
                 ok: down: nginx: 142s, normally up
                 ok: down: oc_bifrost: 0s, normally up
                 ok: down: oc_id: 141s, normally up
                 ok: down: opscode-chef-mover: 474s, normally up
                 ok: down: opscode-erchef: 0s, normally up
                 ok: down: opscode-expander: 140s, normally up
                 ok: down: opscode-expander-reindexer: 139s, normally up
                 ok: down: opscode-solr4: 0s, normally up
                 ok: down: postgresql: 0s, normally up
                 ok: down: rabbitmq: 1s, normally up
                 ok: down: redis_lb: 0s, normally up
                 ok: run: postgresql: (pid 11434) 0s
                 [private-chef-upgrade] - Latest Migration Available: 1.20
                 [private-chef-upgrade] - Migrations to Run: [1.20]
                 [private-chef-upgrade] - Current Migration Version: 1.19
                 [private-chef-upgrade] - Starting Migration 1.20
                 [private-chef-upgrade] - 	Running Command: make deploy with options {:cwd=>"/opt/opscode/embedded/service/enterprise-chef-server-schema", :env=>{"EC_TARGET"=>"@2.5.1", "OSC_TARGET"=>"@1.0.4", "DB_USER"=>"opscode-pgsql"}}
                 /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in `instance_eval': Partybus failed to execute command 'make deploy' exitstatus: 127 (RuntimeError)
                 	from /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v1.rb:97:in `run_command'
                 	from (eval):4:in `block in run'
                 	from /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v1.rb:14:in `instance_eval'
                 	from /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v1.rb:14:in `initialize'
                 	from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:25:in `new'
                 	from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:25:in `define_upgrade'
                 	from (eval):1:in `run'
                 	from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in `instance_eval'
                 	from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in `run'
                 	from /opt/opscode/embedded/service/partybus/lib/partybus/migrations.rb:41:in `run_migration'
                 	from ./bin/partybus:62:in `block in do_upgrade'
                 	from ./bin/partybus:58:in `each'
                 	from ./bin/partybus:58:in `do_upgrade'
                 	from ./bin/partybus:79:in `block in <main>'
                 	from ./bin/partybus:70:in `open'
                 	from ./bin/partybus:70:in `<main>'
```

postgresql-current log
```
2015-01-23_21:30:26.62998 LOG:  database system is ready to accept connections
2015-01-23_21:30:26.63036 LOG:  autovacuum launcher started
2015-01-23_21:30:27.54365 received TERM from runit, sending INT instead to force quit connections
2015-01-23_21:30:27.55419 LOG:  received fast shutdown request
2015-01-23_21:30:27.55447 LOG:  aborting any active transactions
2015-01-23_21:30:27.55468 LOG:  autovacuum launcher shutting down
2015-01-23_21:30:27.55494 LOG:  shutting down
2015-01-23_21:30:27.84605 LOG:  database system is shut down
2015-01-23_21:30:27.91923 LOG:  database system was shut down at 2015-01-23 21:30:27 GMT
2015-01-23_21:30:27.92236 LOG:  database system is ready to accept connections
2015-01-23_21:30:27.92276 LOG:  autovacuum launcher started
2015-01-23_21:30:33.55297 ERROR:  relation "changes" does not exist at character 50
2015-01-23_21:30:33.55303 STATEMENT:
2015-01-23_21:30:33.55303                   SELECT change_id
2015-01-23_21:30:33.55304                     FROM changes
2015-01-23_21:30:33.55304                    WHERE project = $1
2015-01-23_21:30:33.55304                    ORDER BY committed_at DESC
2015-01-23_21:30:33.55304                    LIMIT 1
2015-01-23_21:30:33.55304                   OFFSET COALESCE($2, 0)
2015-01-23_21:30:33.55305
2015-01-23_21:30:38.58836 ERROR:  relation "changes" does not exist at character 50
2015-01-23_21:30:38.58837 STATEMENT:
2015-01-23_21:30:38.58837                   SELECT change_id
2015-01-23_21:30:38.58838                     FROM changes
2015-01-23_21:30:38.58838                    WHERE project = $1
2015-01-23_21:30:38.58838                    ORDER BY committed_at DESC
2015-01-23_21:30:38.58838                    LIMIT 1
2015-01-23_21:30:38.58838                   OFFSET COALESCE($2, 0)
2015-01-23_21:30:38.58839
2015-01-23_21:32:10.52711 received TERM from runit, sending INT instead to force quit connections
2015-01-23_21:32:10.56202 LOG:  received fast shutdown request
2015-01-23_21:32:10.56204 LOG:  aborting any active transactions
2015-01-23_21:32:10.56205 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56205 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56205 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56205 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56206 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56206 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56206 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56206 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56206 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56206 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56207 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56207 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56207 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56207 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56207 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56208 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56208 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56208 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56208 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56209 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56209 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56209 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56209 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56209 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56210 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56211 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56211 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56211 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56211 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56211 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56211 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56212 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56212 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56212 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56212 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56213 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56213 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56213 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56213 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56213 FATAL:  terminating connection due to administrator command
2015-01-23_21:32:10.56213 LOG:  autovacuum launcher shutting down
2015-01-23_21:32:10.58249 LOG:  shutting down
2015-01-23_21:32:10.73643 FATAL:  the database system is shutting down
```

**Comment by stevendanna** [comment]
In the first error message we have:

```
'make deploy' exitstatus: 127
```

Exit status 127 in many shells is the error status for command not found.  It is likely that you do not have make installed on the base system.  This issue can be found here:

https://github.com/chef/chef-server/issues/33

Closing this as a duplicate, but thanks for taking the time to report what you found!
