### ISSUE TITLE
chef-server-ctl test will fail if HOSTNAME has Uppercase letters

### ISSUE THREAD

**Issue by vinyar** [chef/chef-server#776]
```
[root@Localhost oc-chef-pedant]# hostname -f
ALEX
```

```
# chef-server-ctl test
Configuring logging...
Creating platform...
Configured URL: https://ALEX
Creating org pedant_testorg_Localhost_5200
/opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/platform.rb:336:in `block in create_org': Bad error code 400 from create org: {"error":["Field 'name' invalid"]} (RuntimeError)
	from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/platform.rb:321:in `times'
	from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/platform.rb:321:in `create_org'
	from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/platform.rb:123:in `org_from_config'
	from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/platform.rb:42:in `initialize'
	from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant.rb:79:in `new'
	from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant.rb:79:in `create_platform'
	from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant.rb:58:in `setup'
	from ./bin/oc-chef-pedant:10:in `<main>'
```

also: https://getchef.zendesk.com/agent/tickets/8620

**Comment by sean-horn** [comment]
The above VM is misconfigured in a way that doesn't show the hostname problem clearly. This error in pedant comes from the chef server API when trying to create a test org where the Chef Server hostname has any uppercase characters. Pedant integrates the hostname found on the system.

The hostname in the following test is 
```
hostname && hostname -f
GAR-IFNEXCHEF12.REMOTE.STUFF.AND.ITS.REALLY.GOOD.COM
GAR-IFNEXCHEF12.REMOTE.STUFF.AND.ITS.REALLY.GOOD.COM`
```

I ran a failing pedant test
```
chef-server-ctl test
Configuring logging...
Creating platform...
Configured URL: https://gar-ifnexchef12.remote.stuff.and.its.really.good.com
Creating org pedant_testorg_GAR-IFNEXCHEF12_28334
/opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/platform.rb:336:in `block in create_org': Bad error code 400 from create org: {"error":["Field 'name' invalid"]} (RuntimeError)
	from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/platform.rb:321:in `times'
	from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/platform.rb:321:in `create_org'
	from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/platform.rb:123:in `org_from_config'
	from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/platform.rb:42:in `initialize'
	from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant.rb:79:in `new'
	from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant.rb:79:in `create_platform'
	from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant.rb:58:in `setup'
	from ./bin/oc-chef-pedant:10:in `<main>'
```

Then, on the same system after no changes, I followed up with an org creation, producing the same error as pedant
```
chef-server-ctl org-create seanCOFFEE "Sean UpperCase Coffee, Inc." --association_user rainbowdash --filename seanCOFFEE-validator.pem
ERROR: The data in your request was invalid
Response: Field 'name' invalid
```

**Comment by vinyar** [comment]
I think for the purpose for `chef-server-ctl test` the org name pedant is attempting to use should be force set `.to_lower`. 

I tried to figure out exactly where it's coming from, but no luck

**Comment by JPruenteAtRA** [comment]
Confirming that I see this same problem on a host with a mixed case FQDN (modified for public posting):

[root@ServerName bin]# chef-server-ctl test
Configuring logging...
Creating platform...
Configured URL: https://ServerName.Corp.CompanyName.com
Creating org pedant_testorg_ServerName_14894
/opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/platform.rb:336:in `block in create_org': Bad error code 400 from create org: {"error":["Field 'name' invalid"]} (RuntimeError)
        from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/platform.rb:321:in `times'
        from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/platform.rb:321:in `create_org'
        from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/platform.rb:123:in `org_from_config'
        from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/platform.rb:42:in `initialize'
        from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant.rb:79:in `new'
        from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant.rb:79:in `create_platform'
        from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant.rb:58:in `setup'
        from ./bin/oc-chef-pedant:10:in `<main>'

**Comment by erikng** [comment]
Ran into this issue as well.

**Comment by neilfrawley** [comment]
I've seen this issue also when running latest stable version of Chef Server 12.17.33.

For example; 
When I run `hostname` on my server I get **chefserver.mydomain.com**
When I run `hostname --fqdn` on my server I get **CHEFSERVER.mydomain.com**

When I run `chef-server-ctl test` I see the following errors which look to be because of the case mismatch reporting by others above.

```
rspec ./spec/org_creation/validate_containers_spec.rb:20 # Org Creation when validating default containers should have default containers
rspec ./spec/org_creation/validate_groups_spec.rb:26 # Org Creation when validating default groups should have default groups
```

**Comment by neilfrawley** [comment]
At a guess these lines would need to change;

https://github.com/chef/chef-server/blob/608dbe94d15822a31849952e13549744fc40a702/oc-chef-pedant/spec/org_creation/validate_containers_spec.rb#L14

https://github.com/chef/chef-server/blob/608dbe94d15822a31849952e13549744fc40a702/oc-chef-pedant/spec/org_creation/validate_groups_spec.rb#L20
