### ISSUE TITLE
Chef-server 11 Installation Fails

### ISSUE THREAD

**Issue by santhoshjavapro** [chef/chef-server#78]
Hi,

  I m trying to install chef-server 11 and got an error as follows (OS:Centos 6) 

```
[user@ip-111-111-11-11 chef-server_bakups]# chef-server-ctl reconfigure
[2015-02-02T16:42:09+00:00] WARN: 
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
SSL validation of HTTPS requests is disabled. HTTPS connections are still
encrypted, but chef is not able to detect forged replies or man in the middle
attacks.

To fix this issue add an entry like this to your configuration file:

  # Verify all HTTPS connections (recommended)
  ssl_verify_mode :verify_peer

  # OR, Verify only connections to chef-server
  verify_api_cert true


To check your SSL configuration, or troubleshoot errors, you can use the
`knife ssl check` command like so:

  knife ssl check -c /opt/chef-server/embedded/cookbooks/solo.rb


* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 

Starting Chef Client, version 11.12.2
Compiling Cookbooks...
Recipe: chef-server::default
  * directory[/etc/chef-server] action create (up to date)
[2015-02-02T16:42:12+00:00] WARN: Cloning resource attributes for directory[/var/opt/chef-server/chef-server-webui/etc] from prior resource (CHEF-3694)
[2015-02-02T16:42:12+00:00] WARN: Previous directory[/var/opt/chef-server/chef-server-webui/etc]: /opt/chef-server/embedded/cookbooks/chef-server/recipes/chef-server-webui.rb:31:in `block in from_file'
[2015-02-02T16:42:12+00:00] WARN: Current  directory[/var/opt/chef-server/chef-server-webui/etc]: /opt/chef-server/embedded/cookbooks/chef-server/definitions/unicorn_config.rb:21:in `block in from_file'
Converging 197 resources
  * directory[/etc/chef-server] action nothing (skipped due to action :nothing)
Recipe: chef-server::users
  * user[chef_server] action create (up to date)
  * group[chef_server] action create (up to date)
Recipe: chef-server::default
  * directory[/etc/chef] action create (up to date)
  * directory[/var/opt/chef-server] action create (up to date)
Recipe: runit::upstart
  * execute[initctl stop opscode-runsvdir] action run (skipped due to only_if)
  * file[/etc/init/opscode-runsvdir.conf] action delete (up to date)
  * cookbook_file[/etc/init/chef-server-runsvdir.conf] action create (up to date)
  * execute[initctl status chef-server-runsvdir] action run
    - execute initctl status chef-server-runsvdir

  * execute[initctl start chef-server-runsvdir] action run (skipped due to only_if)
Recipe: chef-server::sysctl-updates
  * execute[sysctl-reload] action nothing (skipped due to action :nothing)
  * bash[dual ip4/ip6 portbind] action run (skipped due to only_if)
Recipe: chef-server::rabbitmq
  * directory[/var/opt/chef-server/rabbitmq] action create (up to date)
  * directory[/var/opt/chef-server/rabbitmq/etc] action create (up to date)
  * directory[/var/opt/chef-server/rabbitmq/db] action create (up to date)
  * directory[/var/log/chef-server/rabbitmq] action create (up to date)
  * link[/var/opt/chef-server/rabbitmq/db] action create (skipped due to not_if)
  * link[/opt/chef-server/embedded/bin/rabbitmqctl] action create (up to date)
  * link[/opt/chef-server/embedded/bin/rabbitmq-env] action create (up to date)
  * link[/opt/chef-server/embedded/bin/rabbitmq-multi] action create
    - create symlink at /opt/chef-server/embedded/bin/rabbitmq-multi to /opt/chef-server/embedded/service/rabbitmq/sbin/rabbitmq-multi

  * link[/opt/chef-server/embedded/bin/rabbitmq-server] action create (up to date)
  * template[/opt/chef-server/embedded/service/rabbitmq/sbin/rabbitmq-env] action create
    - update content in file /opt/chef-server/embedded/service/rabbitmq/sbin/rabbitmq-env from 9d8c61 to 1020fa
        --- /opt/chef-server/embedded/service/rabbitmq/sbin/rabbitmq-env	2014-10-17 01:55:13.000000000 +0000
        +++ /tmp/chef-rendered-template20150202-9461-qz8m8r	2015-02-02 16:42:12.928048727 +0000
        @@ -1,19 +1,34 @@
         #!/bin/sh
        -##  The contents of this file are subject to the Mozilla Public License
        -##  Version 1.1 (the "License"); you may not use this file except in
        -##  compliance with the License. You may obtain a copy of the License
        -##  at http://www.mozilla.org/MPL/
        +##   The contents of this file are subject to the Mozilla Public License
        +##   Version 1.1 (the "License"); you may not use this file except in
        +##   compliance with the License. You may obtain a copy of the License at
        +##   http://www.mozilla.org/MPL/
         ##
        -##  Software distributed under the License is distributed on an "AS IS"
        -##  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
        -##  the License for the specific language governing rights and
        -##  limitations under the License.
        +##   Software distributed under the License is distributed on an "AS IS"
        +##   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
        +##   License for the specific language governing rights and limitations
        +##   under the License.
         ##
        -##  The Original Code is RabbitMQ.
        +##   The Original Code is RabbitMQ.
         ##
        -##  The Initial Developer of the Original Code is VMware, Inc.
        -##  Copyright (c) 2007-2011 VMware, Inc.  All rights reserved.
        +##   The Initial Developers of the Original Code are LShift Ltd,
        +##   Cohesive Financial Technologies LLC, and Rabbit Technologies Ltd.
         ##
        +##   Portions created before 22-Nov-2008 00:00:00 GMT by LShift Ltd,
        +##   Cohesive Financial Technologies LLC, or Rabbit Technologies Ltd
        +##   are Copyright (C) 2007-2008 LShift Ltd, Cohesive Financial
        +##   Technologies LLC, and Rabbit Technologies Ltd.
        +##
        +##   Portions created by LShift Ltd are Copyright (C) 2007-2010 LShift
        +##   Ltd. Portions created by Cohesive Financial Technologies LLC are
        +##   Copyright (C) 2007-2010 Cohesive Financial Technologies
        +##   LLC. Portions created by Rabbit Technologies Ltd are Copyright
        +##   (C) 2007-2010 Rabbit Technologies Ltd.
        +##
        +##   All Rights Reserved.
        +##
        +##   Contributor(s): ______________________________________.
        +##
         
         # Determine where this script is really located
         SCRIPT_PATH="$0"
        @@ -37,10 +52,5 @@
         NODENAME=rabbit@${HOSTNAME%%.*}
         
         # Load configuration from the rabbitmq.conf file
        -if [ -f /etc/rabbitmq/rabbitmq.conf ] && \
        -   [ ! -f /etc/rabbitmq/rabbitmq-env.conf ] ; then
        -    echo -n "WARNING: ignoring /etc/rabbitmq/rabbitmq.conf -- "
        -    echo "location has moved to /etc/rabbitmq/rabbitmq-env.conf"
        -fi
        -[ -f /etc/rabbitmq/rabbitmq-env.conf ] && . /etc/rabbitmq/rabbitmq-env.conf
        +[ -f /var/opt/chef-server/rabbitmq/etc/rabbitmq.conf ] && . /var/opt/chef-server/rabbitmq/etc/rabbitmq.conf
    - restore selinux security context

  * template[/var/opt/chef-server/rabbitmq/etc/rabbitmq.conf] action create (up to date)
  * directory[/opt/chef-server/sv/rabbitmq] action create
    - create new directory /opt/chef-server/sv/rabbitmq
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'
    - restore selinux security context

  * directory[/opt/chef-server/sv/rabbitmq/log] action create
    - create new directory /opt/chef-server/sv/rabbitmq/log
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'
    - restore selinux security context

  * directory[/opt/chef-server/sv/rabbitmq/log/main] action create
    - create new directory /opt/chef-server/sv/rabbitmq/log/main
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'
    - restore selinux security context

  * template[/opt/chef-server/sv/rabbitmq/run] action create
    - create new file /opt/chef-server/sv/rabbitmq/run
    - update content in file /opt/chef-server/sv/rabbitmq/run from none to 264c9f
        --- /opt/chef-server/sv/rabbitmq/run	2015-02-02 16:42:13.816023441 +0000
        +++ /tmp/chef-rendered-template20150202-9461-c3ac9r	2015-02-02 16:42:13.818023385 +0000
        @@ -1 +1,5 @@
        +#!/bin/sh
        +exec 2>&1
        +exec chpst -P -u chef_server -U chef_server /usr/bin/env HOME=/var/opt/chef-server/rabbitmq /opt/chef-server/embedded/bin/rabbitmq-server
        +
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'
    - restore selinux security context

  * template[/opt/chef-server/sv/rabbitmq/log/run] action create
    - create new file /opt/chef-server/sv/rabbitmq/log/run
    - update content in file /opt/chef-server/sv/rabbitmq/log/run from none to f2df3a
        --- /opt/chef-server/sv/rabbitmq/log/run	2015-02-02 16:42:14.002018142 +0000
        +++ /tmp/chef-rendered-template20150202-9461-10gb8pu	2015-02-02 16:42:14.003018114 +0000
        @@ -1 +1,3 @@
        +#!/bin/sh
        +exec svlogd -tt /var/log/chef-server/rabbitmq
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'
    - restore selinux security context

  * file[/opt/chef-server/sv/rabbitmq/down] action delete (up to date)
  * link[/opt/chef-server/init/rabbitmq] action create
    - create symlink at /opt/chef-server/init/rabbitmq to /opt/chef-server/embedded/bin/sv

  * link[/opt/chef-server/service/rabbitmq] action create
    - create symlink at /opt/chef-server/service/rabbitmq to /opt/chef-server/sv/rabbitmq

  * ruby_block[supervise_rabbitmq_sleep] action run
    - execute the ruby block supervise_rabbitmq_sleep

  * service[rabbitmq] action nothing (skipped due to action :nothing)
Recipe: chef-server::postgresql
  * user[opscode-pgsql] action create
================================================================================
Error executing action `create` on resource 'user[opscode-pgsql]'
================================================================================


Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '8'
---- Begin output of ["usermod", "-d", "/var/opt/chef-server/postgresql", "opscode-pgsql"] ----
STDOUT: 
STDERR: usermod: user opscode-pgsql is currently logged in
---- End output of ["usermod", "-d", "/var/opt/chef-server/postgresql", "opscode-pgsql"] ----
Ran ["usermod", "-d", "/var/opt/chef-server/postgresql", "opscode-pgsql"] returned 8


Resource Declaration:
---------------------
# In /opt/chef-server/embedded/cookbooks/chef-server/recipes/postgresql.rb

 24: user node['chef_server']['postgresql']['username'] do
 25:   system true
 26:   shell node['chef_server']['postgresql']['shell']
 27:   home node['chef_server']['postgresql']['home']
 28: end
 29: 



Compiled Resource:
------------------
# Declared in /opt/chef-server/embedded/cookbooks/chef-server/recipes/postgresql.rb:24:in `from_file'

user("opscode-pgsql") do
  action :create
  supports {:manage_home=>false, :non_unique=>false}
  retries 0
  retry_delay 2
  guard_interpreter :default
  username "opscode-pgsql"
  home "/var/opt/chef-server/postgresql"
  shell "/bin/sh"
  system true
  cookbook_name :"chef-server"
  recipe_name "postgresql"
end




Running handlers:
[2015-02-02T16:42:17+00:00] ERROR: Running exception handlers
Running handlers complete

[2015-02-02T16:42:17+00:00] ERROR: Exception handlers complete
[2015-02-02T16:42:17+00:00] FATAL: Stacktrace dumped to /opt/chef-server/embedded/cookbooks/cache/chef-stacktrace.out
Chef Client failed. 11 resources updated in 7.86400068 seconds
[2015-02-02T16:42:17+00:00] ERROR: user[opscode-pgsql] (chef-server::postgresql line 24) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '8'
---- Begin output of ["usermod", "-d", "/var/opt/chef-server/postgresql", "opscode-pgsql"] ----
STDOUT: 
STDERR: usermod: user opscode-pgsql is currently logged in
---- End output of ["usermod", "-d", "/var/opt/chef-server/postgresql", "opscode-pgsql"] ----
Ran ["usermod", "-d", "/var/opt/chef-server/postgresql", "opscode-pgsql"] returned 8
[2015-02-02T16:42:17+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

note: I want to run chef-server 11 not chef-server 12.

**Comment by stevendanna** [comment]
Did you previously attempt to install chef-server 12 on this same machine?

**Comment by santhoshjavapro** [comment]
Yes, Actually I m trying to rollback from chef 12 to chef 11,meanwhile I end up crashing my server now I can start neither 12 or 11. Is there anyway to recover the data/configurations?

**Comment by stevendanna** [comment]
@santhoshjavapro OK.  Are you trying to roll back because of a failed upgrade or some other reason?  I can help you roll back, but I ask because if your end goal is to be on Chef 12, it is often easier to move forward.  Let's take this step by step.

1. Does /var/opt/chef-server still exist and appear to have data in it?
2. Does /var/opt/opscode exist?
3. What have you tried so far?  From the looks of it, you still have Chef 12 processes running on the machine (which is why the `usermod` command cannot change the home directory of the opscode-pgsql user)

**Comment by santhoshjavapro** [comment]
@stevendanna yes /var/opt/chef-server exist but how can I verify data still exists?

**Comment by stevendanna** [comment]
@santhoshjavapro It likely does as I don't believe we destroy it.  You should see subdirectories for each service.

**Comment by mmzyk** [comment]
We don't destroy it. So long as you haven't removed the package or deleted the data dirs yourself it should still be there. We purposefully did that in the event something went wrong, so you can recover. 

Also, depending on where in the upgrade your process failed, we first download all the data from your chef 11 server into a tmp dire (it's going to be in /tmp/chef11-randomstringhere), so you could also look for that if you need it. However, since Chef 11 is still on the box, your data is there. If you fully remove Chef server 12, you should be able to restart Chef 11.

**Comment by santhoshjavapro** [comment]
If I remove the chef-server-12 I can't use the command chef-server-ctl command, how to direct this command back to chef-server-11.

**Comment by mmzyk** [comment]
chef-server-ctl for chef 11 is still there, it's just been removed from the path, as the name is the same for Chef 12, but in a different location. Look at /opt/chef-server/bin/chef-server-ctl and you'll find the one for Chef 11. You're data for Chef 11 should still be in place, meaning you don't yet need to recover from /tmp. Try getting Chef 11 running again using chef-server-ctl. 

If that fails for some reason, the data in the /tmp dir can up uploaded to a clean chef 11 server using knife upload. I'd recommend you make a backup copy, just as extra insurance, although I wouldn't expect anything to go wrong.

**Comment by santhoshjavapro** [comment]
Thanks @mmzyk, I removed everything from my machine all I have is /tmp backup now which have all my datas in json format.

 "the data in the /tmp dir can up uploaded to a clean chef 11 server using knife upload" 

Did you mean "clean chef server" means a fresh chef 11 server installation?
So that all the configurations can be recovered?

**Comment by mmzyk** [comment]
By clean I did mean a fresh install. Although if you're having to start fresh you might as well go straight to 12. First, make sure you have the data backed up. Then install 12 on the machine. 

Now, I don't know where your previous upgrade to 12 failed, so there might be a /tmp/chef12-randomstringhere directory. If so, then your Chef 11 data has already been transformed into the format Chef 12 needs. If not, then you'll need to run the transform steps.

See the docs here: https://docs.chef.io/upgrade_server_open_source_notes.html#manual-upgrades

That describes the commands that you can run for the manual upgrades. You can skip the command that downloads the data. If needed you should run the transform command, and then you should run the command that uploads the data. 

If you scroll on that docs page some you'll see each command explained in detail. Also note that you can pass each command the -h flag for the full help menu as well.

Running the upgrade command that you attempted the first time is the same as running these three commands one after the other. Hopefully these commands with the clean system should get you up and running.

**Comment by mmzyk** [comment]
I should note that one of the options for the commands is where to find the /tmp data that is already on the system, so you'll need to supply this option. If you run a command (such as the transform command) and an option it needs isn't set them it will prompt you for the information it needs.

**Comment by santhoshjavapro** [comment]
@mmzyk My fresh chef-server 11 is up and running,and I have data in the /tmp folder in json format(cookbooks, nodes, users, etc) . Now I want to upload all backup-ed data back to the new server.

The link you provided gave a clear idea about what chef-upgrade does at background and it worked in chef-server-12 as expected but I believe the same commands will not work in chef-11(As per the docs, these commands should be used only at the time of up-gradation).

And Knife upload will only upload Cookbooks, Data bags, Roles stored as JSON data and Environments stored as JSON data. With added to that I want all my old node configurations(Already 50+ nodes configured in old server) to be uploaded to the new server. there are no commands given in doc for uploading a node config.

Doc : https://docs.chef.io/knife_upload.html

Kindly help me if you know anyway to do it  else I have to configure all the nodes again, manually .

**Comment by mmzyk** [comment]
@santhoshjavapro knife upload should handle nodes just fine, even though I realize the docs don't mention that. https://docs.chef.io/knife_upload.html 

So long as the repo_mode is set to everything (the default) it should upload the node data.

And you're right, the upload commands are only for getting to Chef 12. Based on your description it sounded like you're in a place where rolling forward made as much sense as rolling back, so I was giving you directions on how to get to Chef 12. But knife upload should allow you to roll back to Chef 11 just fine.

**Comment by mmzyk** [comment]
@santhoshjavapro Are you in a good state now? If so, I'd like to close this issue out.

**Comment by santhoshjavapro** [comment]
@mmzyk Yes, Thanks for all ur support :)
