### ISSUE TITLE
mover_server_admins_global_group_callback: duplicate key

### ISSUE THREAD

**Issue by llaurent** [chef/chef-server#822]
following an error while upgrading from 12.4.1 to 12.5 I now have an errror when "private-chef-upgrade" runs "
/opt/opscode/embedded/bin/escript /opt/opscode/embedded/service/opscode-chef-mover/scripts/migrate mover_server_admins_global_group_callback normal mover_transient_queue_batch_migrator"
isn't that supposed to be idempotent ?

```
2016-04-25 14:38:57.574 [error] 110111951111141033240110111951051004158Could not create new erchef group for server-admins.
2016-04-25 14:38:57.575 [error] 110111951111141033240110111951051004158Processing aborted in migrate due to error: {error,{error,error,<<"23505">>,<<"duplicate key value violates unique constraint \"groups_org_id_name_key\"">>,[{detail,<<"Key (org_id, name)=(00000000000000000000000000000000, server-admins) already exists.">>}]}}
2016-04-25 14:38:57.575 [error] 110111951111141033240110111951051004158{migration_action,"Error in mover_server_admins_global_group_callback:migration_action"}
2016-04-25 14:38:57.575 [error] 110111951111141033240110111951051004158migration_action args
[<<"00000000000000000000000000000000">>,account_dets_not_opened]
2016-04-25 14:38:57.576 [error] 110111951111141033240110111951051004158in working: Worker down with unexpected error. Halting new workers. {error,{error,{error,error,<<"23505">>,<<"duplicate key value violates unique constraint \"groups_org_id_name_key\"">>,[{detail,<<"Key (org_id, name)=(00000000000000000000000000000000, server-admins) already exists.">>}]}},migrate}
2016-04-25 14:38:57.576 [error] 110111951111141033240110111951051004158throw
{error,{error,error,<<"23505">>,<<"duplicate key value violates unique constraint \"groups_org_id_name_key\"">>,[{detail,<<"Key (org_id, name)=(00000000000000000000000000000000, server-admins) already exists.">>}]}}
[{mover_server_admins_global_group_callback,migration_action,2,[{file,"/var/cache/omnibus/src/opscode-chef-mover/_build/default/lib/mover/src/mover_server_admins_global_group_callback.erl"},{line,61}]},{mover_transient_worker,migrate,2,[{file,"/var/cache/omnibus/src/opscode-chef-mover/_build/default/lib/mover/src/mover_transient_worker.erl"},{line,42}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,503}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]
2016-04-25 14:38:57.577 [error] 110111951111141033240110111951051004158gen_fsm <0.1901.0> in state migrate terminated with reason: {error,{error,{error,error,<<"23505">>,<<"duplicate key value violates unique constraint \"groups_org_id_name_key\"">>,[{detail,<<"Key (org_id, name)=(00000000000000000000000000000000, server-admins) already exists.">>}]}},migrate}
2016-04-25 14:38:57.577 [error] 110111951111141033240110111951051004158CRASH REPORT Process <0.1901.0> with 0 neighbours exited with reason: {error,{error,{error,error,<<"23505">>,<<"duplicate key value violates unique constraint \"groups_org_id_name_key\"">>,[{detail,<<"Key (org_id, name)=(00000000000000000000000000000000, server-admins) already exists.">>}]}},migrate} in gen_fsm:terminate/7 line 611
2016-04-25 14:38:57.579 [error] 110111951111141033240110111951051004158Supervisor mover_transient_worker_sup had child undefined started with {mover_transient_worker,start_link,undefined} at <0.1901.0> exit with reason {error,{error,{error,error,<<"23505">>,<<"duplicate key value violates unique constraint \"groups_org_id_name_key\"">>,[{detail,<<"Key (org_id, name)=(00000000000000000000000000000000, server-admins) already exists.">>}]}},migrate} in context child_terminated
```

**Comment by llaurent** [comment]
I've removed the server-admins group from psql.
mover_server_admins_global_group_callback ran ok.
I guess the issue occured when mover_server_admins_global_group_callback run while oc_bifrost wasn't running.

**Comment by glennmate** [comment]
Same issue here. Did an upgrade and it's failing after the reconfigure. Chef-mover is failing during the 1.27 to 1.28 upgrade process. Checking the logs in /var/log/opscode/opscode-chef-mover : 

End output of the ```sudo chef-server-ctl upgrade```

```
Chef Client finished, 24/413 resources updated in 47 seconds
Chef Server Reconfigured!
ok: down: bookshelf: 0s, normally up
ok: down: nginx: 1s, normally up
ok: down: oc_bifrost: 0s, normally up
ok: down: oc_id: 0s, normally up
ok: down: opscode-chef-mover: 112s, normally up
ok: down: opscode-erchef: 0s, normally up
ok: down: opscode-expander: 0s, normally up
ok: down: opscode-expander-reindexer: 0s, normally up, want up
ok: down: opscode-reporting: 0s, normally up
ok: down: opscode-solr4: 0s, normally up
ok: down: postgresql: 0s, normally up
ok: down: rabbitmq: 0s, normally up
ok: down: redis_lb: 1s, normally up
ok: run: postgresql: (pid 19473) 0s
[private-chef-upgrade] - Latest Migration Available: 1.30
[private-chef-upgrade] - Migrations to Run: [#<Partybus::MigrationFile:0x0000000                                                                                        1865d48 @path="/opt/opscode/embedded/upgrades/001/028_server_admins_global_group                                                                                        .rb", @major=1, @minor=28>, #<Partybus::MigrationFile:0x000000018664a0 @path="/o                                                                                        pt/opscode/embedded/upgrades/001/029_server_admins_existing_user_read_access.rb"                                                                                        , @major=1, @minor=29>, #<Partybus::MigrationFile:0x000000018654b0 @path="/opt/o                                                                                        pscode/embedded/upgrades/001/030_actor_keys_access_group.rb", @major=1, @minor=3                                                                                        0>]
[private-chef-upgrade] - Current Migration Version: 1.27
[private-chef-upgrade] - Starting Migration 1.28
[private-chef-upgrade] -        Stopping Services ["nginx", "opscode-erchef"]
ok: down: nginx: 32s, normally up
down: nginx: 37s, normally up; run: log: (pid 1271) 367s
down: nginx: 42s, normally up; run: log: (pid 1271) 372s
ok: down: opscode-erchef: 45s, normally up
down: opscode-erchef: 50s, normally up; run: log: (pid 1257) 382s
down: opscode-erchef: 55s, normally up; run: log: (pid 1257) 387s
[private-chef-upgrade] - Sleeping for 10 seconds while services stop...
[private-chef-upgrade] -        Starting Services ["oc_bifrost", "postgresql"]
down: oc_bifrost: 70s, normally up; run: log: (pid 1250) 401s
ok: run: oc_bifrost: (pid 20788) 1s
run: oc_bifrost: (pid 20788) 6s; run: log: (pid 1250) 412s
run: postgresql: (pid 19473) 75s; run: log: (pid 1256) 416s
[private-chef-upgrade] - Sleeping for 15 seconds while services comes online...
[private-chef-upgrade] -        Restarting Service opscode-chef-mover
ok: run: opscode-chef-mover: (pid 21449) 0s
[private-chef-upgrade] - Sleeping for 15 seconds while service opscode-chef-move                                                                                        r comes back online...
run: opscode-chef-mover: (pid 21449) 20s; run: log: (pid 1251) 456s
[private-chef-upgrade] - Creating global group server-admins with read and creat                                                                                        e access on users container
[private-chef-upgrade] -        Running Command: /opt/opscode/embedded/bin/escri                                                                                        pt /opt/opscode/embedded/service/opscode-chef-mover/scripts/migrate mover_server                                                                                        _admins_global_group_callback normal mover_transient_queue_batch_migrator with o                                                                                        ptions {}
Unknown error error
 Unknown reason function_clause

=ERROR REPORT==== 10-Jul-2016::18:26:03 ===
{error,function_clause}

An unknown error has occurred.

/opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in `instanc                                                                                        e_eval': Partybus failed to execute command '/opt/opscode/embedded/bin/escript /                                                                                        opt/opscode/embedded/service/opscode-chef-mover/scripts/migrate mover_server_adm                                                                                        ins_global_group_callback normal mover_transient_queue_batch_migrator' exitstatu                                                                                        s: 1 (RuntimeError)
        from /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v                                                                                        1.rb:97:in `run_command'
        from (eval):11:in `block in run'
        from /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v                                                                                        1.rb:14:in `instance_eval'
        from /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v                                                                                        1.rb:14:in `initialize'
        from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:2                                                                                        5:in `new'
        from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:2                                                                                        5:in `define_upgrade'
        from (eval):1:in `run'
        from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:1                                                                                        4:in `instance_eval'
        from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:1                                                                                        4:in `run'
        from /opt/opscode/embedded/service/partybus/lib/partybus/migrations.rb:4                                                                                        1:in `run_migration'
        from ./bin/partybus:62:in `block in do_upgrade'
        from ./bin/partybus:58:in `each'
        from ./bin/partybus:58:in `do_upgrade'
        from ./bin/partybus:79:in `block in <main>'
        from ./bin/partybus:70:in `open'
        from ./bin/partybus:70:in `<main>'
```


```
2016-07-10_18:25:45.50005 =INFO REPORT==== 10-Jul-2016::18:25:45 ===
2016-07-10_18:25:45.50005 starting stats_hero_sender_sup with 350 senders
2016-07-10_18:26:02.97022 18:26:02.756 [error] Could not create new erchef group for server-admins.
2016-07-10_18:26:03.03115 18:26:02.756 [error] {migration_action,"Error in mover_server_admins_global_group_callback:migration_action"}
2016-07-10_18:26:03.09711 18:26:02.756 [error] Processing aborted in migrate due to error: {error,{error,error,<<"23505">>,<<"duplicate key value violates unique const$
2016-07-10_18:26:03.16876 18:26:02.756 [error] migration_action args
2016-07-10_18:26:03.16878 [<<"00000000000000000000000000000000">>,account_dets_not_opened]
2016-07-10_18:26:03.31113 18:26:02.756 [error] throw
2016-07-10_18:26:03.31116 {error,{error,error,<<"23505">>,<<"duplicate key value violates unique constraint \"groups_org_id_name_key\"">>,[{detail,<<"Key (org_id, name$
2016-07-10_18:26:03.31116 [{mover_server_admins_global_group_callback,migration_action,2,[{file,"/var/cache/omnibus/src/opscode-chef-mover/_build/default/lib/mover/src$
2016-07-10_18:26:03.38984 18:26:02.757 [error] in working: Worker down with unexpected error. Halting new workers. {error,{error,{error,error,<<"23505">>,<<"duplicate $
2016-07-10_18:26:03.45806 18:26:02.757 [error] gen_fsm <0.1700.0> in state migrate terminated with reason: {error,{error,{error,error,<<"23505">>,<<"duplicate key valu$
2016-07-10_18:26:03.51473 18:26:02.757 [error] CRASH REPORT Process <0.1700.0> with 0 neighbours exited with reason: {error,{error,{error,error,<<"23505">>,<<"duplicat$
2016-07-10_18:26:03.59366 18:26:02.757 [error] Supervisor mover_transient_worker_sup had child undefined started with {mover_transient_worker,start_link,undefined} at $
```

I'll do a bit of digging before executing the same actions as @llaurent and return with my results.

**Comment by glennmate** [comment]
To update, I was unable to get any traction on this issue and may be looking to migrate Chef rather than work through the issues that have presented themselves.

**Comment by tylercloke** [comment]
Ah, if the migration failed half way through and there is an idempotence issue, I could see how that'd happen. I'll take a look. Shouldn't be too hard to write the migration in an idempotent manner.

**Comment by glennmate** [comment]
@tylercloke Thanks for taking a look at this one.

**Comment by tylercloke** [comment]
I've reproduced the issue, looking at a fix now.

**Comment by tylercloke** [comment]
This should fix you up https://github.com/chef/chef-server/pull/881

Are you still blocked @glennmate?

**Comment by glennmate** [comment]
I was unable to work through the issue and haven't spent any time rebuilding Chef to circumvent this issue so I'm still blocked. However, reviewing your PR the fix looks promising :tada:

**Comment by tylercloke** [comment]
Fixed merged! It will ship with the next version of Chef Server. @glennmate @llaurent if you are feeling adventurous and can't wait, you can risk a nightly (should be in by tomorrow), but we have been shipping semi-frequently recently so the wait for a blessed build probably wouldn't be too long. Let me know if the fix doesn't work or you have any issues!

**Comment by andrewvttran** [comment]
Thanks for all your hard work @tylercloke!

Do you know when the next version ships out? I'm running into the same error messages during the ```chef-server-ctl upgrade``` process as well.

**Comment by stevendanna** [comment]
@andrewvttran Chef Server 12.12 shipped eralier this week and should have the included fix.

**Comment by andrewvttran** [comment]
Hmm, running the upgrade today from ```12.8.0``` with no luck so far.

**Comment by stevendanna** [comment]
According to git the fix that @tylercloke Referenced above should be in the following releases:

```
> git tag --contains 86666899c1ecc6f875225da7d34d679d640d0b06
12.10.0
12.11.0
12.11.1
12.12.0
12.9.0
12.9.1
```

Is the error message you are getting an exact match?  Can you check in /var/log/opscode/opscode-chef-mover/current and post any error output you see there?

**Comment by andrewvttran** [comment]
Here's the output from ```/var/log/opscode/opscode-chef-mover```:
```
2017-02-02 08:37:57.710 [error] 110111951111141033240110111951051004158Could not create new erchef group for server-admins.
2017-02-02 08:37:57.710 [error] 110111951111141033240110111951051004158Processing aborted in migrate due to error: {error,{error,error,<<"23505">>,<<"duplicate key value violates unique constraint \"groups_org_id_name_key\"">>,[{detail,<<"Key (org_id, name)=(00000000000000000000000000000000, server-admins) already exists.">>}]}}
2017-02-02 08:37:57.710 [error] 110111951111141033240110111951051004158{migration_action,"Error in mover_server_admins_global_group_callback:migration_action"}
2017-02-02 08:37:57.710 [error] 110111951111141033240110111951051004158migration_action args
[<<"00000000000000000000000000000000">>,account_dets_not_opened]
2017-02-02 08:37:57.711 [error] 110111951111141033240110111951051004158in working: Worker down with unexpected error. Halting new workers. {error,{error,{error,error,<<"23505">>,<<"duplicate key value violates unique constraint \"groups_org_id_name_key\"">>,[{detail,<<"Key (org_id, name)=(00000000000000000000000000000000, server-admins) already exists.">>}]}},migrate}
2017-02-02 08:37:57.711 [error] 110111951111141033240110111951051004158throw
{error,{error,error,<<"23505">>,<<"duplicate key value violates unique constraint \"groups_org_id_name_key\"">>,[{detail,<<"Key (org_id, name)=(00000000000000000000000000000000, server-admins) already exists.">>}]}}
[{mover_server_admins_global_group_callback,migration_action,2,[{file,"/var/cache/omnibus/src/opscode-chef-mover/_build/default/lib/mover/src/mover_server_admins_global_group_callback.erl"},{line,61}]},{mover_transient_worker,migrate,2,[{file,"/var/cache/omnibus/src/opscode-chef-mover/_build/default/lib/mover/src/mover_transient_worker.erl"},{line,42}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,503}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]
2017-02-02 08:37:57.711 [error] 110111951111141033240110111951051004158gen_fsm <0.1700.0> in state migrate terminated with reason: {error,{error,{error,error,<<"23505">>,<<"duplicate key value violates unique constraint \"groups_org_id_name_key\"">>,[{detail,<<"Key (org_id, name)=(00000000000000000000000000000000, server-admins) already exists.">>}]}},migrate}
2017-02-02 08:37:57.711 [error] 110111951111141033240110111951051004158CRASH REPORT Process <0.1700.0> with 0 neighbours exited with reason: {error,{error,{error,error,<<"23505">>,<<"duplicate key value violates unique constraint \"groups_org_id_name_key\"">>,[{detail,<<"Key (org_id, name)=(00000000000000000000000000000000, server-admins) already exists.">>}]}},migrate} in gen_fsm:terminate/7 line 611
2017-02-02 08:37:57.712 [error] 110111951111141033240110111951051004158Supervisor mover_transient_worker_sup had child undefined started with {mover_transient_worker,start_link,undefined} at <0.1700.0> exit with reason {error,{error,{error,error,<<"23505">>,<<"duplicate key value violates unique constraint \"groups_org_id_name_key\"">>,[{detail,<<"Key (org_id, name)=(00000000000000000000000000000000, server-admins) already exists.">>}]}},migrate} in context child_terminated
```

**Comment by phene** [comment]
I'm experiencing this error with the latest chef-server build, as well.

**Comment by phene** [comment]
Filed new issue: https://github.com/chef/chef-server/issues/1124
