### ISSUE TITLE
chef-sync 1.0-rc6 crashes

### ISSUE THREAD

**Issue by cyan-novartis** [chef/chef-server#831]
_Basic Info:_
centos 6.7
chef-server 12.5
chef-sync 1.0-rc6

_Description:_
fresh install of chef-server, chef-sync, trying to sync with a master chef-server. 
chef-sync-ctl sync-status reports **"crashed"**

From the log, it looks like postgresql conf may not be setup correctly, some info might be missing or incorrect.

_Additional Information:_
**/var/log/opscode/chef-sync/client/current**
2016-05-06_15:30:02.37387 I, [2016-05-06T11:30:02.373693 #17663]  INFO -- : ec_sync_client: manager starting
2016-05-06_15:30:02.37585 I, [2016-05-06T11:30:02.375760 #17663]  INFO -- : ec_sync_client: listening on /var/opt/chef-sync/ec_sync_client/ec_sync.sock
2016-05-06_15:30:03.80122 I, [2016-05-06T11:30:03.800165 #17663]  INFO -- : Sending fast shutdown to workers
2016-05-06_15:30:03.80124 I, [2016-05-06T11:30:03.800242 #17663]  INFO -- : Waiting for workers to stop
2016-05-06_15:30:03.80124 I, [2016-05-06T11:30:03.800272 #17663]  INFO -- : Shutdown complete.
2016-05-06_15:30:05.24829 I, [2016-05-06T11:30:05.248219 #17731]  INFO -- : ec_sync_client: manager starting
2016-05-06_15:30:05.25115 I, [2016-05-06T11:30:05.251117 #17731]  INFO -- : ec_sync_client: listening on /var/opt/chef-sync/ec_sync_client/ec_sync.sock
2016-05-06_15:37:20.53808 I, [2016-05-06T11:37:20.535368 #17731]  INFO -- : Sending fast shutdown to workers
2016-05-06_15:37:20.53820 I, [2016-05-06T11:37:20.538151 #17731]  INFO -- : Waiting for workers to stop
2016-05-06_15:37:20.53829 I, [2016-05-06T11:37:20.538243 #17731]  INFO -- : Shutdown complete.
2016-05-06_15:37:21.52449 I, [2016-05-06T11:37:21.524425 #18176]  INFO -- : ec_sync_client: manager starting
2016-05-06_15:37:21.52468 I, [2016-05-06T11:37:21.524652 #18176]  INFO -- : ec_sync_client: listening on /var/opt/chef-sync/ec_sync_client/ec_sync.sock
2016-05-06_15:37:21.52473 I, [2016-05-06T11:37:21.524708 #18176]  INFO -- : ec_sync_client: starting worker for rcp

**_2016-05-06_15:37:22.42698 /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:217:in `initialize': PG::ConnectionBad: fe_sendauth: no password supplied (Sequel::DatabaseConnectionError)_**

2016-05-06_15:37:22.42700   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapte
rs/postgres.rb:217:in `new'
2016-05-06_15:37:22.42701   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapte
rs/postgres.rb:217:in`connect'
2016-05-06_15:37:22.42701   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connec
tion_pool.rb:96:in `make_new'
2016-05-06_15:37:22.42701   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connec
tion_pool/threaded.rb:158:in`make_new'
2016-05-06_15:37:22.42701   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connec
tion_pool/threaded.rb:137:in `available'
2016-05-06_15:37:22.42702   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connec
tion_pool/threaded.rb:127:in`block in acquire'
2016-05-06_15:37:22.42702   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connec
tion_pool/threaded.rb:194:in `block in sync'
2016-05-06_15:37:22.42702   from <internal:prelude>:10:in`synchronize'
2016-05-06_15:37:22.42702   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connec
tion_pool/threaded.rb:194:in `sync'
2016-05-06_15:37:22.42703   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connec
tion_pool/threaded.rb:126:in`acquire'
2016-05-06_15:37:22.42703   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/connec
tion_pool/threaded.rb:94:in `hold'
2016-05-06_15:37:22.42703   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/databa
se/connecting.rb:250:in`synchronize'
2016-05-06_15:37:22.42703   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapte
rs/shared/postgres.rb:446:in `server_version'
2016-05-06_15:37:22.42703   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/adapte
rs/shared/postgres.rb:1563:in`server_version'
2016-05-06_15:37:22.42704   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/datase
t/sql.rb:228:in `select_sql'
2016-05-06_15:37:22.42704   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/datase
t/actions.rb:139:in`each'
2016-05-06_15:37:22.42705   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/datase
t/actions.rb:639:in `single_record'
2016-05-06_15:37:22.42705   from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/gems/sequel-4.13.0/lib/sequel/datase
t/actions.rb:191:in`first'
2016-05-06_15:37:22.42705   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/org.rb:28:in `las
t_seq'
2016-05-06_15:37:22.42706   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/orgsyncer.rb:114:
in`bootstrap_required?'
2016-05-06_15:37:22.42706   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/orgsyncer.rb:52:i
n `start'
2016-05-06_15:37:22.42706   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:1
14:in`block in start_worker'
2016-05-06_15:37:22.42706   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:1
10:in `fork'
2016-05-06_15:37:22.42706   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:1
10:in`start_worker'
2016-05-06_15:37:22.42706   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:6
9:in `block in start'
2016-05-06_15:37:22.42707   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:6
6:in`each'
2016-05-06_15:37:22.42707   from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:6
6:in `start'
2016-05-06_15:37:22.42707   from /opt/chef-sync/embedded/service/ec_sync_client/bin/ec_sync_client:56:in`run'
2016-05-06_15:37:22.42707   from /opt/chef-sync/embedded/service/ec_sync_client/bin/ec_sync_client:62:in `<main>'
2016-05-06_15:37:22.43254 I, [2016-05-06T11:37:22.432437 #18176]  INFO -- : Worker for rcp died unexpectedly!
2016-05-06_15:37:59.53052 I, [2016-05-06T11:37:59.530436 #18176]  INFO -- : ec_sync_client: starting new command connection handler
2016-05-06_15:37:59.54578 I, [2016-05-06T11:37:59.545687 #18176]  INFO -- : ec_sync_client: closing command connection handler

**no manual changes to postgresql configuration file,** 
**/var/opt/opscode/postgresql/9.2/data/pg_hba.conf**
local   all         opscode-pgsql                               peer

host    all         opscode-pgsql         samehost           md5

host    all         all         127.0.0.1/32           md5
host    all         all         ::1/128           md5

**Comment by cyan-novartis** [comment]
**In pg_hba.conf, changed**
-host all all 127.0.0.1/32 md5
+host all all 127.0.0.1/32 trust

This get around the initial/above error. However, master does not seem to respond correctly. **500 is the http return code.**

_details:_
chef-sync client log,
2016-05-06_19:07:26.74966 I, [2016-05-06T15:07:26.749632 #18176]  INFO -- : ec_sync_client: starting worker for rcp
2016-05-06_19:07:26.76882 I, [2016-05-06T15:07:26.768708 #18176]  INFO -- : ec_sync_client: closing command connection handler
2016-05-06_19:07:27.69516 I, [2016-05-06T15:07:27.695117 #18176]  INFO -- : rcp: boostrap started at 2016-05-06 15:07:27 -0400
2016-05-06_19:07:27.90124 I, [2016-05-06T15:07:27.901142 #18176]  INFO -- : rcp: ERROR! bootstrap failed: 500 "Internal Server Error"
2016-05-06_19:07:27.90140 /opt/chef-sync/embedded/lib/ruby/1.9.1/net/http.rb:2633:in `error!': 500 "Internal Server Error" (Net::HTTPFatalError)
2016-05-06_19:07:27.90155 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/http.rb:143:in `request'
2016-05-06_19:07:27.90159 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/rest.rb:115:in `get'
2016-05-06_19:07:27.90164 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/org.rb:49:in `update_log'
2016-05-06_19:07:27.90168 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/orgsyncer.rb:129:in `bootstrap'
2016-05-06_19:07:27.90173 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/orgsyncer.rb:54:in `start'
2016-05-06_19:07:27.90177 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:114:in `block in start_worker'
2016-05-06_19:07:27.90181 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:110:in `fork'
2016-05-06_19:07:27.90185 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:110:in `start_worker'
2016-05-06_19:07:27.90189 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:191:in `block in handle_command_connection'
2016-05-06_19:07:27.90194 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:163:in `loop'
2016-05-06_19:07:27.90215 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:163:in `handle_command_connection'
2016-05-06_19:07:27.90223 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:139:in `block (3 levels) in manage'
2016-05-06_19:07:27.93580 I, [2016-05-06T15:07:27.935625 #18176]  INFO -- : Worker for rcp died unexpectedly!

**chef-sync server access log,**
**/var/log/opscode/nginx/current**
160.62.191.114 - - [06/May/2016:15:07:28 -0400]  "GET /organizations/rcp HTTP/1.1" 200 "0.036" 91 "-" "-" "127.0.0.1:8000" "200" "0.035" "11.0.1" "version=1.1" "pivotal" "2016-05-06T19:07:27Z" "2jmj7l5rSw0yVb/vlWAYkK/YBwk=" 775
160.62.191.114 - - [06/May/2016:15:07:28 -0400]  "GET /organizations/rcp HTTP/1.1" 200 "0.014" 91 "-" "-" "127.0.0.1:8000" "200" "0.014" "11.0.1" "version=1.1" "pivotal" "2016-05-06T19:07:28Z" "2jmj7l5rSw0yVb/vlWAYkK/YBwk=" 775
160.62.191.12 - - [06/May/2016:15:07:28 -0400]  "GET /organizations/rcp/objects_since?seq=0 HTTP/1.1" 500 "0.179" 962 "-" "Chef Client/11.14.0.alpha.5 (ruby-1.9.3-p550; ohai-7.2.0.alpha.0; x86_64-linux; +http://opscode.com)" "127.0.0.1:9996" "500" "0.179" "11.14.0.alpha.5" "algorithm=sha1;version=1.0;" "ec_sync_user" "2016-05-06T19:07:27Z" "2jmj7l5rSw0yVb/vlWAYkK/YBwk=" 1060

**chef-sync log**
**/var/log/opscode/chef-sync/server/current**
2016-05-06_19:07:28.15699 =SUPERVISOR REPORT==== 6-May-2016::15:07:28 ===
2016-05-06_19:07:28.15700      Supervisor: {local,pooler_sqerl_member_sup}
2016-05-06_19:07:28.15700      Context:    child_terminated
2016-05-06_19:07:28.15700      Reason:     invalid_password
2016-05-06_19:07:28.15700      Offender:   [{pid,<0.4266.0>},
2016-05-06_19:07:28.15700                   {name,sqerl_client},
2016-05-06_19:07:28.15701                   {mfargs,{sqerl_client,start_link,undefined}},
2016-05-06_19:07:28.15701                   {restart_type,temporary},
2016-05-06_19:07:28.15701                   {shutdown,brutal_kill},
2016-05-06_19:07:28.15701                   {child_type,worker}]

**This seems to indicate it is pg_hba.conf issue as well.**

**Comment by cyan-novartis** [comment]
**on master chef server, in pg_hba.conf, changed**
-host all all 127.0.0.1/32 md5
+host all all 127.0.0.1/32 trust

**chef-sync client error is 401 "Unauthorized"**
**/var/log/opscode/chef-sync/client/current**
2016-05-06_19:25:50.55266 I, [2016-05-06T15:25:50.552622 #18176]  INFO -- : ec_sync_client: starting worker for rcp
2016-05-06_19:25:50.55938 I, [2016-05-06T15:25:50.559309 #18176]  INFO -- : ec_sync_client: closing command connection handler
2016-05-06_19:25:51.23717 I, [2016-05-06T15:25:51.237129 #18176]  INFO -- : rcp: boostrap started at 2016-05-06 15:25:51 -0400
2016-05-06_19:25:52.81412 /opt/chef-sync/embedded/lib/ruby/1.9.1/net/http.rb:2633:in `error!'I, [2016-05-06T15:25:52.814473 #18176]  INFO -- : rcp: ERROR! bootstrap failed: 401 "Unauthorized"
2016-05-06_19:25:52.81507 : 401 "Unauthorized" (Net::HTTPServerException)
2016-05-06_19:25:52.81508 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/http.rb:143:in `request'
2016-05-06_19:25:52.81509 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/http.rb:108:in `get'
2016-05-06_19:25:52.81509 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/file_system/chef_server_root_dir.rb:64:in `get_json'
2016-05-06_19:25:52.81509 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/file_system/cookbooks_dir.rb:57:in `children'
2016-05-06_19:25:52.81510 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/file_system.rb:232:in `child_pairs'
2016-05-06_19:25:52.81510 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/file_system.rb:360:in `copy_entries'
2016-05-06_19:25:52.81511 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/file_system.rb:361:in `block in copy_entries'
2016-05-06_19:25:52.81512 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `call'
2016-05-06_19:25:52.81513 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `process_input'
2016-05-06_19:25:52.81513 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:257:in `process_one'
2016-05-06_19:25:52.81514 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:195:in `each_with_exceptions_unordered'
2016-05-06_19:25:52.81514 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:74:in `wait'
2016-05-06_19:25:52.81514 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/parallelizer.rb:48:in `parallel_do'
2016-05-06_19:25:52.81515 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/parallelizer.rb:29:in `parallel_do'
2016-05-06_19:25:52.81515 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/file_system.rb:426:in `parallel_do'
2016-05-06_19:25:52.81515 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/file_system.rb:360:in `copy_entries'
2016-05-06_19:25:52.81516 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/file_system.rb:145:in `block in copy_to'
2016-05-06_19:25:52.81516 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `call'
2016-05-06_19:25:52.81516 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `process_input'
2016-05-06_19:25:52.81516 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:257:in `process_one'
2016-05-06_19:25:52.81517 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:195:in `each_with_exceptions_unordered'
2016-05-06_19:25:52.81517 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:74:in `wait'
2016-05-06_19:25:52.81518 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/parallelizer.rb:48:in `parallel_do'
2016-05-06_19:25:52.81518 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/parallelizer.rb:29:in `parallel_do'
2016-05-06_19:25:52.81519 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/file_system.rb:426:in `parallel_do'
2016-05-06_19:25:52.81519 	from /opt/chef-sync/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-fa77f1e10e85/lib/chef/chef_fs/file_system.rb:142:in `copy_to'
2016-05-06_19:25:52.81519 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/orgsyncer.rb:132:in `bootstrap'
2016-05-06_19:25:52.81519 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/orgsyncer.rb:54:in `start'
2016-05-06_19:25:52.81520 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:114:in `block in start_worker'
2016-05-06_19:25:52.81520 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:110:in `fork'
2016-05-06_19:25:52.81521 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:110:in `start_worker'
2016-05-06_19:25:52.81521 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:191:in `block in handle_command_connection'
2016-05-06_19:25:52.81521 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:163:in `loop'
2016-05-06_19:25:52.81521 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:163:in `handle_command_connection'
2016-05-06_19:25:52.81522 	from /opt/chef-sync/embedded/service/ec_sync_client/lib/ec_sync_client/sync_manager.rb:139:in `block (3 levels) in manage'
2016-05-06_19:25:52.85760 I, [2016-05-06T15:25:52.857488 #18176]  INFO -- : Worker for rcp died unexpectedly!

**Comment by cyan-novartis** [comment]
The issue is the caused by postgresql conf.

after changes to pg_hba.conf, on both master and replica, replication/sync works correctly.

-host all all 127.0.0.1/32 md5
+host all all 127.0.0.1/32 trust

**Comment by cyan-novartis** [comment]
line 69-71 of chef-server/omnibus/files/private-chef-cookbooks/private-chef/templates/default/pg_hba.conf.erb is listed, line 70 is causing the issue.

<% node['private_chef']['postgresql']['md5_auth_cidr_addresses'].each do |cidr| %>
host    all         all         <%= cidr %>           md5
<% end %>

**Comment by stevendanna** [comment]
Thank you for trying chef-sync and taking the time to file this
ticket. I am sorry you haven't received more feedback on this
issue before now.

Chef sync is no longer an actively developed product as it saw
very little adoption in our user base.  No further development is
planned for Chef sync.

I am closing this ticket. However, if you already have a Chef
sync deployment and still require further assistance, please
contact support at support@chef.io.
