### ISSUE TITLE
Ubuntu 14.04 chef-server 12.8.0 - Recipe Compile Error on chef-server-ctl reconfigure

### ISSUE THREAD

**Issue by safematix** [chef/chef-server#877]
If I try chef server to start on a lxd image, I get the following error messages:

- lxd image: ubuntu:14.04
- package: chef-server-core_12.8.0-1_amd64.deb

```
root@chef-server:~# dpkg -i chef-server-core_12.8.0-1_amd64.deb
Selecting previously unselected package chef-server-core.
(Reading database ... 25003 files and directories currently installed.)
Preparing to unpack chef-server-core_12.8.0-1_amd64.deb ...
Unpacking chef-server-core (12.8.0-1) ...
Setting up chef-server-core (12.8.0-1) ...
```

First run:

```
root@chef-server:~# chef-server-ctl reconfigure
Starting Chef Client, version 12.12.19
resolving cookbooks for run list: ["private-chef::default"]
Synchronizing Cookbooks:
  - private-chef (0.1.0)
  - enterprise (0.10.1)
  - apt (2.9.2)
  - yum (3.11.0)
  - openssl (4.4.0)
  - runit (1.6.0)
  - chef-sugar (3.3.0)
  - packagecloud (0.2.4)
Installing Cookbook Gems:
Compiling Cookbooks...
[2016-07-10T09:44:48+00:00] WARN: Chef::Provider::AptRepository already exists!  Cannot create deprecation class for LWRP provider apt_repository from cookbook apt
[2016-07-10T09:44:48+00:00] WARN: AptRepository already exists!  Deprecation class overwrites Custom resource apt_repository from cookbook apt
Recipe: private-chef::default
  * directory[/etc/opscode] action create (up to date)
  * directory[/etc/opscode/logrotate.d] action create
    - create new directory /etc/opscode/logrotate.d
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'

  ================================================================================
  Recipe Compile Error in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb
  ================================================================================

  Chef::Exceptions::ValidationFailed
  ----------------------------------
  common_name is required

  Cookbook Trace:
  ---------------
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/nginx.rb:58:in `block in from_file'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/nginx.rb:57:in `from_file'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:159:in `block in from_file'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:142:in `each'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:142:in `from_file'

  Relevant File Content:
  ----------------------
  /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/nginx.rb:

   51:
   52:  ssl_keyfile = File.join(nginx_ca_dir, "#{node['private_chef']['nginx']['server_name']}.key")
   53:  ssl_crtfile = File.join(nginx_ca_dir, "#{node['private_chef']['nginx']['server_name']}.crt")
   54:  ssl_dhparam = File.join(nginx_ca_dir, 'dhparams.pem')
   55:
   56:  # Generate self-signed SSL certificate
   57:  openssl_x509 ssl_crtfile do
   58>>   common_name node['private_chef']['nginx']['server_name']
   59:    org node['private_chef']['nginx']['ssl_company_name']
   60:    org_unit node['private_chef']['nginx']['ssl_organizational_unit_name']
   61:    country node['private_chef']['nginx']['ssl_country_name']
   62:    key_length node['private_chef']['nginx']['ssl_key_length']
   63:    expire node['private_chef']['nginx']['ssl_duration']
   64:    owner 'root'
   65:    group 'root'
   66:    mode '0644'
   67:  end

  Platform:
  ---------
  x86_64-linux


  Running handlers:
[2016-07-10T09:44:49+00:00] ERROR: Running exception handlers
  Running handlers complete
[2016-07-10T09:44:49+00:00] ERROR: Exception handlers complete
  Chef Client failed. 1 resources updated in 05 seconds
[2016-07-10T09:44:49+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2016-07-10T09:44:49+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-07-10T09:44:49+00:00] FATAL: Chef::Exceptions::ValidationFailed: common_name is required
```

Second run: 

```
root@chef-server:~# chef-server-ctl reconfigure
Starting Chef Client, version 12.12.19
resolving cookbooks for run list: ["private-chef::default"]
Synchronizing Cookbooks:
  - private-chef (0.1.0)
  - enterprise (0.10.1)
  - apt (2.9.2)
  - yum (3.11.0)
  - openssl (4.4.0)
  - runit (1.6.0)
  - chef-sugar (3.3.0)
  - packagecloud (0.2.4)
Installing Cookbook Gems:
Compiling Cookbooks...
[2016-07-10T09:45:37+00:00] WARN: Chef::Provider::AptRepository already exists!  Cannot create deprecation class for LWRP provider apt_repository from cookbook apt
[2016-07-10T09:45:37+00:00] WARN: AptRepository already exists!  Deprecation class overwrites Custom resource apt_repository from cookbook apt
Recipe: private-chef::default
  * directory[/etc/opscode] action create (up to date)
  * directory[/etc/opscode/logrotate.d] action create (up to date)
[2016-07-10T09:45:37+00:00] FATAL:

-----------------------------------------------------------------------
BOOT007: The secrets file (/etc/opscode/private-chef-secrets.json) is present
         but the file /etc/opscode/pivotal.pem is missing.

         Ensure that private-chef-secrets.json is copied into /etc/opscode from the
         first Chef Server node that you brought online, then run
         'chef-server-ctl reconfigure' again.
-----------------------------------------------------------------------
```

**Comment by safematix** [comment]
My mistake. 

Easy to fix:

- Set correct hostname
- Set the hostname in /etc/hosts
