### ISSUE TITLE
unbale to fix the rabbitmq issue while executing 'sudo chef-server-ctl reconfigure'

### ISSUE THREAD

**Issue by nadarashwin** [chef/chef-server#916]
I am using chef-server-core-12.8.0-1.el6.x86_64.rpm
Got the rpm installed successfully on "Red Hat Enterprise Linux Server release 6.2 (Santiago)" 64 bit.
When  i perform  'sudo chef-server-ctl reconfigure' stuck with the following error prompt.

    ================================================================================
    Error executing action `run` on resource 'execute[/opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '2'
    ---- Begin output of /opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid ----
    STDOUT: Waiting for rabbit@localhost ...
    pid is 22760 ...
    STDERR: Error: process_not_running
    ---- End output of /opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid ----
    Ran /opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid returned 2

    Resource Declaration:
    ---------------------
    # In /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/rabbitmq.rb

    121:   execute "#{rmq_ctl_chpst} wait #{rabbitmq_data_dir}/#{rabbitmq['nodename']}.pid" do
    122:     environment rabbitmq_env
    123:     retries 10
    124:   end
    125:

    Compiled Resource:
    ------------------
    # Declared in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/rabbitmq.rb:121:in `from_file'

    execute("/opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid") do
      action [:run]
      retries 10
      retry_delay 2
      default_guard_interpreter :execute
      command "/opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid"
      backup 5
      environment {"HOSTNAME"=>"psvlxodweb1", "SHELL"=>"/bin/bash", "TERM"=>"xterm", "HISTSIZE"=>"1000", "QTDIR"=>"/usr/lib64/qt-3.3", "USER"=>"root", "LS_COLORS"=>"rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.tbz=01;31:*.tbz2=01;31:*.bz=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:", "SUDO_USER"=>"infaops", "SUDO_UID"=>"500", "USERNAME"=>"root", "PATH"=>"/opt/opscode/bin:/opt/opscode/embedded/bin:/usr/bin:/bin", "MAIL"=>"/var/spool/mail/infaops", "PWD"=>"/home/ondemand", "LANG"=>"en_US.UTF-8", "SVWAIT"=>"30", "SHLVL"=>"1", "SUDO_COMMAND"=>"/usr/bin/chef-server-ctl reconfigure", "HOME"=>"/root", "LOGNAME"=>"root", "SUDO_GID"=>"100", "DISPLAY"=>"localhost:11.0", "_"=>"/opt/opscode/embedded/service/omnibus-ctl/chef-server-ctl"}
      returns 0
      declared_type :execute
      cookbook_name "private-chef"
      recipe_name "rabbitmq"
    end

    Platform:
    ---------
    x86_64-linux

  * execute[restart_rabbitmq_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/rabbitmq/log

Running handlers:
[2016-08-25T04:45:56-07:00] ERROR: Running exception handlers
Running handlers complete
[2016-08-25T04:45:56-07:00] ERROR: Exception handlers complete
Chef Client failed. 30 resources updated in 01 minutes 05 seconds
[2016-08-25T04:45:56-07:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2016-08-25T04:45:56-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-08-25T04:45:57-07:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[/opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid] (private-chef::rabbitmq line 121) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of /opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid ----
STDOUT: Waiting for rabbit@localhost ...
pid is 22760 ...
STDERR: Error: process_not_running
---- End output of /opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid ----
Ran /opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid returned 2

**Comment by nadarashwin** [comment]
under ps -ef i get the following
<snip>


opscode  13469     1  2 03:55 ?        00:01:42 /opt/opscode/embedded/lib/erlang/erts-6.4/bin/beam.smp -W w -K true -A30 -P 1048576 -- -root /opt/opscode/embedded/lib/erlang -progname erl -- -home /var/opt/opscode/rabbitmq -- -pa /opt/opscode/embedded/service/rabbitmq/sbin/../ebin -noshell -noinput -s rabbit boot -sname rabbit@localhost -boot start_sasl -config /var/opt/opscode/rabbitmq/etc/rabbitmq -kernel inet_default_connect_options [{nodelay,true}] -rabbit tcp_listeners [{"127.0.0.1",5672}] -sasl errlog_type error -sasl sasl_error_logger false -rabbit error_logger {file,"/var/opt/opscode/rabbitmq/log/rabbit@localhost.log"} -rabbit sasl_error_logger {file,"/var/opt/opscode/rabbitmq/log/rabbit@localhost-sasl.log"} -rabbit enabled_plugins_file "/var/opt/opscode/rabbitmq/etc/enabled_plugins" -rabbit plugins_dir "/opt/opscode/embedded/service/rabbitmq/sbin/../plugins" -rabbit plugins_expand_dir "/var/opt/opscode/rabbitmq/db/rabbit@localhost-plugins-expand" -os_mon start_cpu_sup false -os_mon start_disksup false -os_mon start_memsup false -mnesia dir "/var/opt/opscode/rabbitmq/db/rabbit@localhost" -kernel inet_dist_listen_min 25672 -kernel inet_dist_listen_max 25672
root     13557     1  0 03:55 ?        00:00:00 runsvdir -P /opt/opscode/service log: runsv rabbitmq: fatal: unable to start ./run: file does not exist?runsv rabbitmq: warning: unable to open supervise/pid.new: file does not exist?runsv rabbitmq: warning: unable to open supervise/pid.new: file does not exist?runsv rabbitmq: warning: unable to open log/supervise/pid.new: file does not exist?runsv rabbitmq: warning: unable to open log/supervise/pid.new: file does not exist?.....
opscode  16615 21277  0 05:20 ?        00:00:00 /bin/sh -e /opt/opscode/embedded/bin/rabbitmq-server
opscode  16624 16615  0 05:20 ?        00:00:00 /opt/opscode/embedded/lib/erlang/erts-6.4/bin/beam.smp -- -root /opt/opscode/embedded/lib/erlang -progname erl -- -home /var/opt/opscode/rabbitmq -- -pa /opt/opscode/embedded/service/rabbitmq/sbin/../ebin -boot start_clean -noshell -noinput -hidden -s rabbit_prelaunch -sname rabbitmqprelaunch16615 -extra rabbit@localhost
infaops  16651  1157  0 05:20 pts/0    00:00:00 grep rabbit
root     21277 13557  0 04:45 ?        00:00:01 runsv rabbitmq
opscode  22817 21277  0 04:45 ?        00:00:00 svlogd -tt /var/log/opscode/rabbitmq

<>/snip



and on '/var/opt/opscode/local-mode-cache/chef-stacktrace.out'

<snip>
Generated at 2016-08-25 04:45:56 -0700
Mixlib::ShellOut::ShellCommandFailed: execute[/opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid] (private-chef::rabbitmq line 121) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of /opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid ----
STDOUT: Waiting for rabbit@localhost ...
pid is 22760 ...
STDERR: Error: process_not_running
---- End output of /opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid ----
Ran /opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid returned 2
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:276:in `error!'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/mixin/shell_out.rb:45:in `shell_out!'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/provider/execute.rb:62:in `block in action_run'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/provider.rb:176:in `converge_by'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/provider/execute.rb:60:in `action_run'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/provider.rb:145:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/resource.rb:591:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/runner.rb:69:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/runner.rb:97:in `block (2 levels) in converge'


</snip>

**Comment by nadarashwin** [comment]
well not sure what happened but when i opened a new session  and started to deploy the same everything worked fine.
something to do with environment variables it seems not sure though
