### ISSUE TITLE
error in chef-server-ctl reconfigure in docker.

### ISSUE THREAD

**Issue by argentum47** [chef/chef-server#960]
I installed centos latest version on docker. and then I downloaded the red hat latest chef-server-core distribution and installed it .
After that I ran a `chef-server-ctl reconfigure`. and it threw an error:

 Error executing action `create` on resource 'component_runit_supervisor[private_chef]'
    ==============================================================================  
    ArgumentError
    -------------
    wrong number of arguments (2 for 0)

``````
Resource Declaration:
---------------------
# In /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb

```
 28: component_runit_supervisor node['enterprise']['name'] do
 29:   ctl_name node[node['enterprise']['name']]['ctl_name'] ||
 30:            "#{node['enterprise']['name']}-ctl"
 31:   sysvinit_id node[node['enterprise']['name']]['sysvinit_id']
 32:   install_path node[node['enterprise']['name']]['install_path']
 33: end
``````

``````
Compiled Resource:
    ------------------
    # Declared in /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:28:in `from_file'

    ```
    component_runit_supervisor("private_chef") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :component_runit_supervisor
      cookbook_name "enterprise"
      recipe_name "runit"
      ctl_name "private_chef-ctl"
      sysvinit_id "SV"
      install_path "/opt/opscode"
    end
``````

```
Platform:
---------
x86_64-linux
```

Running handlers:

```
[2016-10-07T10:34:18+00:00] ERROR: Running exception handlers
Running handlers complete
[2016-10-07T10:34:18+00:00] ERROR: Exception handlers complete
Chef Client failed. 9 resources updated in 12 seconds
[2016-10-07T10:34:18+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2016-10-07T10:34:18+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-10-07T10:34:18+00:00] FATAL: ArgumentError: component_runit_supervisor[private_chef] (enterprise::runit line 28) had an error: ArgumentError: wrong number of arguments (2 for 0)
```

How to I solve this.. I also am not sure if this is a docker setup error, like exposing something..

I also tried the `base/chef-server` package. but it also throws an error .. `errconnrefused while connecting to 127.0.0.1 over port 5627` (or someport)

cat of stracktrace.out

```
[root@4aa1bbc8f44b local-mode-cache]# cat chef-stacktrace.out 
Generated at 2016-10-07 12:22:51 +0000
ArgumentError: component_runit_supervisor[private_chef] (enterprise::runit line 28) had an error: ArgumentError: wrong number of arguments (2 for 0)
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource.rb:1453:in `initialize'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource.rb:1453:in `new'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource.rb:1453:in `provider_for_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource.rb:603:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/runner.rb:69:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/runner.rb:97:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/runner.rb:97:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/stepable_iterator.rb:114:in `call'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/runner.rb:96:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/client.rb:669:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/client.rb:664:in `catch'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/client.rb:664:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/client.rb:703:in `converge_and_save'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/client.rb:283:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/application.rb:284:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/application.rb:260:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/application.rb:243:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/application/client.rb:427:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/application.rb:60:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/bin/chef-client:26:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:22:in `load'
/opt/opscode/embedded/bin/chef-client:22:in `<main>'

>>>> Caused by ArgumentError: wrong number of arguments (2 for 0)
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource.rb:1453:in `initialize'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource.rb:1453:in `new'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource.rb:1453:in `provider_for_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource.rb:603:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/runner.rb:69:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/runner.rb:97:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/runner.rb:97:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/stepable_iterator.rb:114:in `call'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/runner.rb:96:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/client.rb:669:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/client.rb:664:in `catch'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/client.rb:664:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/client.rb:703:in `converge_and_save'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/client.rb:283:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/application.rb:284:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/application.rb:260:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/application.rb:243:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/application/client.rb:427:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/application.rb:60:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/bin/chef-client:26:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:22:in `load'
/opt/opscode/embedded/bin/chef-client:22:in `<main>'
```

**Comment by prparmar77** [comment]
I am facing same issue in docker 1.12 container ..

**Comment by marcparadise** [comment]
While docker is not a supported configuration at this time, I have been able to get Chef Server running by following the steps detailed here:
https://github.com/chef/chef-server/issues/62#issuecomment-226949526

You could also look at installing `supervisor` as an alternative.
